/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the ListStoryDevelopments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListStoryDevelopments200Response{}

// ListStoryDevelopments200Response struct for ListStoryDevelopments200Response
type ListStoryDevelopments200Response struct {
	Developments []StoryDevelopment `json:"developments,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewListStoryDevelopments200Response instantiates a new ListStoryDevelopments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListStoryDevelopments200Response() *ListStoryDevelopments200Response {
	this := ListStoryDevelopments200Response{}
	return &this
}

// NewListStoryDevelopments200ResponseWithDefaults instantiates a new ListStoryDevelopments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListStoryDevelopments200ResponseWithDefaults() *ListStoryDevelopments200Response {
	this := ListStoryDevelopments200Response{}
	return &this
}

// GetDevelopments returns the Developments field value if set, zero value otherwise.
func (o *ListStoryDevelopments200Response) GetDevelopments() []StoryDevelopment {
	if o == nil || IsNil(o.Developments) {
		var ret []StoryDevelopment
		return ret
	}
	return o.Developments
}

// GetDevelopmentsOk returns a tuple with the Developments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListStoryDevelopments200Response) GetDevelopmentsOk() ([]StoryDevelopment, bool) {
	if o == nil || IsNil(o.Developments) {
		return nil, false
	}
	return o.Developments, true
}

// HasDevelopments returns a boolean if a field has been set.
func (o *ListStoryDevelopments200Response) HasDevelopments() bool {
	if o != nil && !IsNil(o.Developments) {
		return true
	}

	return false
}

// SetDevelopments gets a reference to the given []StoryDevelopment and assigns it to the Developments field.
func (o *ListStoryDevelopments200Response) SetDevelopments(v []StoryDevelopment) {
	o.Developments = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ListStoryDevelopments200Response) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListStoryDevelopments200Response) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ListStoryDevelopments200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ListStoryDevelopments200Response) SetCount(v int32) {
	o.Count = &v
}

func (o ListStoryDevelopments200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListStoryDevelopments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Developments) {
		toSerialize["developments"] = o.Developments
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableListStoryDevelopments200Response struct {
	value *ListStoryDevelopments200Response
	isSet bool
}

func (v NullableListStoryDevelopments200Response) Get() *ListStoryDevelopments200Response {
	return v.value
}

func (v *NullableListStoryDevelopments200Response) Set(val *ListStoryDevelopments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListStoryDevelopments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListStoryDevelopments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListStoryDevelopments200Response(val *ListStoryDevelopments200Response) *NullableListStoryDevelopments200Response {
	return &NullableListStoryDevelopments200Response{value: val, isSet: true}
}

func (v NullableListStoryDevelopments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListStoryDevelopments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


