/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// GetEmbedding200ResponseEmbedding - struct for GetEmbedding200ResponseEmbedding
type GetEmbedding200ResponseEmbedding struct {
	ArrayOfFloat32 *[]float32
	String *string
}

// []float32AsGetEmbedding200ResponseEmbedding is a convenience function that returns []float32 wrapped in GetEmbedding200ResponseEmbedding
func ArrayOfFloat32AsGetEmbedding200ResponseEmbedding(v *[]float32) GetEmbedding200ResponseEmbedding {
	return GetEmbedding200ResponseEmbedding{
		ArrayOfFloat32: v,
	}
}

// stringAsGetEmbedding200ResponseEmbedding is a convenience function that returns string wrapped in GetEmbedding200ResponseEmbedding
func StringAsGetEmbedding200ResponseEmbedding(v *string) GetEmbedding200ResponseEmbedding {
	return GetEmbedding200ResponseEmbedding{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetEmbedding200ResponseEmbedding) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfFloat32
	err = newStrictDecoder(data).Decode(&dst.ArrayOfFloat32)
	if err == nil {
		jsonArrayOfFloat32, _ := json.Marshal(dst.ArrayOfFloat32)
		if string(jsonArrayOfFloat32) == "{}" { // empty struct
			dst.ArrayOfFloat32 = nil
		} else {
			if err = validator.Validate(dst.ArrayOfFloat32); err != nil {
				dst.ArrayOfFloat32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfFloat32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfFloat32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetEmbedding200ResponseEmbedding)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetEmbedding200ResponseEmbedding)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetEmbedding200ResponseEmbedding) MarshalJSON() ([]byte, error) {
	if src.ArrayOfFloat32 != nil {
		return json.Marshal(&src.ArrayOfFloat32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetEmbedding200ResponseEmbedding) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfFloat32 != nil {
		return obj.ArrayOfFloat32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGetEmbedding200ResponseEmbedding struct {
	value *GetEmbedding200ResponseEmbedding
	isSet bool
}

func (v NullableGetEmbedding200ResponseEmbedding) Get() *GetEmbedding200ResponseEmbedding {
	return v.value
}

func (v *NullableGetEmbedding200ResponseEmbedding) Set(val *GetEmbedding200ResponseEmbedding) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmbedding200ResponseEmbedding) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmbedding200ResponseEmbedding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmbedding200ResponseEmbedding(val *GetEmbedding200ResponseEmbedding) *NullableGetEmbedding200ResponseEmbedding {
	return &NullableGetEmbedding200ResponseEmbedding{value: val, isSet: true}
}

func (v NullableGetEmbedding200ResponseEmbedding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmbedding200ResponseEmbedding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


