/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the SearchSuggest200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchSuggest200Response{}

// SearchSuggest200Response struct for SearchSuggest200Response
type SearchSuggest200Response struct {
	Suggestions []string `json:"suggestions,omitempty"`
}

// NewSearchSuggest200Response instantiates a new SearchSuggest200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchSuggest200Response() *SearchSuggest200Response {
	this := SearchSuggest200Response{}
	return &this
}

// NewSearchSuggest200ResponseWithDefaults instantiates a new SearchSuggest200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchSuggest200ResponseWithDefaults() *SearchSuggest200Response {
	this := SearchSuggest200Response{}
	return &this
}

// GetSuggestions returns the Suggestions field value if set, zero value otherwise.
func (o *SearchSuggest200Response) GetSuggestions() []string {
	if o == nil || IsNil(o.Suggestions) {
		var ret []string
		return ret
	}
	return o.Suggestions
}

// GetSuggestionsOk returns a tuple with the Suggestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchSuggest200Response) GetSuggestionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Suggestions) {
		return nil, false
	}
	return o.Suggestions, true
}

// HasSuggestions returns a boolean if a field has been set.
func (o *SearchSuggest200Response) HasSuggestions() bool {
	if o != nil && !IsNil(o.Suggestions) {
		return true
	}

	return false
}

// SetSuggestions gets a reference to the given []string and assigns it to the Suggestions field.
func (o *SearchSuggest200Response) SetSuggestions(v []string) {
	o.Suggestions = v
}

func (o SearchSuggest200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchSuggest200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Suggestions) {
		toSerialize["suggestions"] = o.Suggestions
	}
	return toSerialize, nil
}

type NullableSearchSuggest200Response struct {
	value *SearchSuggest200Response
	isSet bool
}

func (v NullableSearchSuggest200Response) Get() *SearchSuggest200Response {
	return v.value
}

func (v *NullableSearchSuggest200Response) Set(val *SearchSuggest200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSuggest200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSuggest200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSuggest200Response(val *SearchSuggest200Response) *NullableSearchSuggest200Response {
	return &NullableSearchSuggest200Response{value: val, isSet: true}
}

func (v NullableSearchSuggest200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSuggest200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


