/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetStoryEntityGraph200ResponseEdgesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStoryEntityGraph200ResponseEdgesInner{}

// GetStoryEntityGraph200ResponseEdgesInner struct for GetStoryEntityGraph200ResponseEdgesInner
type GetStoryEntityGraph200ResponseEdgesInner struct {
	StoryId *int32 `json:"story_id,omitempty"`
	EntityId *int32 `json:"entity_id,omitempty"`
	MentionCount *int32 `json:"mention_count,omitempty"`
}

// NewGetStoryEntityGraph200ResponseEdgesInner instantiates a new GetStoryEntityGraph200ResponseEdgesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStoryEntityGraph200ResponseEdgesInner() *GetStoryEntityGraph200ResponseEdgesInner {
	this := GetStoryEntityGraph200ResponseEdgesInner{}
	return &this
}

// NewGetStoryEntityGraph200ResponseEdgesInnerWithDefaults instantiates a new GetStoryEntityGraph200ResponseEdgesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStoryEntityGraph200ResponseEdgesInnerWithDefaults() *GetStoryEntityGraph200ResponseEdgesInner {
	this := GetStoryEntityGraph200ResponseEdgesInner{}
	return &this
}

// GetStoryId returns the StoryId field value if set, zero value otherwise.
func (o *GetStoryEntityGraph200ResponseEdgesInner) GetStoryId() int32 {
	if o == nil || IsNil(o.StoryId) {
		var ret int32
		return ret
	}
	return *o.StoryId
}

// GetStoryIdOk returns a tuple with the StoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStoryEntityGraph200ResponseEdgesInner) GetStoryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.StoryId) {
		return nil, false
	}
	return o.StoryId, true
}

// HasStoryId returns a boolean if a field has been set.
func (o *GetStoryEntityGraph200ResponseEdgesInner) HasStoryId() bool {
	if o != nil && !IsNil(o.StoryId) {
		return true
	}

	return false
}

// SetStoryId gets a reference to the given int32 and assigns it to the StoryId field.
func (o *GetStoryEntityGraph200ResponseEdgesInner) SetStoryId(v int32) {
	o.StoryId = &v
}

// GetEntityId returns the EntityId field value if set, zero value otherwise.
func (o *GetStoryEntityGraph200ResponseEdgesInner) GetEntityId() int32 {
	if o == nil || IsNil(o.EntityId) {
		var ret int32
		return ret
	}
	return *o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStoryEntityGraph200ResponseEdgesInner) GetEntityIdOk() (*int32, bool) {
	if o == nil || IsNil(o.EntityId) {
		return nil, false
	}
	return o.EntityId, true
}

// HasEntityId returns a boolean if a field has been set.
func (o *GetStoryEntityGraph200ResponseEdgesInner) HasEntityId() bool {
	if o != nil && !IsNil(o.EntityId) {
		return true
	}

	return false
}

// SetEntityId gets a reference to the given int32 and assigns it to the EntityId field.
func (o *GetStoryEntityGraph200ResponseEdgesInner) SetEntityId(v int32) {
	o.EntityId = &v
}

// GetMentionCount returns the MentionCount field value if set, zero value otherwise.
func (o *GetStoryEntityGraph200ResponseEdgesInner) GetMentionCount() int32 {
	if o == nil || IsNil(o.MentionCount) {
		var ret int32
		return ret
	}
	return *o.MentionCount
}

// GetMentionCountOk returns a tuple with the MentionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStoryEntityGraph200ResponseEdgesInner) GetMentionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MentionCount) {
		return nil, false
	}
	return o.MentionCount, true
}

// HasMentionCount returns a boolean if a field has been set.
func (o *GetStoryEntityGraph200ResponseEdgesInner) HasMentionCount() bool {
	if o != nil && !IsNil(o.MentionCount) {
		return true
	}

	return false
}

// SetMentionCount gets a reference to the given int32 and assigns it to the MentionCount field.
func (o *GetStoryEntityGraph200ResponseEdgesInner) SetMentionCount(v int32) {
	o.MentionCount = &v
}

func (o GetStoryEntityGraph200ResponseEdgesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStoryEntityGraph200ResponseEdgesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StoryId) {
		toSerialize["story_id"] = o.StoryId
	}
	if !IsNil(o.EntityId) {
		toSerialize["entity_id"] = o.EntityId
	}
	if !IsNil(o.MentionCount) {
		toSerialize["mention_count"] = o.MentionCount
	}
	return toSerialize, nil
}

type NullableGetStoryEntityGraph200ResponseEdgesInner struct {
	value *GetStoryEntityGraph200ResponseEdgesInner
	isSet bool
}

func (v NullableGetStoryEntityGraph200ResponseEdgesInner) Get() *GetStoryEntityGraph200ResponseEdgesInner {
	return v.value
}

func (v *NullableGetStoryEntityGraph200ResponseEdgesInner) Set(val *GetStoryEntityGraph200ResponseEdgesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStoryEntityGraph200ResponseEdgesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStoryEntityGraph200ResponseEdgesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStoryEntityGraph200ResponseEdgesInner(val *GetStoryEntityGraph200ResponseEdgesInner) *NullableGetStoryEntityGraph200ResponseEdgesInner {
	return &NullableGetStoryEntityGraph200ResponseEdgesInner{value: val, isSet: true}
}

func (v NullableGetStoryEntityGraph200ResponseEdgesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStoryEntityGraph200ResponseEdgesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


