/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the StoryUpdateSignal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoryUpdateSignal{}

// StoryUpdateSignal struct for StoryUpdateSignal
type StoryUpdateSignal struct {
	ClusterId *int32 `json:"cluster_id,omitempty"`
	NewArticles []StoryUpdateSignalNewArticlesInner `json:"new_articles,omitempty"`
	NewArticleCount *int32 `json:"new_article_count,omitempty"`
	NewSources []string `json:"new_sources,omitempty"`
	NewEntities []string `json:"new_entities,omitempty"`
	Significance *string `json:"significance,omitempty"`
	SignificanceReasons []string `json:"significance_reasons,omitempty"`
	BaselineMemberCount *int32 `json:"baseline_member_count,omitempty"`
	// Unix timestamp in milliseconds
	CheckedAtMs *int64 `json:"checked_at_ms,omitempty"`
}

// NewStoryUpdateSignal instantiates a new StoryUpdateSignal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoryUpdateSignal() *StoryUpdateSignal {
	this := StoryUpdateSignal{}
	return &this
}

// NewStoryUpdateSignalWithDefaults instantiates a new StoryUpdateSignal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoryUpdateSignalWithDefaults() *StoryUpdateSignal {
	this := StoryUpdateSignal{}
	return &this
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetClusterId() int32 {
	if o == nil || IsNil(o.ClusterId) {
		var ret int32
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetClusterIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given int32 and assigns it to the ClusterId field.
func (o *StoryUpdateSignal) SetClusterId(v int32) {
	o.ClusterId = &v
}

// GetNewArticles returns the NewArticles field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetNewArticles() []StoryUpdateSignalNewArticlesInner {
	if o == nil || IsNil(o.NewArticles) {
		var ret []StoryUpdateSignalNewArticlesInner
		return ret
	}
	return o.NewArticles
}

// GetNewArticlesOk returns a tuple with the NewArticles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetNewArticlesOk() ([]StoryUpdateSignalNewArticlesInner, bool) {
	if o == nil || IsNil(o.NewArticles) {
		return nil, false
	}
	return o.NewArticles, true
}

// HasNewArticles returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasNewArticles() bool {
	if o != nil && !IsNil(o.NewArticles) {
		return true
	}

	return false
}

// SetNewArticles gets a reference to the given []StoryUpdateSignalNewArticlesInner and assigns it to the NewArticles field.
func (o *StoryUpdateSignal) SetNewArticles(v []StoryUpdateSignalNewArticlesInner) {
	o.NewArticles = v
}

// GetNewArticleCount returns the NewArticleCount field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetNewArticleCount() int32 {
	if o == nil || IsNil(o.NewArticleCount) {
		var ret int32
		return ret
	}
	return *o.NewArticleCount
}

// GetNewArticleCountOk returns a tuple with the NewArticleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetNewArticleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.NewArticleCount) {
		return nil, false
	}
	return o.NewArticleCount, true
}

// HasNewArticleCount returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasNewArticleCount() bool {
	if o != nil && !IsNil(o.NewArticleCount) {
		return true
	}

	return false
}

// SetNewArticleCount gets a reference to the given int32 and assigns it to the NewArticleCount field.
func (o *StoryUpdateSignal) SetNewArticleCount(v int32) {
	o.NewArticleCount = &v
}

// GetNewSources returns the NewSources field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetNewSources() []string {
	if o == nil || IsNil(o.NewSources) {
		var ret []string
		return ret
	}
	return o.NewSources
}

// GetNewSourcesOk returns a tuple with the NewSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetNewSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.NewSources) {
		return nil, false
	}
	return o.NewSources, true
}

// HasNewSources returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasNewSources() bool {
	if o != nil && !IsNil(o.NewSources) {
		return true
	}

	return false
}

// SetNewSources gets a reference to the given []string and assigns it to the NewSources field.
func (o *StoryUpdateSignal) SetNewSources(v []string) {
	o.NewSources = v
}

// GetNewEntities returns the NewEntities field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetNewEntities() []string {
	if o == nil || IsNil(o.NewEntities) {
		var ret []string
		return ret
	}
	return o.NewEntities
}

// GetNewEntitiesOk returns a tuple with the NewEntities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetNewEntitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.NewEntities) {
		return nil, false
	}
	return o.NewEntities, true
}

// HasNewEntities returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasNewEntities() bool {
	if o != nil && !IsNil(o.NewEntities) {
		return true
	}

	return false
}

// SetNewEntities gets a reference to the given []string and assigns it to the NewEntities field.
func (o *StoryUpdateSignal) SetNewEntities(v []string) {
	o.NewEntities = v
}

// GetSignificance returns the Significance field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetSignificance() string {
	if o == nil || IsNil(o.Significance) {
		var ret string
		return ret
	}
	return *o.Significance
}

// GetSignificanceOk returns a tuple with the Significance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetSignificanceOk() (*string, bool) {
	if o == nil || IsNil(o.Significance) {
		return nil, false
	}
	return o.Significance, true
}

// HasSignificance returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasSignificance() bool {
	if o != nil && !IsNil(o.Significance) {
		return true
	}

	return false
}

// SetSignificance gets a reference to the given string and assigns it to the Significance field.
func (o *StoryUpdateSignal) SetSignificance(v string) {
	o.Significance = &v
}

// GetSignificanceReasons returns the SignificanceReasons field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetSignificanceReasons() []string {
	if o == nil || IsNil(o.SignificanceReasons) {
		var ret []string
		return ret
	}
	return o.SignificanceReasons
}

// GetSignificanceReasonsOk returns a tuple with the SignificanceReasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetSignificanceReasonsOk() ([]string, bool) {
	if o == nil || IsNil(o.SignificanceReasons) {
		return nil, false
	}
	return o.SignificanceReasons, true
}

// HasSignificanceReasons returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasSignificanceReasons() bool {
	if o != nil && !IsNil(o.SignificanceReasons) {
		return true
	}

	return false
}

// SetSignificanceReasons gets a reference to the given []string and assigns it to the SignificanceReasons field.
func (o *StoryUpdateSignal) SetSignificanceReasons(v []string) {
	o.SignificanceReasons = v
}

// GetBaselineMemberCount returns the BaselineMemberCount field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetBaselineMemberCount() int32 {
	if o == nil || IsNil(o.BaselineMemberCount) {
		var ret int32
		return ret
	}
	return *o.BaselineMemberCount
}

// GetBaselineMemberCountOk returns a tuple with the BaselineMemberCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetBaselineMemberCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BaselineMemberCount) {
		return nil, false
	}
	return o.BaselineMemberCount, true
}

// HasBaselineMemberCount returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasBaselineMemberCount() bool {
	if o != nil && !IsNil(o.BaselineMemberCount) {
		return true
	}

	return false
}

// SetBaselineMemberCount gets a reference to the given int32 and assigns it to the BaselineMemberCount field.
func (o *StoryUpdateSignal) SetBaselineMemberCount(v int32) {
	o.BaselineMemberCount = &v
}

// GetCheckedAtMs returns the CheckedAtMs field value if set, zero value otherwise.
func (o *StoryUpdateSignal) GetCheckedAtMs() int64 {
	if o == nil || IsNil(o.CheckedAtMs) {
		var ret int64
		return ret
	}
	return *o.CheckedAtMs
}

// GetCheckedAtMsOk returns a tuple with the CheckedAtMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignal) GetCheckedAtMsOk() (*int64, bool) {
	if o == nil || IsNil(o.CheckedAtMs) {
		return nil, false
	}
	return o.CheckedAtMs, true
}

// HasCheckedAtMs returns a boolean if a field has been set.
func (o *StoryUpdateSignal) HasCheckedAtMs() bool {
	if o != nil && !IsNil(o.CheckedAtMs) {
		return true
	}

	return false
}

// SetCheckedAtMs gets a reference to the given int64 and assigns it to the CheckedAtMs field.
func (o *StoryUpdateSignal) SetCheckedAtMs(v int64) {
	o.CheckedAtMs = &v
}

func (o StoryUpdateSignal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoryUpdateSignal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClusterId) {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if !IsNil(o.NewArticles) {
		toSerialize["new_articles"] = o.NewArticles
	}
	if !IsNil(o.NewArticleCount) {
		toSerialize["new_article_count"] = o.NewArticleCount
	}
	if !IsNil(o.NewSources) {
		toSerialize["new_sources"] = o.NewSources
	}
	if !IsNil(o.NewEntities) {
		toSerialize["new_entities"] = o.NewEntities
	}
	if !IsNil(o.Significance) {
		toSerialize["significance"] = o.Significance
	}
	if !IsNil(o.SignificanceReasons) {
		toSerialize["significance_reasons"] = o.SignificanceReasons
	}
	if !IsNil(o.BaselineMemberCount) {
		toSerialize["baseline_member_count"] = o.BaselineMemberCount
	}
	if !IsNil(o.CheckedAtMs) {
		toSerialize["checked_at_ms"] = o.CheckedAtMs
	}
	return toSerialize, nil
}

type NullableStoryUpdateSignal struct {
	value *StoryUpdateSignal
	isSet bool
}

func (v NullableStoryUpdateSignal) Get() *StoryUpdateSignal {
	return v.value
}

func (v *NullableStoryUpdateSignal) Set(val *StoryUpdateSignal) {
	v.value = val
	v.isSet = true
}

func (v NullableStoryUpdateSignal) IsSet() bool {
	return v.isSet
}

func (v *NullableStoryUpdateSignal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoryUpdateSignal(val *StoryUpdateSignal) *NullableStoryUpdateSignal {
	return &NullableStoryUpdateSignal{value: val, isSet: true}
}

func (v NullableStoryUpdateSignal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoryUpdateSignal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


