/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the EntityDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityDetail{}

// EntityDetail struct for EntityDetail
type EntityDetail struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Subcategory *string `json:"subcategory,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Description *string `json:"description,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	WikidataId *string `json:"wikidata_id,omitempty"`
	WikipediaUrl *string `json:"wikipedia_url,omitempty"`
	ArticleCount *int32 `json:"article_count,omitempty"`
	Aliases []string `json:"aliases,omitempty"`
	Enriched *bool `json:"enriched,omitempty"`
}

// NewEntityDetail instantiates a new EntityDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityDetail() *EntityDetail {
	this := EntityDetail{}
	return &this
}

// NewEntityDetailWithDefaults instantiates a new EntityDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityDetailWithDefaults() *EntityDetail {
	this := EntityDetail{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EntityDetail) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EntityDetail) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *EntityDetail) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EntityDetail) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EntityDetail) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EntityDetail) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EntityDetail) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EntityDetail) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EntityDetail) SetType(v string) {
	o.Type = &v
}

// GetSubcategory returns the Subcategory field value if set, zero value otherwise.
func (o *EntityDetail) GetSubcategory() string {
	if o == nil || IsNil(o.Subcategory) {
		var ret string
		return ret
	}
	return *o.Subcategory
}

// GetSubcategoryOk returns a tuple with the Subcategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetSubcategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Subcategory) {
		return nil, false
	}
	return o.Subcategory, true
}

// HasSubcategory returns a boolean if a field has been set.
func (o *EntityDetail) HasSubcategory() bool {
	if o != nil && !IsNil(o.Subcategory) {
		return true
	}

	return false
}

// SetSubcategory gets a reference to the given string and assigns it to the Subcategory field.
func (o *EntityDetail) SetSubcategory(v string) {
	o.Subcategory = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *EntityDetail) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *EntityDetail) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *EntityDetail) SetSlug(v string) {
	o.Slug = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EntityDetail) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EntityDetail) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EntityDetail) SetDescription(v string) {
	o.Description = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *EntityDetail) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *EntityDetail) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *EntityDetail) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetWikidataId returns the WikidataId field value if set, zero value otherwise.
func (o *EntityDetail) GetWikidataId() string {
	if o == nil || IsNil(o.WikidataId) {
		var ret string
		return ret
	}
	return *o.WikidataId
}

// GetWikidataIdOk returns a tuple with the WikidataId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetWikidataIdOk() (*string, bool) {
	if o == nil || IsNil(o.WikidataId) {
		return nil, false
	}
	return o.WikidataId, true
}

// HasWikidataId returns a boolean if a field has been set.
func (o *EntityDetail) HasWikidataId() bool {
	if o != nil && !IsNil(o.WikidataId) {
		return true
	}

	return false
}

// SetWikidataId gets a reference to the given string and assigns it to the WikidataId field.
func (o *EntityDetail) SetWikidataId(v string) {
	o.WikidataId = &v
}

// GetWikipediaUrl returns the WikipediaUrl field value if set, zero value otherwise.
func (o *EntityDetail) GetWikipediaUrl() string {
	if o == nil || IsNil(o.WikipediaUrl) {
		var ret string
		return ret
	}
	return *o.WikipediaUrl
}

// GetWikipediaUrlOk returns a tuple with the WikipediaUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetWikipediaUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WikipediaUrl) {
		return nil, false
	}
	return o.WikipediaUrl, true
}

// HasWikipediaUrl returns a boolean if a field has been set.
func (o *EntityDetail) HasWikipediaUrl() bool {
	if o != nil && !IsNil(o.WikipediaUrl) {
		return true
	}

	return false
}

// SetWikipediaUrl gets a reference to the given string and assigns it to the WikipediaUrl field.
func (o *EntityDetail) SetWikipediaUrl(v string) {
	o.WikipediaUrl = &v
}

// GetArticleCount returns the ArticleCount field value if set, zero value otherwise.
func (o *EntityDetail) GetArticleCount() int32 {
	if o == nil || IsNil(o.ArticleCount) {
		var ret int32
		return ret
	}
	return *o.ArticleCount
}

// GetArticleCountOk returns a tuple with the ArticleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetArticleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ArticleCount) {
		return nil, false
	}
	return o.ArticleCount, true
}

// HasArticleCount returns a boolean if a field has been set.
func (o *EntityDetail) HasArticleCount() bool {
	if o != nil && !IsNil(o.ArticleCount) {
		return true
	}

	return false
}

// SetArticleCount gets a reference to the given int32 and assigns it to the ArticleCount field.
func (o *EntityDetail) SetArticleCount(v int32) {
	o.ArticleCount = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *EntityDetail) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *EntityDetail) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *EntityDetail) SetAliases(v []string) {
	o.Aliases = v
}

// GetEnriched returns the Enriched field value if set, zero value otherwise.
func (o *EntityDetail) GetEnriched() bool {
	if o == nil || IsNil(o.Enriched) {
		var ret bool
		return ret
	}
	return *o.Enriched
}

// GetEnrichedOk returns a tuple with the Enriched field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityDetail) GetEnrichedOk() (*bool, bool) {
	if o == nil || IsNil(o.Enriched) {
		return nil, false
	}
	return o.Enriched, true
}

// HasEnriched returns a boolean if a field has been set.
func (o *EntityDetail) HasEnriched() bool {
	if o != nil && !IsNil(o.Enriched) {
		return true
	}

	return false
}

// SetEnriched gets a reference to the given bool and assigns it to the Enriched field.
func (o *EntityDetail) SetEnriched(v bool) {
	o.Enriched = &v
}

func (o EntityDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Subcategory) {
		toSerialize["subcategory"] = o.Subcategory
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.WikidataId) {
		toSerialize["wikidata_id"] = o.WikidataId
	}
	if !IsNil(o.WikipediaUrl) {
		toSerialize["wikipedia_url"] = o.WikipediaUrl
	}
	if !IsNil(o.ArticleCount) {
		toSerialize["article_count"] = o.ArticleCount
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.Enriched) {
		toSerialize["enriched"] = o.Enriched
	}
	return toSerialize, nil
}

type NullableEntityDetail struct {
	value *EntityDetail
	isSet bool
}

func (v NullableEntityDetail) Get() *EntityDetail {
	return v.value
}

func (v *NullableEntityDetail) Set(val *EntityDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityDetail(val *EntityDetail) *NullableEntityDetail {
	return &NullableEntityDetail{value: val, isSet: true}
}

func (v NullableEntityDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


