/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the VectorSearch200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorSearch200Response{}

// VectorSearch200Response struct for VectorSearch200Response
type VectorSearch200Response struct {
	Ok *bool `json:"ok,omitempty"`
	Articles []VectorSearch200ResponseArticlesInner `json:"articles,omitempty"`
	Stories []VectorSearch200ResponseStoriesInner `json:"stories,omitempty"`
}

// NewVectorSearch200Response instantiates a new VectorSearch200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorSearch200Response() *VectorSearch200Response {
	this := VectorSearch200Response{}
	return &this
}

// NewVectorSearch200ResponseWithDefaults instantiates a new VectorSearch200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorSearch200ResponseWithDefaults() *VectorSearch200Response {
	this := VectorSearch200Response{}
	return &this
}

// GetOk returns the Ok field value if set, zero value otherwise.
func (o *VectorSearch200Response) GetOk() bool {
	if o == nil || IsNil(o.Ok) {
		var ret bool
		return ret
	}
	return *o.Ok
}

// GetOkOk returns a tuple with the Ok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200Response) GetOkOk() (*bool, bool) {
	if o == nil || IsNil(o.Ok) {
		return nil, false
	}
	return o.Ok, true
}

// HasOk returns a boolean if a field has been set.
func (o *VectorSearch200Response) HasOk() bool {
	if o != nil && !IsNil(o.Ok) {
		return true
	}

	return false
}

// SetOk gets a reference to the given bool and assigns it to the Ok field.
func (o *VectorSearch200Response) SetOk(v bool) {
	o.Ok = &v
}

// GetArticles returns the Articles field value if set, zero value otherwise.
func (o *VectorSearch200Response) GetArticles() []VectorSearch200ResponseArticlesInner {
	if o == nil || IsNil(o.Articles) {
		var ret []VectorSearch200ResponseArticlesInner
		return ret
	}
	return o.Articles
}

// GetArticlesOk returns a tuple with the Articles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200Response) GetArticlesOk() ([]VectorSearch200ResponseArticlesInner, bool) {
	if o == nil || IsNil(o.Articles) {
		return nil, false
	}
	return o.Articles, true
}

// HasArticles returns a boolean if a field has been set.
func (o *VectorSearch200Response) HasArticles() bool {
	if o != nil && !IsNil(o.Articles) {
		return true
	}

	return false
}

// SetArticles gets a reference to the given []VectorSearch200ResponseArticlesInner and assigns it to the Articles field.
func (o *VectorSearch200Response) SetArticles(v []VectorSearch200ResponseArticlesInner) {
	o.Articles = v
}

// GetStories returns the Stories field value if set, zero value otherwise.
func (o *VectorSearch200Response) GetStories() []VectorSearch200ResponseStoriesInner {
	if o == nil || IsNil(o.Stories) {
		var ret []VectorSearch200ResponseStoriesInner
		return ret
	}
	return o.Stories
}

// GetStoriesOk returns a tuple with the Stories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200Response) GetStoriesOk() ([]VectorSearch200ResponseStoriesInner, bool) {
	if o == nil || IsNil(o.Stories) {
		return nil, false
	}
	return o.Stories, true
}

// HasStories returns a boolean if a field has been set.
func (o *VectorSearch200Response) HasStories() bool {
	if o != nil && !IsNil(o.Stories) {
		return true
	}

	return false
}

// SetStories gets a reference to the given []VectorSearch200ResponseStoriesInner and assigns it to the Stories field.
func (o *VectorSearch200Response) SetStories(v []VectorSearch200ResponseStoriesInner) {
	o.Stories = v
}

func (o VectorSearch200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorSearch200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ok) {
		toSerialize["ok"] = o.Ok
	}
	if !IsNil(o.Articles) {
		toSerialize["articles"] = o.Articles
	}
	if !IsNil(o.Stories) {
		toSerialize["stories"] = o.Stories
	}
	return toSerialize, nil
}

type NullableVectorSearch200Response struct {
	value *VectorSearch200Response
	isSet bool
}

func (v NullableVectorSearch200Response) Get() *VectorSearch200Response {
	return v.value
}

func (v *NullableVectorSearch200Response) Set(val *VectorSearch200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorSearch200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorSearch200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorSearch200Response(val *VectorSearch200Response) *NullableVectorSearch200Response {
	return &NullableVectorSearch200Response{value: val, isSet: true}
}

func (v NullableVectorSearch200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorSearch200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


