/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the ListStories200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListStories200Response{}

// ListStories200Response struct for ListStories200Response
type ListStories200Response struct {
	Stories []Story `json:"stories,omitempty"`
}

// NewListStories200Response instantiates a new ListStories200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListStories200Response() *ListStories200Response {
	this := ListStories200Response{}
	return &this
}

// NewListStories200ResponseWithDefaults instantiates a new ListStories200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListStories200ResponseWithDefaults() *ListStories200Response {
	this := ListStories200Response{}
	return &this
}

// GetStories returns the Stories field value if set, zero value otherwise.
func (o *ListStories200Response) GetStories() []Story {
	if o == nil || IsNil(o.Stories) {
		var ret []Story
		return ret
	}
	return o.Stories
}

// GetStoriesOk returns a tuple with the Stories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListStories200Response) GetStoriesOk() ([]Story, bool) {
	if o == nil || IsNil(o.Stories) {
		return nil, false
	}
	return o.Stories, true
}

// HasStories returns a boolean if a field has been set.
func (o *ListStories200Response) HasStories() bool {
	if o != nil && !IsNil(o.Stories) {
		return true
	}

	return false
}

// SetStories gets a reference to the given []Story and assigns it to the Stories field.
func (o *ListStories200Response) SetStories(v []Story) {
	o.Stories = v
}

func (o ListStories200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListStories200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stories) {
		toSerialize["stories"] = o.Stories
	}
	return toSerialize, nil
}

type NullableListStories200Response struct {
	value *ListStories200Response
	isSet bool
}

func (v NullableListStories200Response) Get() *ListStories200Response {
	return v.value
}

func (v *NullableListStories200Response) Set(val *ListStories200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListStories200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListStories200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListStories200Response(val *ListStories200Response) *NullableListStories200Response {
	return &NullableListStories200Response{value: val, isSet: true}
}

func (v NullableListStories200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListStories200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


