/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the Story type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Story{}

// Story struct for Story
type Story struct {
	Id *int32 `json:"id,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Summary *string `json:"summary,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	ArticleCount *int32 `json:"article_count,omitempty"`
	Sources []string `json:"sources,omitempty"`
	TopEntities []string `json:"top_entities,omitempty"`
	Category *string `json:"category,omitempty"`
	// Unix timestamp in milliseconds
	FirstSeen *int64 `json:"first_seen,omitempty"`
	// Unix timestamp in milliseconds
	LastUpdated *int64 `json:"last_updated,omitempty"`
	Label *string `json:"label,omitempty"`
}

// NewStory instantiates a new Story object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStory() *Story {
	this := Story{}
	return &this
}

// NewStoryWithDefaults instantiates a new Story object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoryWithDefaults() *Story {
	this := Story{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Story) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Story) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Story) SetId(v int32) {
	o.Id = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *Story) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *Story) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *Story) SetSlug(v string) {
	o.Slug = &v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *Story) GetHeadline() string {
	if o == nil || IsNil(o.Headline) {
		var ret string
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetHeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.Headline) {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *Story) HasHeadline() bool {
	if o != nil && !IsNil(o.Headline) {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given string and assigns it to the Headline field.
func (o *Story) SetHeadline(v string) {
	o.Headline = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *Story) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *Story) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *Story) SetSummary(v string) {
	o.Summary = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *Story) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *Story) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *Story) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetArticleCount returns the ArticleCount field value if set, zero value otherwise.
func (o *Story) GetArticleCount() int32 {
	if o == nil || IsNil(o.ArticleCount) {
		var ret int32
		return ret
	}
	return *o.ArticleCount
}

// GetArticleCountOk returns a tuple with the ArticleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetArticleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ArticleCount) {
		return nil, false
	}
	return o.ArticleCount, true
}

// HasArticleCount returns a boolean if a field has been set.
func (o *Story) HasArticleCount() bool {
	if o != nil && !IsNil(o.ArticleCount) {
		return true
	}

	return false
}

// SetArticleCount gets a reference to the given int32 and assigns it to the ArticleCount field.
func (o *Story) SetArticleCount(v int32) {
	o.ArticleCount = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *Story) GetSources() []string {
	if o == nil || IsNil(o.Sources) {
		var ret []string
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *Story) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []string and assigns it to the Sources field.
func (o *Story) SetSources(v []string) {
	o.Sources = v
}

// GetTopEntities returns the TopEntities field value if set, zero value otherwise.
func (o *Story) GetTopEntities() []string {
	if o == nil || IsNil(o.TopEntities) {
		var ret []string
		return ret
	}
	return o.TopEntities
}

// GetTopEntitiesOk returns a tuple with the TopEntities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetTopEntitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.TopEntities) {
		return nil, false
	}
	return o.TopEntities, true
}

// HasTopEntities returns a boolean if a field has been set.
func (o *Story) HasTopEntities() bool {
	if o != nil && !IsNil(o.TopEntities) {
		return true
	}

	return false
}

// SetTopEntities gets a reference to the given []string and assigns it to the TopEntities field.
func (o *Story) SetTopEntities(v []string) {
	o.TopEntities = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *Story) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *Story) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *Story) SetCategory(v string) {
	o.Category = &v
}

// GetFirstSeen returns the FirstSeen field value if set, zero value otherwise.
func (o *Story) GetFirstSeen() int64 {
	if o == nil || IsNil(o.FirstSeen) {
		var ret int64
		return ret
	}
	return *o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetFirstSeenOk() (*int64, bool) {
	if o == nil || IsNil(o.FirstSeen) {
		return nil, false
	}
	return o.FirstSeen, true
}

// HasFirstSeen returns a boolean if a field has been set.
func (o *Story) HasFirstSeen() bool {
	if o != nil && !IsNil(o.FirstSeen) {
		return true
	}

	return false
}

// SetFirstSeen gets a reference to the given int64 and assigns it to the FirstSeen field.
func (o *Story) SetFirstSeen(v int64) {
	o.FirstSeen = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *Story) GetLastUpdated() int64 {
	if o == nil || IsNil(o.LastUpdated) {
		var ret int64
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetLastUpdatedOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *Story) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given int64 and assigns it to the LastUpdated field.
func (o *Story) SetLastUpdated(v int64) {
	o.LastUpdated = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *Story) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Story) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *Story) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *Story) SetLabel(v string) {
	o.Label = &v
}

func (o Story) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Story) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Headline) {
		toSerialize["headline"] = o.Headline
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.ArticleCount) {
		toSerialize["article_count"] = o.ArticleCount
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.TopEntities) {
		toSerialize["top_entities"] = o.TopEntities
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.FirstSeen) {
		toSerialize["first_seen"] = o.FirstSeen
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last_updated"] = o.LastUpdated
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableStory struct {
	value *Story
	isSet bool
}

func (v NullableStory) Get() *Story {
	return v.value
}

func (v *NullableStory) Set(val *Story) {
	v.value = val
	v.isSet = true
}

func (v NullableStory) IsSet() bool {
	return v.isSet
}

func (v *NullableStory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStory(val *Story) *NullableStory {
	return &NullableStory{value: val, isSet: true}
}

func (v NullableStory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


