/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the VectorSearch200ResponseArticlesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorSearch200ResponseArticlesInner{}

// VectorSearch200ResponseArticlesInner struct for VectorSearch200ResponseArticlesInner
type VectorSearch200ResponseArticlesInner struct {
	Similarity *float32 `json:"similarity,omitempty"`
	Distance *float32 `json:"distance,omitempty"`
	UrlHash *string `json:"url_hash,omitempty"`
	Title *string `json:"title,omitempty"`
	Url *string `json:"url,omitempty"`
	SourceName *string `json:"source_name,omitempty"`
	Category *string `json:"category,omitempty"`
	PublishedAt *int64 `json:"published_at,omitempty"`
}

// NewVectorSearch200ResponseArticlesInner instantiates a new VectorSearch200ResponseArticlesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorSearch200ResponseArticlesInner() *VectorSearch200ResponseArticlesInner {
	this := VectorSearch200ResponseArticlesInner{}
	return &this
}

// NewVectorSearch200ResponseArticlesInnerWithDefaults instantiates a new VectorSearch200ResponseArticlesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorSearch200ResponseArticlesInnerWithDefaults() *VectorSearch200ResponseArticlesInner {
	this := VectorSearch200ResponseArticlesInner{}
	return &this
}

// GetSimilarity returns the Similarity field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetSimilarity() float32 {
	if o == nil || IsNil(o.Similarity) {
		var ret float32
		return ret
	}
	return *o.Similarity
}

// GetSimilarityOk returns a tuple with the Similarity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetSimilarityOk() (*float32, bool) {
	if o == nil || IsNil(o.Similarity) {
		return nil, false
	}
	return o.Similarity, true
}

// HasSimilarity returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasSimilarity() bool {
	if o != nil && !IsNil(o.Similarity) {
		return true
	}

	return false
}

// SetSimilarity gets a reference to the given float32 and assigns it to the Similarity field.
func (o *VectorSearch200ResponseArticlesInner) SetSimilarity(v float32) {
	o.Similarity = &v
}

// GetDistance returns the Distance field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetDistance() float32 {
	if o == nil || IsNil(o.Distance) {
		var ret float32
		return ret
	}
	return *o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetDistanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Distance) {
		return nil, false
	}
	return o.Distance, true
}

// HasDistance returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasDistance() bool {
	if o != nil && !IsNil(o.Distance) {
		return true
	}

	return false
}

// SetDistance gets a reference to the given float32 and assigns it to the Distance field.
func (o *VectorSearch200ResponseArticlesInner) SetDistance(v float32) {
	o.Distance = &v
}

// GetUrlHash returns the UrlHash field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetUrlHash() string {
	if o == nil || IsNil(o.UrlHash) {
		var ret string
		return ret
	}
	return *o.UrlHash
}

// GetUrlHashOk returns a tuple with the UrlHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetUrlHashOk() (*string, bool) {
	if o == nil || IsNil(o.UrlHash) {
		return nil, false
	}
	return o.UrlHash, true
}

// HasUrlHash returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasUrlHash() bool {
	if o != nil && !IsNil(o.UrlHash) {
		return true
	}

	return false
}

// SetUrlHash gets a reference to the given string and assigns it to the UrlHash field.
func (o *VectorSearch200ResponseArticlesInner) SetUrlHash(v string) {
	o.UrlHash = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *VectorSearch200ResponseArticlesInner) SetTitle(v string) {
	o.Title = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *VectorSearch200ResponseArticlesInner) SetUrl(v string) {
	o.Url = &v
}

// GetSourceName returns the SourceName field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetSourceName() string {
	if o == nil || IsNil(o.SourceName) {
		var ret string
		return ret
	}
	return *o.SourceName
}

// GetSourceNameOk returns a tuple with the SourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetSourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceName) {
		return nil, false
	}
	return o.SourceName, true
}

// HasSourceName returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasSourceName() bool {
	if o != nil && !IsNil(o.SourceName) {
		return true
	}

	return false
}

// SetSourceName gets a reference to the given string and assigns it to the SourceName field.
func (o *VectorSearch200ResponseArticlesInner) SetSourceName(v string) {
	o.SourceName = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *VectorSearch200ResponseArticlesInner) SetCategory(v string) {
	o.Category = &v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise.
func (o *VectorSearch200ResponseArticlesInner) GetPublishedAt() int64 {
	if o == nil || IsNil(o.PublishedAt) {
		var ret int64
		return ret
	}
	return *o.PublishedAt
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseArticlesInner) GetPublishedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.PublishedAt) {
		return nil, false
	}
	return o.PublishedAt, true
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *VectorSearch200ResponseArticlesInner) HasPublishedAt() bool {
	if o != nil && !IsNil(o.PublishedAt) {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given int64 and assigns it to the PublishedAt field.
func (o *VectorSearch200ResponseArticlesInner) SetPublishedAt(v int64) {
	o.PublishedAt = &v
}

func (o VectorSearch200ResponseArticlesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorSearch200ResponseArticlesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Similarity) {
		toSerialize["similarity"] = o.Similarity
	}
	if !IsNil(o.Distance) {
		toSerialize["distance"] = o.Distance
	}
	if !IsNil(o.UrlHash) {
		toSerialize["url_hash"] = o.UrlHash
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.SourceName) {
		toSerialize["source_name"] = o.SourceName
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.PublishedAt) {
		toSerialize["published_at"] = o.PublishedAt
	}
	return toSerialize, nil
}

type NullableVectorSearch200ResponseArticlesInner struct {
	value *VectorSearch200ResponseArticlesInner
	isSet bool
}

func (v NullableVectorSearch200ResponseArticlesInner) Get() *VectorSearch200ResponseArticlesInner {
	return v.value
}

func (v *NullableVectorSearch200ResponseArticlesInner) Set(val *VectorSearch200ResponseArticlesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorSearch200ResponseArticlesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorSearch200ResponseArticlesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorSearch200ResponseArticlesInner(val *VectorSearch200ResponseArticlesInner) *NullableVectorSearch200ResponseArticlesInner {
	return &NullableVectorSearch200ResponseArticlesInner{value: val, isSet: true}
}

func (v NullableVectorSearch200ResponseArticlesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorSearch200ResponseArticlesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


