/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetUsage200ResponseSummaryTopEndpointsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsage200ResponseSummaryTopEndpointsInner{}

// GetUsage200ResponseSummaryTopEndpointsInner struct for GetUsage200ResponseSummaryTopEndpointsInner
type GetUsage200ResponseSummaryTopEndpointsInner struct {
	Endpoint *string `json:"endpoint,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewGetUsage200ResponseSummaryTopEndpointsInner instantiates a new GetUsage200ResponseSummaryTopEndpointsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsage200ResponseSummaryTopEndpointsInner() *GetUsage200ResponseSummaryTopEndpointsInner {
	this := GetUsage200ResponseSummaryTopEndpointsInner{}
	return &this
}

// NewGetUsage200ResponseSummaryTopEndpointsInnerWithDefaults instantiates a new GetUsage200ResponseSummaryTopEndpointsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsage200ResponseSummaryTopEndpointsInnerWithDefaults() *GetUsage200ResponseSummaryTopEndpointsInner {
	this := GetUsage200ResponseSummaryTopEndpointsInner{}
	return &this
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetUsage200ResponseSummaryTopEndpointsInner) SetCount(v int32) {
	o.Count = &v
}

func (o GetUsage200ResponseSummaryTopEndpointsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsage200ResponseSummaryTopEndpointsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableGetUsage200ResponseSummaryTopEndpointsInner struct {
	value *GetUsage200ResponseSummaryTopEndpointsInner
	isSet bool
}

func (v NullableGetUsage200ResponseSummaryTopEndpointsInner) Get() *GetUsage200ResponseSummaryTopEndpointsInner {
	return v.value
}

func (v *NullableGetUsage200ResponseSummaryTopEndpointsInner) Set(val *GetUsage200ResponseSummaryTopEndpointsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsage200ResponseSummaryTopEndpointsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsage200ResponseSummaryTopEndpointsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsage200ResponseSummaryTopEndpointsInner(val *GetUsage200ResponseSummaryTopEndpointsInner) *NullableGetUsage200ResponseSummaryTopEndpointsInner {
	return &NullableGetUsage200ResponseSummaryTopEndpointsInner{value: val, isSet: true}
}

func (v NullableGetUsage200ResponseSummaryTopEndpointsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsage200ResponseSummaryTopEndpointsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


