/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the SearchFull200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchFull200Response{}

// SearchFull200Response struct for SearchFull200Response
type SearchFull200Response struct {
	Results []SearchResult `json:"results,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewSearchFull200Response instantiates a new SearchFull200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchFull200Response() *SearchFull200Response {
	this := SearchFull200Response{}
	return &this
}

// NewSearchFull200ResponseWithDefaults instantiates a new SearchFull200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchFull200ResponseWithDefaults() *SearchFull200Response {
	this := SearchFull200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *SearchFull200Response) GetResults() []SearchResult {
	if o == nil || IsNil(o.Results) {
		var ret []SearchResult
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFull200Response) GetResultsOk() ([]SearchResult, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *SearchFull200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []SearchResult and assigns it to the Results field.
func (o *SearchFull200Response) SetResults(v []SearchResult) {
	o.Results = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SearchFull200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchFull200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SearchFull200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *SearchFull200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o SearchFull200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchFull200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableSearchFull200Response struct {
	value *SearchFull200Response
	isSet bool
}

func (v NullableSearchFull200Response) Get() *SearchFull200Response {
	return v.value
}

func (v *NullableSearchFull200Response) Set(val *SearchFull200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchFull200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchFull200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchFull200Response(val *SearchFull200Response) *NullableSearchFull200Response {
	return &NullableSearchFull200Response{value: val, isSet: true}
}

func (v NullableSearchFull200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchFull200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


