/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the Stats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Stats{}

// Stats struct for Stats
type Stats struct {
	TotalArticles *int32 `json:"total_articles,omitempty"`
	TotalStories *int32 `json:"total_stories,omitempty"`
	TotalEntities *int32 `json:"total_entities,omitempty"`
	TotalSources *int32 `json:"total_sources,omitempty"`
}

// NewStats instantiates a new Stats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStats() *Stats {
	this := Stats{}
	return &this
}

// NewStatsWithDefaults instantiates a new Stats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsWithDefaults() *Stats {
	this := Stats{}
	return &this
}

// GetTotalArticles returns the TotalArticles field value if set, zero value otherwise.
func (o *Stats) GetTotalArticles() int32 {
	if o == nil || IsNil(o.TotalArticles) {
		var ret int32
		return ret
	}
	return *o.TotalArticles
}

// GetTotalArticlesOk returns a tuple with the TotalArticles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Stats) GetTotalArticlesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalArticles) {
		return nil, false
	}
	return o.TotalArticles, true
}

// HasTotalArticles returns a boolean if a field has been set.
func (o *Stats) HasTotalArticles() bool {
	if o != nil && !IsNil(o.TotalArticles) {
		return true
	}

	return false
}

// SetTotalArticles gets a reference to the given int32 and assigns it to the TotalArticles field.
func (o *Stats) SetTotalArticles(v int32) {
	o.TotalArticles = &v
}

// GetTotalStories returns the TotalStories field value if set, zero value otherwise.
func (o *Stats) GetTotalStories() int32 {
	if o == nil || IsNil(o.TotalStories) {
		var ret int32
		return ret
	}
	return *o.TotalStories
}

// GetTotalStoriesOk returns a tuple with the TotalStories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Stats) GetTotalStoriesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalStories) {
		return nil, false
	}
	return o.TotalStories, true
}

// HasTotalStories returns a boolean if a field has been set.
func (o *Stats) HasTotalStories() bool {
	if o != nil && !IsNil(o.TotalStories) {
		return true
	}

	return false
}

// SetTotalStories gets a reference to the given int32 and assigns it to the TotalStories field.
func (o *Stats) SetTotalStories(v int32) {
	o.TotalStories = &v
}

// GetTotalEntities returns the TotalEntities field value if set, zero value otherwise.
func (o *Stats) GetTotalEntities() int32 {
	if o == nil || IsNil(o.TotalEntities) {
		var ret int32
		return ret
	}
	return *o.TotalEntities
}

// GetTotalEntitiesOk returns a tuple with the TotalEntities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Stats) GetTotalEntitiesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalEntities) {
		return nil, false
	}
	return o.TotalEntities, true
}

// HasTotalEntities returns a boolean if a field has been set.
func (o *Stats) HasTotalEntities() bool {
	if o != nil && !IsNil(o.TotalEntities) {
		return true
	}

	return false
}

// SetTotalEntities gets a reference to the given int32 and assigns it to the TotalEntities field.
func (o *Stats) SetTotalEntities(v int32) {
	o.TotalEntities = &v
}

// GetTotalSources returns the TotalSources field value if set, zero value otherwise.
func (o *Stats) GetTotalSources() int32 {
	if o == nil || IsNil(o.TotalSources) {
		var ret int32
		return ret
	}
	return *o.TotalSources
}

// GetTotalSourcesOk returns a tuple with the TotalSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Stats) GetTotalSourcesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalSources) {
		return nil, false
	}
	return o.TotalSources, true
}

// HasTotalSources returns a boolean if a field has been set.
func (o *Stats) HasTotalSources() bool {
	if o != nil && !IsNil(o.TotalSources) {
		return true
	}

	return false
}

// SetTotalSources gets a reference to the given int32 and assigns it to the TotalSources field.
func (o *Stats) SetTotalSources(v int32) {
	o.TotalSources = &v
}

func (o Stats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Stats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalArticles) {
		toSerialize["total_articles"] = o.TotalArticles
	}
	if !IsNil(o.TotalStories) {
		toSerialize["total_stories"] = o.TotalStories
	}
	if !IsNil(o.TotalEntities) {
		toSerialize["total_entities"] = o.TotalEntities
	}
	if !IsNil(o.TotalSources) {
		toSerialize["total_sources"] = o.TotalSources
	}
	return toSerialize, nil
}

type NullableStats struct {
	value *Stats
	isSet bool
}

func (v NullableStats) Get() *Stats {
	return v.value
}

func (v *NullableStats) Set(val *Stats) {
	v.value = val
	v.isSet = true
}

func (v NullableStats) IsSet() bool {
	return v.isSet
}

func (v *NullableStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStats(val *Stats) *NullableStats {
	return &NullableStats{value: val, isSet: true}
}

func (v NullableStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


