/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the Item type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Item{}

// Item struct for Item
type Item struct {
	Id *int32 `json:"id,omitempty"`
	UrlHash *string `json:"url_hash,omitempty"`
	Title *string `json:"title,omitempty"`
	Url *string `json:"url,omitempty"`
	SourceId *int32 `json:"source_id,omitempty"`
	SourceName *string `json:"source_name,omitempty"`
	Category *string `json:"category,omitempty"`
	// Unix timestamp in milliseconds
	PublishedAt *int64 `json:"published_at,omitempty"`
	// Unix timestamp in milliseconds
	DiscoveredAt *int64 `json:"discovered_at,omitempty"`
	Excerpt *string `json:"excerpt,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	ContentStatus *string `json:"content_status,omitempty"`
	HeadlineSummary *string `json:"headline_summary,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

// NewItem instantiates a new Item object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItem() *Item {
	this := Item{}
	return &this
}

// NewItemWithDefaults instantiates a new Item object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemWithDefaults() *Item {
	this := Item{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Item) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Item) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Item) SetId(v int32) {
	o.Id = &v
}

// GetUrlHash returns the UrlHash field value if set, zero value otherwise.
func (o *Item) GetUrlHash() string {
	if o == nil || IsNil(o.UrlHash) {
		var ret string
		return ret
	}
	return *o.UrlHash
}

// GetUrlHashOk returns a tuple with the UrlHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetUrlHashOk() (*string, bool) {
	if o == nil || IsNil(o.UrlHash) {
		return nil, false
	}
	return o.UrlHash, true
}

// HasUrlHash returns a boolean if a field has been set.
func (o *Item) HasUrlHash() bool {
	if o != nil && !IsNil(o.UrlHash) {
		return true
	}

	return false
}

// SetUrlHash gets a reference to the given string and assigns it to the UrlHash field.
func (o *Item) SetUrlHash(v string) {
	o.UrlHash = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Item) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Item) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Item) SetTitle(v string) {
	o.Title = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Item) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Item) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Item) SetUrl(v string) {
	o.Url = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *Item) GetSourceId() int32 {
	if o == nil || IsNil(o.SourceId) {
		var ret int32
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetSourceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *Item) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given int32 and assigns it to the SourceId field.
func (o *Item) SetSourceId(v int32) {
	o.SourceId = &v
}

// GetSourceName returns the SourceName field value if set, zero value otherwise.
func (o *Item) GetSourceName() string {
	if o == nil || IsNil(o.SourceName) {
		var ret string
		return ret
	}
	return *o.SourceName
}

// GetSourceNameOk returns a tuple with the SourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetSourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceName) {
		return nil, false
	}
	return o.SourceName, true
}

// HasSourceName returns a boolean if a field has been set.
func (o *Item) HasSourceName() bool {
	if o != nil && !IsNil(o.SourceName) {
		return true
	}

	return false
}

// SetSourceName gets a reference to the given string and assigns it to the SourceName field.
func (o *Item) SetSourceName(v string) {
	o.SourceName = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *Item) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *Item) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *Item) SetCategory(v string) {
	o.Category = &v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise.
func (o *Item) GetPublishedAt() int64 {
	if o == nil || IsNil(o.PublishedAt) {
		var ret int64
		return ret
	}
	return *o.PublishedAt
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetPublishedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.PublishedAt) {
		return nil, false
	}
	return o.PublishedAt, true
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *Item) HasPublishedAt() bool {
	if o != nil && !IsNil(o.PublishedAt) {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given int64 and assigns it to the PublishedAt field.
func (o *Item) SetPublishedAt(v int64) {
	o.PublishedAt = &v
}

// GetDiscoveredAt returns the DiscoveredAt field value if set, zero value otherwise.
func (o *Item) GetDiscoveredAt() int64 {
	if o == nil || IsNil(o.DiscoveredAt) {
		var ret int64
		return ret
	}
	return *o.DiscoveredAt
}

// GetDiscoveredAtOk returns a tuple with the DiscoveredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetDiscoveredAtOk() (*int64, bool) {
	if o == nil || IsNil(o.DiscoveredAt) {
		return nil, false
	}
	return o.DiscoveredAt, true
}

// HasDiscoveredAt returns a boolean if a field has been set.
func (o *Item) HasDiscoveredAt() bool {
	if o != nil && !IsNil(o.DiscoveredAt) {
		return true
	}

	return false
}

// SetDiscoveredAt gets a reference to the given int64 and assigns it to the DiscoveredAt field.
func (o *Item) SetDiscoveredAt(v int64) {
	o.DiscoveredAt = &v
}

// GetExcerpt returns the Excerpt field value if set, zero value otherwise.
func (o *Item) GetExcerpt() string {
	if o == nil || IsNil(o.Excerpt) {
		var ret string
		return ret
	}
	return *o.Excerpt
}

// GetExcerptOk returns a tuple with the Excerpt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetExcerptOk() (*string, bool) {
	if o == nil || IsNil(o.Excerpt) {
		return nil, false
	}
	return o.Excerpt, true
}

// HasExcerpt returns a boolean if a field has been set.
func (o *Item) HasExcerpt() bool {
	if o != nil && !IsNil(o.Excerpt) {
		return true
	}

	return false
}

// SetExcerpt gets a reference to the given string and assigns it to the Excerpt field.
func (o *Item) SetExcerpt(v string) {
	o.Excerpt = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *Item) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *Item) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *Item) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetContentStatus returns the ContentStatus field value if set, zero value otherwise.
func (o *Item) GetContentStatus() string {
	if o == nil || IsNil(o.ContentStatus) {
		var ret string
		return ret
	}
	return *o.ContentStatus
}

// GetContentStatusOk returns a tuple with the ContentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetContentStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ContentStatus) {
		return nil, false
	}
	return o.ContentStatus, true
}

// HasContentStatus returns a boolean if a field has been set.
func (o *Item) HasContentStatus() bool {
	if o != nil && !IsNil(o.ContentStatus) {
		return true
	}

	return false
}

// SetContentStatus gets a reference to the given string and assigns it to the ContentStatus field.
func (o *Item) SetContentStatus(v string) {
	o.ContentStatus = &v
}

// GetHeadlineSummary returns the HeadlineSummary field value if set, zero value otherwise.
func (o *Item) GetHeadlineSummary() string {
	if o == nil || IsNil(o.HeadlineSummary) {
		var ret string
		return ret
	}
	return *o.HeadlineSummary
}

// GetHeadlineSummaryOk returns a tuple with the HeadlineSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetHeadlineSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.HeadlineSummary) {
		return nil, false
	}
	return o.HeadlineSummary, true
}

// HasHeadlineSummary returns a boolean if a field has been set.
func (o *Item) HasHeadlineSummary() bool {
	if o != nil && !IsNil(o.HeadlineSummary) {
		return true
	}

	return false
}

// SetHeadlineSummary gets a reference to the given string and assigns it to the HeadlineSummary field.
func (o *Item) SetHeadlineSummary(v string) {
	o.HeadlineSummary = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *Item) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *Item) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *Item) SetSlug(v string) {
	o.Slug = &v
}

func (o Item) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Item) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.UrlHash) {
		toSerialize["url_hash"] = o.UrlHash
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	if !IsNil(o.SourceName) {
		toSerialize["source_name"] = o.SourceName
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.PublishedAt) {
		toSerialize["published_at"] = o.PublishedAt
	}
	if !IsNil(o.DiscoveredAt) {
		toSerialize["discovered_at"] = o.DiscoveredAt
	}
	if !IsNil(o.Excerpt) {
		toSerialize["excerpt"] = o.Excerpt
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.ContentStatus) {
		toSerialize["content_status"] = o.ContentStatus
	}
	if !IsNil(o.HeadlineSummary) {
		toSerialize["headline_summary"] = o.HeadlineSummary
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	return toSerialize, nil
}

type NullableItem struct {
	value *Item
	isSet bool
}

func (v NullableItem) Get() *Item {
	return v.value
}

func (v *NullableItem) Set(val *Item) {
	v.value = val
	v.isSet = true
}

func (v NullableItem) IsSet() bool {
	return v.isSet
}

func (v *NullableItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItem(val *Item) *NullableItem {
	return &NullableItem{value: val, isSet: true}
}

func (v NullableItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


