/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the VectorSearch200ResponseStoriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorSearch200ResponseStoriesInner{}

// VectorSearch200ResponseStoriesInner struct for VectorSearch200ResponseStoriesInner
type VectorSearch200ResponseStoriesInner struct {
	Similarity *float32 `json:"similarity,omitempty"`
	Distance *float32 `json:"distance,omitempty"`
	ClusterId *int32 `json:"cluster_id,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Summary *string `json:"summary,omitempty"`
	ArticleCount *int32 `json:"article_count,omitempty"`
	FirstSeen *int64 `json:"first_seen,omitempty"`
	LastUpdated *int64 `json:"last_updated,omitempty"`
}

// NewVectorSearch200ResponseStoriesInner instantiates a new VectorSearch200ResponseStoriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorSearch200ResponseStoriesInner() *VectorSearch200ResponseStoriesInner {
	this := VectorSearch200ResponseStoriesInner{}
	return &this
}

// NewVectorSearch200ResponseStoriesInnerWithDefaults instantiates a new VectorSearch200ResponseStoriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorSearch200ResponseStoriesInnerWithDefaults() *VectorSearch200ResponseStoriesInner {
	this := VectorSearch200ResponseStoriesInner{}
	return &this
}

// GetSimilarity returns the Similarity field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetSimilarity() float32 {
	if o == nil || IsNil(o.Similarity) {
		var ret float32
		return ret
	}
	return *o.Similarity
}

// GetSimilarityOk returns a tuple with the Similarity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetSimilarityOk() (*float32, bool) {
	if o == nil || IsNil(o.Similarity) {
		return nil, false
	}
	return o.Similarity, true
}

// HasSimilarity returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasSimilarity() bool {
	if o != nil && !IsNil(o.Similarity) {
		return true
	}

	return false
}

// SetSimilarity gets a reference to the given float32 and assigns it to the Similarity field.
func (o *VectorSearch200ResponseStoriesInner) SetSimilarity(v float32) {
	o.Similarity = &v
}

// GetDistance returns the Distance field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetDistance() float32 {
	if o == nil || IsNil(o.Distance) {
		var ret float32
		return ret
	}
	return *o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetDistanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Distance) {
		return nil, false
	}
	return o.Distance, true
}

// HasDistance returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasDistance() bool {
	if o != nil && !IsNil(o.Distance) {
		return true
	}

	return false
}

// SetDistance gets a reference to the given float32 and assigns it to the Distance field.
func (o *VectorSearch200ResponseStoriesInner) SetDistance(v float32) {
	o.Distance = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetClusterId() int32 {
	if o == nil || IsNil(o.ClusterId) {
		var ret int32
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetClusterIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given int32 and assigns it to the ClusterId field.
func (o *VectorSearch200ResponseStoriesInner) SetClusterId(v int32) {
	o.ClusterId = &v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetHeadline() string {
	if o == nil || IsNil(o.Headline) {
		var ret string
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetHeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.Headline) {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasHeadline() bool {
	if o != nil && !IsNil(o.Headline) {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given string and assigns it to the Headline field.
func (o *VectorSearch200ResponseStoriesInner) SetHeadline(v string) {
	o.Headline = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *VectorSearch200ResponseStoriesInner) SetSummary(v string) {
	o.Summary = &v
}

// GetArticleCount returns the ArticleCount field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetArticleCount() int32 {
	if o == nil || IsNil(o.ArticleCount) {
		var ret int32
		return ret
	}
	return *o.ArticleCount
}

// GetArticleCountOk returns a tuple with the ArticleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetArticleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ArticleCount) {
		return nil, false
	}
	return o.ArticleCount, true
}

// HasArticleCount returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasArticleCount() bool {
	if o != nil && !IsNil(o.ArticleCount) {
		return true
	}

	return false
}

// SetArticleCount gets a reference to the given int32 and assigns it to the ArticleCount field.
func (o *VectorSearch200ResponseStoriesInner) SetArticleCount(v int32) {
	o.ArticleCount = &v
}

// GetFirstSeen returns the FirstSeen field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetFirstSeen() int64 {
	if o == nil || IsNil(o.FirstSeen) {
		var ret int64
		return ret
	}
	return *o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetFirstSeenOk() (*int64, bool) {
	if o == nil || IsNil(o.FirstSeen) {
		return nil, false
	}
	return o.FirstSeen, true
}

// HasFirstSeen returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasFirstSeen() bool {
	if o != nil && !IsNil(o.FirstSeen) {
		return true
	}

	return false
}

// SetFirstSeen gets a reference to the given int64 and assigns it to the FirstSeen field.
func (o *VectorSearch200ResponseStoriesInner) SetFirstSeen(v int64) {
	o.FirstSeen = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *VectorSearch200ResponseStoriesInner) GetLastUpdated() int64 {
	if o == nil || IsNil(o.LastUpdated) {
		var ret int64
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearch200ResponseStoriesInner) GetLastUpdatedOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *VectorSearch200ResponseStoriesInner) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given int64 and assigns it to the LastUpdated field.
func (o *VectorSearch200ResponseStoriesInner) SetLastUpdated(v int64) {
	o.LastUpdated = &v
}

func (o VectorSearch200ResponseStoriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorSearch200ResponseStoriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Similarity) {
		toSerialize["similarity"] = o.Similarity
	}
	if !IsNil(o.Distance) {
		toSerialize["distance"] = o.Distance
	}
	if !IsNil(o.ClusterId) {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if !IsNil(o.Headline) {
		toSerialize["headline"] = o.Headline
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.ArticleCount) {
		toSerialize["article_count"] = o.ArticleCount
	}
	if !IsNil(o.FirstSeen) {
		toSerialize["first_seen"] = o.FirstSeen
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last_updated"] = o.LastUpdated
	}
	return toSerialize, nil
}

type NullableVectorSearch200ResponseStoriesInner struct {
	value *VectorSearch200ResponseStoriesInner
	isSet bool
}

func (v NullableVectorSearch200ResponseStoriesInner) Get() *VectorSearch200ResponseStoriesInner {
	return v.value
}

func (v *NullableVectorSearch200ResponseStoriesInner) Set(val *VectorSearch200ResponseStoriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorSearch200ResponseStoriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorSearch200ResponseStoriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorSearch200ResponseStoriesInner(val *VectorSearch200ResponseStoriesInner) *NullableVectorSearch200ResponseStoriesInner {
	return &NullableVectorSearch200ResponseStoriesInner{value: val, isSet: true}
}

func (v NullableVectorSearch200ResponseStoriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorSearch200ResponseStoriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


