/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetUsage200ResponseDailyInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsage200ResponseDailyInner{}

// GetUsage200ResponseDailyInner struct for GetUsage200ResponseDailyInner
type GetUsage200ResponseDailyInner struct {
	DayMs *int64 `json:"day_ms,omitempty"`
	Requests *int32 `json:"requests,omitempty"`
	Errors *int32 `json:"errors,omitempty"`
	Bytes *int32 `json:"bytes,omitempty"`
}

// NewGetUsage200ResponseDailyInner instantiates a new GetUsage200ResponseDailyInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsage200ResponseDailyInner() *GetUsage200ResponseDailyInner {
	this := GetUsage200ResponseDailyInner{}
	return &this
}

// NewGetUsage200ResponseDailyInnerWithDefaults instantiates a new GetUsage200ResponseDailyInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsage200ResponseDailyInnerWithDefaults() *GetUsage200ResponseDailyInner {
	this := GetUsage200ResponseDailyInner{}
	return &this
}

// GetDayMs returns the DayMs field value if set, zero value otherwise.
func (o *GetUsage200ResponseDailyInner) GetDayMs() int64 {
	if o == nil || IsNil(o.DayMs) {
		var ret int64
		return ret
	}
	return *o.DayMs
}

// GetDayMsOk returns a tuple with the DayMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseDailyInner) GetDayMsOk() (*int64, bool) {
	if o == nil || IsNil(o.DayMs) {
		return nil, false
	}
	return o.DayMs, true
}

// HasDayMs returns a boolean if a field has been set.
func (o *GetUsage200ResponseDailyInner) HasDayMs() bool {
	if o != nil && !IsNil(o.DayMs) {
		return true
	}

	return false
}

// SetDayMs gets a reference to the given int64 and assigns it to the DayMs field.
func (o *GetUsage200ResponseDailyInner) SetDayMs(v int64) {
	o.DayMs = &v
}

// GetRequests returns the Requests field value if set, zero value otherwise.
func (o *GetUsage200ResponseDailyInner) GetRequests() int32 {
	if o == nil || IsNil(o.Requests) {
		var ret int32
		return ret
	}
	return *o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseDailyInner) GetRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.Requests) {
		return nil, false
	}
	return o.Requests, true
}

// HasRequests returns a boolean if a field has been set.
func (o *GetUsage200ResponseDailyInner) HasRequests() bool {
	if o != nil && !IsNil(o.Requests) {
		return true
	}

	return false
}

// SetRequests gets a reference to the given int32 and assigns it to the Requests field.
func (o *GetUsage200ResponseDailyInner) SetRequests(v int32) {
	o.Requests = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *GetUsage200ResponseDailyInner) GetErrors() int32 {
	if o == nil || IsNil(o.Errors) {
		var ret int32
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseDailyInner) GetErrorsOk() (*int32, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *GetUsage200ResponseDailyInner) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given int32 and assigns it to the Errors field.
func (o *GetUsage200ResponseDailyInner) SetErrors(v int32) {
	o.Errors = &v
}

// GetBytes returns the Bytes field value if set, zero value otherwise.
func (o *GetUsage200ResponseDailyInner) GetBytes() int32 {
	if o == nil || IsNil(o.Bytes) {
		var ret int32
		return ret
	}
	return *o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseDailyInner) GetBytesOk() (*int32, bool) {
	if o == nil || IsNil(o.Bytes) {
		return nil, false
	}
	return o.Bytes, true
}

// HasBytes returns a boolean if a field has been set.
func (o *GetUsage200ResponseDailyInner) HasBytes() bool {
	if o != nil && !IsNil(o.Bytes) {
		return true
	}

	return false
}

// SetBytes gets a reference to the given int32 and assigns it to the Bytes field.
func (o *GetUsage200ResponseDailyInner) SetBytes(v int32) {
	o.Bytes = &v
}

func (o GetUsage200ResponseDailyInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsage200ResponseDailyInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DayMs) {
		toSerialize["day_ms"] = o.DayMs
	}
	if !IsNil(o.Requests) {
		toSerialize["requests"] = o.Requests
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Bytes) {
		toSerialize["bytes"] = o.Bytes
	}
	return toSerialize, nil
}

type NullableGetUsage200ResponseDailyInner struct {
	value *GetUsage200ResponseDailyInner
	isSet bool
}

func (v NullableGetUsage200ResponseDailyInner) Get() *GetUsage200ResponseDailyInner {
	return v.value
}

func (v *NullableGetUsage200ResponseDailyInner) Set(val *GetUsage200ResponseDailyInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsage200ResponseDailyInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsage200ResponseDailyInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsage200ResponseDailyInner(val *GetUsage200ResponseDailyInner) *NullableGetUsage200ResponseDailyInner {
	return &NullableGetUsage200ResponseDailyInner{value: val, isSet: true}
}

func (v NullableGetUsage200ResponseDailyInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsage200ResponseDailyInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


