/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetTopicClusterGraph200ResponseTopicsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTopicClusterGraph200ResponseTopicsInner{}

// GetTopicClusterGraph200ResponseTopicsInner struct for GetTopicClusterGraph200ResponseTopicsInner
type GetTopicClusterGraph200ResponseTopicsInner struct {
	Id *int32 `json:"id,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Category *string `json:"category,omitempty"`
	EventClusters []Story `json:"event_clusters,omitempty"`
}

// NewGetTopicClusterGraph200ResponseTopicsInner instantiates a new GetTopicClusterGraph200ResponseTopicsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTopicClusterGraph200ResponseTopicsInner() *GetTopicClusterGraph200ResponseTopicsInner {
	this := GetTopicClusterGraph200ResponseTopicsInner{}
	return &this
}

// NewGetTopicClusterGraph200ResponseTopicsInnerWithDefaults instantiates a new GetTopicClusterGraph200ResponseTopicsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTopicClusterGraph200ResponseTopicsInnerWithDefaults() *GetTopicClusterGraph200ResponseTopicsInner {
	this := GetTopicClusterGraph200ResponseTopicsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetTopicClusterGraph200ResponseTopicsInner) SetId(v int32) {
	o.Id = &v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetHeadline() string {
	if o == nil || IsNil(o.Headline) {
		var ret string
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetHeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.Headline) {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) HasHeadline() bool {
	if o != nil && !IsNil(o.Headline) {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given string and assigns it to the Headline field.
func (o *GetTopicClusterGraph200ResponseTopicsInner) SetHeadline(v string) {
	o.Headline = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *GetTopicClusterGraph200ResponseTopicsInner) SetCategory(v string) {
	o.Category = &v
}

// GetEventClusters returns the EventClusters field value if set, zero value otherwise.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetEventClusters() []Story {
	if o == nil || IsNil(o.EventClusters) {
		var ret []Story
		return ret
	}
	return o.EventClusters
}

// GetEventClustersOk returns a tuple with the EventClusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) GetEventClustersOk() ([]Story, bool) {
	if o == nil || IsNil(o.EventClusters) {
		return nil, false
	}
	return o.EventClusters, true
}

// HasEventClusters returns a boolean if a field has been set.
func (o *GetTopicClusterGraph200ResponseTopicsInner) HasEventClusters() bool {
	if o != nil && !IsNil(o.EventClusters) {
		return true
	}

	return false
}

// SetEventClusters gets a reference to the given []Story and assigns it to the EventClusters field.
func (o *GetTopicClusterGraph200ResponseTopicsInner) SetEventClusters(v []Story) {
	o.EventClusters = v
}

func (o GetTopicClusterGraph200ResponseTopicsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTopicClusterGraph200ResponseTopicsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Headline) {
		toSerialize["headline"] = o.Headline
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.EventClusters) {
		toSerialize["event_clusters"] = o.EventClusters
	}
	return toSerialize, nil
}

type NullableGetTopicClusterGraph200ResponseTopicsInner struct {
	value *GetTopicClusterGraph200ResponseTopicsInner
	isSet bool
}

func (v NullableGetTopicClusterGraph200ResponseTopicsInner) Get() *GetTopicClusterGraph200ResponseTopicsInner {
	return v.value
}

func (v *NullableGetTopicClusterGraph200ResponseTopicsInner) Set(val *GetTopicClusterGraph200ResponseTopicsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTopicClusterGraph200ResponseTopicsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTopicClusterGraph200ResponseTopicsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTopicClusterGraph200ResponseTopicsInner(val *GetTopicClusterGraph200ResponseTopicsInner) *NullableGetTopicClusterGraph200ResponseTopicsInner {
	return &NullableGetTopicClusterGraph200ResponseTopicsInner{value: val, isSet: true}
}

func (v NullableGetTopicClusterGraph200ResponseTopicsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTopicClusterGraph200ResponseTopicsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


