/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the StoryDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoryDetail{}

// StoryDetail struct for StoryDetail
type StoryDetail struct {
	Id *int32 `json:"id,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Summary *string `json:"summary,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	ArticleCount *int32 `json:"article_count,omitempty"`
	Sources []string `json:"sources,omitempty"`
	TopEntities []string `json:"top_entities,omitempty"`
	Category *string `json:"category,omitempty"`
	// Unix timestamp in milliseconds
	FirstSeen *int64 `json:"first_seen,omitempty"`
	// Unix timestamp in milliseconds
	LastUpdated *int64 `json:"last_updated,omitempty"`
	Label *string `json:"label,omitempty"`
	RichSummary *string `json:"rich_summary,omitempty"`
	Articles []Item `json:"articles,omitempty"`
	Developments []StoryDevelopment `json:"developments,omitempty"`
}

// NewStoryDetail instantiates a new StoryDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoryDetail() *StoryDetail {
	this := StoryDetail{}
	return &this
}

// NewStoryDetailWithDefaults instantiates a new StoryDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoryDetailWithDefaults() *StoryDetail {
	this := StoryDetail{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StoryDetail) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StoryDetail) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *StoryDetail) SetId(v int32) {
	o.Id = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *StoryDetail) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *StoryDetail) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *StoryDetail) SetSlug(v string) {
	o.Slug = &v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *StoryDetail) GetHeadline() string {
	if o == nil || IsNil(o.Headline) {
		var ret string
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetHeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.Headline) {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *StoryDetail) HasHeadline() bool {
	if o != nil && !IsNil(o.Headline) {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given string and assigns it to the Headline field.
func (o *StoryDetail) SetHeadline(v string) {
	o.Headline = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *StoryDetail) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *StoryDetail) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *StoryDetail) SetSummary(v string) {
	o.Summary = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *StoryDetail) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *StoryDetail) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *StoryDetail) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetArticleCount returns the ArticleCount field value if set, zero value otherwise.
func (o *StoryDetail) GetArticleCount() int32 {
	if o == nil || IsNil(o.ArticleCount) {
		var ret int32
		return ret
	}
	return *o.ArticleCount
}

// GetArticleCountOk returns a tuple with the ArticleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetArticleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ArticleCount) {
		return nil, false
	}
	return o.ArticleCount, true
}

// HasArticleCount returns a boolean if a field has been set.
func (o *StoryDetail) HasArticleCount() bool {
	if o != nil && !IsNil(o.ArticleCount) {
		return true
	}

	return false
}

// SetArticleCount gets a reference to the given int32 and assigns it to the ArticleCount field.
func (o *StoryDetail) SetArticleCount(v int32) {
	o.ArticleCount = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *StoryDetail) GetSources() []string {
	if o == nil || IsNil(o.Sources) {
		var ret []string
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *StoryDetail) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []string and assigns it to the Sources field.
func (o *StoryDetail) SetSources(v []string) {
	o.Sources = v
}

// GetTopEntities returns the TopEntities field value if set, zero value otherwise.
func (o *StoryDetail) GetTopEntities() []string {
	if o == nil || IsNil(o.TopEntities) {
		var ret []string
		return ret
	}
	return o.TopEntities
}

// GetTopEntitiesOk returns a tuple with the TopEntities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetTopEntitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.TopEntities) {
		return nil, false
	}
	return o.TopEntities, true
}

// HasTopEntities returns a boolean if a field has been set.
func (o *StoryDetail) HasTopEntities() bool {
	if o != nil && !IsNil(o.TopEntities) {
		return true
	}

	return false
}

// SetTopEntities gets a reference to the given []string and assigns it to the TopEntities field.
func (o *StoryDetail) SetTopEntities(v []string) {
	o.TopEntities = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *StoryDetail) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *StoryDetail) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *StoryDetail) SetCategory(v string) {
	o.Category = &v
}

// GetFirstSeen returns the FirstSeen field value if set, zero value otherwise.
func (o *StoryDetail) GetFirstSeen() int64 {
	if o == nil || IsNil(o.FirstSeen) {
		var ret int64
		return ret
	}
	return *o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetFirstSeenOk() (*int64, bool) {
	if o == nil || IsNil(o.FirstSeen) {
		return nil, false
	}
	return o.FirstSeen, true
}

// HasFirstSeen returns a boolean if a field has been set.
func (o *StoryDetail) HasFirstSeen() bool {
	if o != nil && !IsNil(o.FirstSeen) {
		return true
	}

	return false
}

// SetFirstSeen gets a reference to the given int64 and assigns it to the FirstSeen field.
func (o *StoryDetail) SetFirstSeen(v int64) {
	o.FirstSeen = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *StoryDetail) GetLastUpdated() int64 {
	if o == nil || IsNil(o.LastUpdated) {
		var ret int64
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetLastUpdatedOk() (*int64, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *StoryDetail) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given int64 and assigns it to the LastUpdated field.
func (o *StoryDetail) SetLastUpdated(v int64) {
	o.LastUpdated = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *StoryDetail) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *StoryDetail) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *StoryDetail) SetLabel(v string) {
	o.Label = &v
}

// GetRichSummary returns the RichSummary field value if set, zero value otherwise.
func (o *StoryDetail) GetRichSummary() string {
	if o == nil || IsNil(o.RichSummary) {
		var ret string
		return ret
	}
	return *o.RichSummary
}

// GetRichSummaryOk returns a tuple with the RichSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetRichSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.RichSummary) {
		return nil, false
	}
	return o.RichSummary, true
}

// HasRichSummary returns a boolean if a field has been set.
func (o *StoryDetail) HasRichSummary() bool {
	if o != nil && !IsNil(o.RichSummary) {
		return true
	}

	return false
}

// SetRichSummary gets a reference to the given string and assigns it to the RichSummary field.
func (o *StoryDetail) SetRichSummary(v string) {
	o.RichSummary = &v
}

// GetArticles returns the Articles field value if set, zero value otherwise.
func (o *StoryDetail) GetArticles() []Item {
	if o == nil || IsNil(o.Articles) {
		var ret []Item
		return ret
	}
	return o.Articles
}

// GetArticlesOk returns a tuple with the Articles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetArticlesOk() ([]Item, bool) {
	if o == nil || IsNil(o.Articles) {
		return nil, false
	}
	return o.Articles, true
}

// HasArticles returns a boolean if a field has been set.
func (o *StoryDetail) HasArticles() bool {
	if o != nil && !IsNil(o.Articles) {
		return true
	}

	return false
}

// SetArticles gets a reference to the given []Item and assigns it to the Articles field.
func (o *StoryDetail) SetArticles(v []Item) {
	o.Articles = v
}

// GetDevelopments returns the Developments field value if set, zero value otherwise.
func (o *StoryDetail) GetDevelopments() []StoryDevelopment {
	if o == nil || IsNil(o.Developments) {
		var ret []StoryDevelopment
		return ret
	}
	return o.Developments
}

// GetDevelopmentsOk returns a tuple with the Developments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDetail) GetDevelopmentsOk() ([]StoryDevelopment, bool) {
	if o == nil || IsNil(o.Developments) {
		return nil, false
	}
	return o.Developments, true
}

// HasDevelopments returns a boolean if a field has been set.
func (o *StoryDetail) HasDevelopments() bool {
	if o != nil && !IsNil(o.Developments) {
		return true
	}

	return false
}

// SetDevelopments gets a reference to the given []StoryDevelopment and assigns it to the Developments field.
func (o *StoryDetail) SetDevelopments(v []StoryDevelopment) {
	o.Developments = v
}

func (o StoryDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoryDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Headline) {
		toSerialize["headline"] = o.Headline
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.ArticleCount) {
		toSerialize["article_count"] = o.ArticleCount
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.TopEntities) {
		toSerialize["top_entities"] = o.TopEntities
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.FirstSeen) {
		toSerialize["first_seen"] = o.FirstSeen
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last_updated"] = o.LastUpdated
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.RichSummary) {
		toSerialize["rich_summary"] = o.RichSummary
	}
	if !IsNil(o.Articles) {
		toSerialize["articles"] = o.Articles
	}
	if !IsNil(o.Developments) {
		toSerialize["developments"] = o.Developments
	}
	return toSerialize, nil
}

type NullableStoryDetail struct {
	value *StoryDetail
	isSet bool
}

func (v NullableStoryDetail) Get() *StoryDetail {
	return v.value
}

func (v *NullableStoryDetail) Set(val *StoryDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableStoryDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableStoryDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoryDetail(val *StoryDetail) *NullableStoryDetail {
	return &NullableStoryDetail{value: val, isSet: true}
}

func (v NullableStoryDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoryDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


