/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetArticle200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetArticle200Response{}

// GetArticle200Response struct for GetArticle200Response
type GetArticle200Response struct {
	Item *Item `json:"item,omitempty"`
}

// NewGetArticle200Response instantiates a new GetArticle200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetArticle200Response() *GetArticle200Response {
	this := GetArticle200Response{}
	return &this
}

// NewGetArticle200ResponseWithDefaults instantiates a new GetArticle200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetArticle200ResponseWithDefaults() *GetArticle200Response {
	this := GetArticle200Response{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *GetArticle200Response) GetItem() Item {
	if o == nil || IsNil(o.Item) {
		var ret Item
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetArticle200Response) GetItemOk() (*Item, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *GetArticle200Response) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given Item and assigns it to the Item field.
func (o *GetArticle200Response) SetItem(v Item) {
	o.Item = &v
}

func (o GetArticle200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetArticle200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableGetArticle200Response struct {
	value *GetArticle200Response
	isSet bool
}

func (v NullableGetArticle200Response) Get() *GetArticle200Response {
	return v.value
}

func (v *NullableGetArticle200Response) Set(val *GetArticle200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetArticle200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetArticle200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetArticle200Response(val *GetArticle200Response) *NullableGetArticle200Response {
	return &NullableGetArticle200Response{value: val, isSet: true}
}

func (v NullableGetArticle200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetArticle200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


