/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the StoryUpdateSignalNewArticlesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoryUpdateSignalNewArticlesInner{}

// StoryUpdateSignalNewArticlesInner struct for StoryUpdateSignalNewArticlesInner
type StoryUpdateSignalNewArticlesInner struct {
	UrlHash *string `json:"url_hash,omitempty"`
	Title *string `json:"title,omitempty"`
	SourceName *string `json:"source_name,omitempty"`
	PublishedAt *int64 `json:"published_at,omitempty"`
}

// NewStoryUpdateSignalNewArticlesInner instantiates a new StoryUpdateSignalNewArticlesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoryUpdateSignalNewArticlesInner() *StoryUpdateSignalNewArticlesInner {
	this := StoryUpdateSignalNewArticlesInner{}
	return &this
}

// NewStoryUpdateSignalNewArticlesInnerWithDefaults instantiates a new StoryUpdateSignalNewArticlesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoryUpdateSignalNewArticlesInnerWithDefaults() *StoryUpdateSignalNewArticlesInner {
	this := StoryUpdateSignalNewArticlesInner{}
	return &this
}

// GetUrlHash returns the UrlHash field value if set, zero value otherwise.
func (o *StoryUpdateSignalNewArticlesInner) GetUrlHash() string {
	if o == nil || IsNil(o.UrlHash) {
		var ret string
		return ret
	}
	return *o.UrlHash
}

// GetUrlHashOk returns a tuple with the UrlHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignalNewArticlesInner) GetUrlHashOk() (*string, bool) {
	if o == nil || IsNil(o.UrlHash) {
		return nil, false
	}
	return o.UrlHash, true
}

// HasUrlHash returns a boolean if a field has been set.
func (o *StoryUpdateSignalNewArticlesInner) HasUrlHash() bool {
	if o != nil && !IsNil(o.UrlHash) {
		return true
	}

	return false
}

// SetUrlHash gets a reference to the given string and assigns it to the UrlHash field.
func (o *StoryUpdateSignalNewArticlesInner) SetUrlHash(v string) {
	o.UrlHash = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *StoryUpdateSignalNewArticlesInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignalNewArticlesInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *StoryUpdateSignalNewArticlesInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *StoryUpdateSignalNewArticlesInner) SetTitle(v string) {
	o.Title = &v
}

// GetSourceName returns the SourceName field value if set, zero value otherwise.
func (o *StoryUpdateSignalNewArticlesInner) GetSourceName() string {
	if o == nil || IsNil(o.SourceName) {
		var ret string
		return ret
	}
	return *o.SourceName
}

// GetSourceNameOk returns a tuple with the SourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignalNewArticlesInner) GetSourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceName) {
		return nil, false
	}
	return o.SourceName, true
}

// HasSourceName returns a boolean if a field has been set.
func (o *StoryUpdateSignalNewArticlesInner) HasSourceName() bool {
	if o != nil && !IsNil(o.SourceName) {
		return true
	}

	return false
}

// SetSourceName gets a reference to the given string and assigns it to the SourceName field.
func (o *StoryUpdateSignalNewArticlesInner) SetSourceName(v string) {
	o.SourceName = &v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise.
func (o *StoryUpdateSignalNewArticlesInner) GetPublishedAt() int64 {
	if o == nil || IsNil(o.PublishedAt) {
		var ret int64
		return ret
	}
	return *o.PublishedAt
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryUpdateSignalNewArticlesInner) GetPublishedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.PublishedAt) {
		return nil, false
	}
	return o.PublishedAt, true
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *StoryUpdateSignalNewArticlesInner) HasPublishedAt() bool {
	if o != nil && !IsNil(o.PublishedAt) {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given int64 and assigns it to the PublishedAt field.
func (o *StoryUpdateSignalNewArticlesInner) SetPublishedAt(v int64) {
	o.PublishedAt = &v
}

func (o StoryUpdateSignalNewArticlesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoryUpdateSignalNewArticlesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UrlHash) {
		toSerialize["url_hash"] = o.UrlHash
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.SourceName) {
		toSerialize["source_name"] = o.SourceName
	}
	if !IsNil(o.PublishedAt) {
		toSerialize["published_at"] = o.PublishedAt
	}
	return toSerialize, nil
}

type NullableStoryUpdateSignalNewArticlesInner struct {
	value *StoryUpdateSignalNewArticlesInner
	isSet bool
}

func (v NullableStoryUpdateSignalNewArticlesInner) Get() *StoryUpdateSignalNewArticlesInner {
	return v.value
}

func (v *NullableStoryUpdateSignalNewArticlesInner) Set(val *StoryUpdateSignalNewArticlesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableStoryUpdateSignalNewArticlesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableStoryUpdateSignalNewArticlesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoryUpdateSignalNewArticlesInner(val *StoryUpdateSignalNewArticlesInner) *NullableStoryUpdateSignalNewArticlesInner {
	return &NullableStoryUpdateSignalNewArticlesInner{value: val, isSet: true}
}

func (v NullableStoryUpdateSignalNewArticlesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoryUpdateSignalNewArticlesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


