/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GraphEdge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphEdge{}

// GraphEdge struct for GraphEdge
type GraphEdge struct {
	Id *int32 `json:"id,omitempty"`
	SourceEntityId *int32 `json:"source_entity_id,omitempty"`
	TargetEntityId *int32 `json:"target_entity_id,omitempty"`
	RelationshipType *string `json:"relationship_type,omitempty"`
	Confidence *float32 `json:"confidence,omitempty"`
	ArticleCount *int32 `json:"article_count,omitempty"`
	SourceEntity *GraphNode `json:"source_entity,omitempty"`
	TargetEntity *GraphNode `json:"target_entity,omitempty"`
}

// NewGraphEdge instantiates a new GraphEdge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphEdge() *GraphEdge {
	this := GraphEdge{}
	return &this
}

// NewGraphEdgeWithDefaults instantiates a new GraphEdge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphEdgeWithDefaults() *GraphEdge {
	this := GraphEdge{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GraphEdge) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GraphEdge) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GraphEdge) SetId(v int32) {
	o.Id = &v
}

// GetSourceEntityId returns the SourceEntityId field value if set, zero value otherwise.
func (o *GraphEdge) GetSourceEntityId() int32 {
	if o == nil || IsNil(o.SourceEntityId) {
		var ret int32
		return ret
	}
	return *o.SourceEntityId
}

// GetSourceEntityIdOk returns a tuple with the SourceEntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetSourceEntityIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SourceEntityId) {
		return nil, false
	}
	return o.SourceEntityId, true
}

// HasSourceEntityId returns a boolean if a field has been set.
func (o *GraphEdge) HasSourceEntityId() bool {
	if o != nil && !IsNil(o.SourceEntityId) {
		return true
	}

	return false
}

// SetSourceEntityId gets a reference to the given int32 and assigns it to the SourceEntityId field.
func (o *GraphEdge) SetSourceEntityId(v int32) {
	o.SourceEntityId = &v
}

// GetTargetEntityId returns the TargetEntityId field value if set, zero value otherwise.
func (o *GraphEdge) GetTargetEntityId() int32 {
	if o == nil || IsNil(o.TargetEntityId) {
		var ret int32
		return ret
	}
	return *o.TargetEntityId
}

// GetTargetEntityIdOk returns a tuple with the TargetEntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetTargetEntityIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TargetEntityId) {
		return nil, false
	}
	return o.TargetEntityId, true
}

// HasTargetEntityId returns a boolean if a field has been set.
func (o *GraphEdge) HasTargetEntityId() bool {
	if o != nil && !IsNil(o.TargetEntityId) {
		return true
	}

	return false
}

// SetTargetEntityId gets a reference to the given int32 and assigns it to the TargetEntityId field.
func (o *GraphEdge) SetTargetEntityId(v int32) {
	o.TargetEntityId = &v
}

// GetRelationshipType returns the RelationshipType field value if set, zero value otherwise.
func (o *GraphEdge) GetRelationshipType() string {
	if o == nil || IsNil(o.RelationshipType) {
		var ret string
		return ret
	}
	return *o.RelationshipType
}

// GetRelationshipTypeOk returns a tuple with the RelationshipType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetRelationshipTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RelationshipType) {
		return nil, false
	}
	return o.RelationshipType, true
}

// HasRelationshipType returns a boolean if a field has been set.
func (o *GraphEdge) HasRelationshipType() bool {
	if o != nil && !IsNil(o.RelationshipType) {
		return true
	}

	return false
}

// SetRelationshipType gets a reference to the given string and assigns it to the RelationshipType field.
func (o *GraphEdge) SetRelationshipType(v string) {
	o.RelationshipType = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *GraphEdge) GetConfidence() float32 {
	if o == nil || IsNil(o.Confidence) {
		var ret float32
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *GraphEdge) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float32 and assigns it to the Confidence field.
func (o *GraphEdge) SetConfidence(v float32) {
	o.Confidence = &v
}

// GetArticleCount returns the ArticleCount field value if set, zero value otherwise.
func (o *GraphEdge) GetArticleCount() int32 {
	if o == nil || IsNil(o.ArticleCount) {
		var ret int32
		return ret
	}
	return *o.ArticleCount
}

// GetArticleCountOk returns a tuple with the ArticleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetArticleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ArticleCount) {
		return nil, false
	}
	return o.ArticleCount, true
}

// HasArticleCount returns a boolean if a field has been set.
func (o *GraphEdge) HasArticleCount() bool {
	if o != nil && !IsNil(o.ArticleCount) {
		return true
	}

	return false
}

// SetArticleCount gets a reference to the given int32 and assigns it to the ArticleCount field.
func (o *GraphEdge) SetArticleCount(v int32) {
	o.ArticleCount = &v
}

// GetSourceEntity returns the SourceEntity field value if set, zero value otherwise.
func (o *GraphEdge) GetSourceEntity() GraphNode {
	if o == nil || IsNil(o.SourceEntity) {
		var ret GraphNode
		return ret
	}
	return *o.SourceEntity
}

// GetSourceEntityOk returns a tuple with the SourceEntity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetSourceEntityOk() (*GraphNode, bool) {
	if o == nil || IsNil(o.SourceEntity) {
		return nil, false
	}
	return o.SourceEntity, true
}

// HasSourceEntity returns a boolean if a field has been set.
func (o *GraphEdge) HasSourceEntity() bool {
	if o != nil && !IsNil(o.SourceEntity) {
		return true
	}

	return false
}

// SetSourceEntity gets a reference to the given GraphNode and assigns it to the SourceEntity field.
func (o *GraphEdge) SetSourceEntity(v GraphNode) {
	o.SourceEntity = &v
}

// GetTargetEntity returns the TargetEntity field value if set, zero value otherwise.
func (o *GraphEdge) GetTargetEntity() GraphNode {
	if o == nil || IsNil(o.TargetEntity) {
		var ret GraphNode
		return ret
	}
	return *o.TargetEntity
}

// GetTargetEntityOk returns a tuple with the TargetEntity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetTargetEntityOk() (*GraphNode, bool) {
	if o == nil || IsNil(o.TargetEntity) {
		return nil, false
	}
	return o.TargetEntity, true
}

// HasTargetEntity returns a boolean if a field has been set.
func (o *GraphEdge) HasTargetEntity() bool {
	if o != nil && !IsNil(o.TargetEntity) {
		return true
	}

	return false
}

// SetTargetEntity gets a reference to the given GraphNode and assigns it to the TargetEntity field.
func (o *GraphEdge) SetTargetEntity(v GraphNode) {
	o.TargetEntity = &v
}

func (o GraphEdge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphEdge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SourceEntityId) {
		toSerialize["source_entity_id"] = o.SourceEntityId
	}
	if !IsNil(o.TargetEntityId) {
		toSerialize["target_entity_id"] = o.TargetEntityId
	}
	if !IsNil(o.RelationshipType) {
		toSerialize["relationship_type"] = o.RelationshipType
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.ArticleCount) {
		toSerialize["article_count"] = o.ArticleCount
	}
	if !IsNil(o.SourceEntity) {
		toSerialize["source_entity"] = o.SourceEntity
	}
	if !IsNil(o.TargetEntity) {
		toSerialize["target_entity"] = o.TargetEntity
	}
	return toSerialize, nil
}

type NullableGraphEdge struct {
	value *GraphEdge
	isSet bool
}

func (v NullableGraphEdge) Get() *GraphEdge {
	return v.value
}

func (v *NullableGraphEdge) Set(val *GraphEdge) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphEdge) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphEdge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphEdge(val *GraphEdge) *NullableGraphEdge {
	return &NullableGraphEdge{value: val, isSet: true}
}

func (v NullableGraphEdge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphEdge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


