/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the BacktestEmbeddingFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BacktestEmbeddingFilter{}

// BacktestEmbeddingFilter struct for BacktestEmbeddingFilter
type BacktestEmbeddingFilter struct {
	// 1536-dimensional embedding vector for similarity search
	Embedding []float32 `json:"embedding,omitempty"`
	// Minimum cosine similarity threshold (0.0–1.0, default 0.75)
	Threshold *float32 `json:"threshold,omitempty"`
	// Optional label for this filter
	Label *string `json:"label,omitempty"`
}

// NewBacktestEmbeddingFilter instantiates a new BacktestEmbeddingFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBacktestEmbeddingFilter() *BacktestEmbeddingFilter {
	this := BacktestEmbeddingFilter{}
	return &this
}

// NewBacktestEmbeddingFilterWithDefaults instantiates a new BacktestEmbeddingFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBacktestEmbeddingFilterWithDefaults() *BacktestEmbeddingFilter {
	this := BacktestEmbeddingFilter{}
	return &this
}

// GetEmbedding returns the Embedding field value if set, zero value otherwise.
func (o *BacktestEmbeddingFilter) GetEmbedding() []float32 {
	if o == nil || IsNil(o.Embedding) {
		var ret []float32
		return ret
	}
	return o.Embedding
}

// GetEmbeddingOk returns a tuple with the Embedding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEmbeddingFilter) GetEmbeddingOk() ([]float32, bool) {
	if o == nil || IsNil(o.Embedding) {
		return nil, false
	}
	return o.Embedding, true
}

// HasEmbedding returns a boolean if a field has been set.
func (o *BacktestEmbeddingFilter) HasEmbedding() bool {
	if o != nil && !IsNil(o.Embedding) {
		return true
	}

	return false
}

// SetEmbedding gets a reference to the given []float32 and assigns it to the Embedding field.
func (o *BacktestEmbeddingFilter) SetEmbedding(v []float32) {
	o.Embedding = v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *BacktestEmbeddingFilter) GetThreshold() float32 {
	if o == nil || IsNil(o.Threshold) {
		var ret float32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEmbeddingFilter) GetThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *BacktestEmbeddingFilter) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given float32 and assigns it to the Threshold field.
func (o *BacktestEmbeddingFilter) SetThreshold(v float32) {
	o.Threshold = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *BacktestEmbeddingFilter) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEmbeddingFilter) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *BacktestEmbeddingFilter) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *BacktestEmbeddingFilter) SetLabel(v string) {
	o.Label = &v
}

func (o BacktestEmbeddingFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BacktestEmbeddingFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Embedding) {
		toSerialize["embedding"] = o.Embedding
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableBacktestEmbeddingFilter struct {
	value *BacktestEmbeddingFilter
	isSet bool
}

func (v NullableBacktestEmbeddingFilter) Get() *BacktestEmbeddingFilter {
	return v.value
}

func (v *NullableBacktestEmbeddingFilter) Set(val *BacktestEmbeddingFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableBacktestEmbeddingFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableBacktestEmbeddingFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBacktestEmbeddingFilter(val *BacktestEmbeddingFilter) *NullableBacktestEmbeddingFilter {
	return &NullableBacktestEmbeddingFilter{value: val, isSet: true}
}

func (v NullableBacktestEmbeddingFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBacktestEmbeddingFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


