/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the SearchArticles200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchArticles200Response{}

// SearchArticles200Response struct for SearchArticles200Response
type SearchArticles200Response struct {
	Items []Item `json:"items,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewSearchArticles200Response instantiates a new SearchArticles200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchArticles200Response() *SearchArticles200Response {
	this := SearchArticles200Response{}
	return &this
}

// NewSearchArticles200ResponseWithDefaults instantiates a new SearchArticles200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchArticles200ResponseWithDefaults() *SearchArticles200Response {
	this := SearchArticles200Response{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *SearchArticles200Response) GetItems() []Item {
	if o == nil || IsNil(o.Items) {
		var ret []Item
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchArticles200Response) GetItemsOk() ([]Item, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SearchArticles200Response) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Item and assigns it to the Items field.
func (o *SearchArticles200Response) SetItems(v []Item) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SearchArticles200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchArticles200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SearchArticles200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *SearchArticles200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o SearchArticles200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchArticles200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableSearchArticles200Response struct {
	value *SearchArticles200Response
	isSet bool
}

func (v NullableSearchArticles200Response) Get() *SearchArticles200Response {
	return v.value
}

func (v *NullableSearchArticles200Response) Set(val *SearchArticles200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchArticles200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchArticles200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchArticles200Response(val *SearchArticles200Response) *NullableSearchArticles200Response {
	return &NullableSearchArticles200Response{value: val, isSet: true}
}

func (v NullableSearchArticles200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchArticles200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


