/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the BacktestEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BacktestEvent{}

// BacktestEvent struct for BacktestEvent
type BacktestEvent struct {
	Id *int64 `json:"id,omitempty"`
	// Event timestamp (Unix milliseconds)
	Ts *int64 `json:"ts,omitempty"`
	EventType *string `json:"event_type,omitempty"`
	// Story cluster ID (0 for article-only events)
	ClusterId *int64 `json:"cluster_id,omitempty"`
	// The original WebSocket event payload
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Cosine similarity score (only present when embedding filter is active)
	Similarity *float32 `json:"similarity,omitempty"`
	// Embedding vector (only present when include_embeddings=true)
	Embedding []float32 `json:"embedding,omitempty"`
}

// NewBacktestEvent instantiates a new BacktestEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBacktestEvent() *BacktestEvent {
	this := BacktestEvent{}
	return &this
}

// NewBacktestEventWithDefaults instantiates a new BacktestEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBacktestEventWithDefaults() *BacktestEvent {
	this := BacktestEvent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BacktestEvent) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEvent) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BacktestEvent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *BacktestEvent) SetId(v int64) {
	o.Id = &v
}

// GetTs returns the Ts field value if set, zero value otherwise.
func (o *BacktestEvent) GetTs() int64 {
	if o == nil || IsNil(o.Ts) {
		var ret int64
		return ret
	}
	return *o.Ts
}

// GetTsOk returns a tuple with the Ts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEvent) GetTsOk() (*int64, bool) {
	if o == nil || IsNil(o.Ts) {
		return nil, false
	}
	return o.Ts, true
}

// HasTs returns a boolean if a field has been set.
func (o *BacktestEvent) HasTs() bool {
	if o != nil && !IsNil(o.Ts) {
		return true
	}

	return false
}

// SetTs gets a reference to the given int64 and assigns it to the Ts field.
func (o *BacktestEvent) SetTs(v int64) {
	o.Ts = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *BacktestEvent) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEvent) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *BacktestEvent) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *BacktestEvent) SetEventType(v string) {
	o.EventType = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *BacktestEvent) GetClusterId() int64 {
	if o == nil || IsNil(o.ClusterId) {
		var ret int64
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEvent) GetClusterIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *BacktestEvent) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given int64 and assigns it to the ClusterId field.
func (o *BacktestEvent) SetClusterId(v int64) {
	o.ClusterId = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *BacktestEvent) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEvent) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *BacktestEvent) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *BacktestEvent) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetSimilarity returns the Similarity field value if set, zero value otherwise.
func (o *BacktestEvent) GetSimilarity() float32 {
	if o == nil || IsNil(o.Similarity) {
		var ret float32
		return ret
	}
	return *o.Similarity
}

// GetSimilarityOk returns a tuple with the Similarity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEvent) GetSimilarityOk() (*float32, bool) {
	if o == nil || IsNil(o.Similarity) {
		return nil, false
	}
	return o.Similarity, true
}

// HasSimilarity returns a boolean if a field has been set.
func (o *BacktestEvent) HasSimilarity() bool {
	if o != nil && !IsNil(o.Similarity) {
		return true
	}

	return false
}

// SetSimilarity gets a reference to the given float32 and assigns it to the Similarity field.
func (o *BacktestEvent) SetSimilarity(v float32) {
	o.Similarity = &v
}

// GetEmbedding returns the Embedding field value if set, zero value otherwise.
func (o *BacktestEvent) GetEmbedding() []float32 {
	if o == nil || IsNil(o.Embedding) {
		var ret []float32
		return ret
	}
	return o.Embedding
}

// GetEmbeddingOk returns a tuple with the Embedding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestEvent) GetEmbeddingOk() ([]float32, bool) {
	if o == nil || IsNil(o.Embedding) {
		return nil, false
	}
	return o.Embedding, true
}

// HasEmbedding returns a boolean if a field has been set.
func (o *BacktestEvent) HasEmbedding() bool {
	if o != nil && !IsNil(o.Embedding) {
		return true
	}

	return false
}

// SetEmbedding gets a reference to the given []float32 and assigns it to the Embedding field.
func (o *BacktestEvent) SetEmbedding(v []float32) {
	o.Embedding = v
}

func (o BacktestEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BacktestEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ts) {
		toSerialize["ts"] = o.Ts
	}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.ClusterId) {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.Similarity) {
		toSerialize["similarity"] = o.Similarity
	}
	if !IsNil(o.Embedding) {
		toSerialize["embedding"] = o.Embedding
	}
	return toSerialize, nil
}

type NullableBacktestEvent struct {
	value *BacktestEvent
	isSet bool
}

func (v NullableBacktestEvent) Get() *BacktestEvent {
	return v.value
}

func (v *NullableBacktestEvent) Set(val *BacktestEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableBacktestEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableBacktestEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBacktestEvent(val *BacktestEvent) *NullableBacktestEvent {
	return &NullableBacktestEvent{value: val, isSet: true}
}

func (v NullableBacktestEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBacktestEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


