/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the ListTrendingEntities200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTrendingEntities200Response{}

// ListTrendingEntities200Response struct for ListTrendingEntities200Response
type ListTrendingEntities200Response struct {
	Entities []EntityDetail `json:"entities,omitempty"`
}

// NewListTrendingEntities200Response instantiates a new ListTrendingEntities200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTrendingEntities200Response() *ListTrendingEntities200Response {
	this := ListTrendingEntities200Response{}
	return &this
}

// NewListTrendingEntities200ResponseWithDefaults instantiates a new ListTrendingEntities200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTrendingEntities200ResponseWithDefaults() *ListTrendingEntities200Response {
	this := ListTrendingEntities200Response{}
	return &this
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *ListTrendingEntities200Response) GetEntities() []EntityDetail {
	if o == nil || IsNil(o.Entities) {
		var ret []EntityDetail
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTrendingEntities200Response) GetEntitiesOk() ([]EntityDetail, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *ListTrendingEntities200Response) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []EntityDetail and assigns it to the Entities field.
func (o *ListTrendingEntities200Response) SetEntities(v []EntityDetail) {
	o.Entities = v
}

func (o ListTrendingEntities200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTrendingEntities200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entities) {
		toSerialize["entities"] = o.Entities
	}
	return toSerialize, nil
}

type NullableListTrendingEntities200Response struct {
	value *ListTrendingEntities200Response
	isSet bool
}

func (v NullableListTrendingEntities200Response) Get() *ListTrendingEntities200Response {
	return v.value
}

func (v *NullableListTrendingEntities200Response) Set(val *ListTrendingEntities200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListTrendingEntities200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListTrendingEntities200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTrendingEntities200Response(val *ListTrendingEntities200Response) *NullableListTrendingEntities200Response {
	return &NullableListTrendingEntities200Response{value: val, isSet: true}
}

func (v NullableListTrendingEntities200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTrendingEntities200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


