/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetUsage200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsage200Response{}

// GetUsage200Response struct for GetUsage200Response
type GetUsage200Response struct {
	KeyId *string `json:"key_id,omitempty"`
	Tier *string `json:"tier,omitempty"`
	Quota *GetUsage200ResponseQuota `json:"quota,omitempty"`
	Summary *GetUsage200ResponseSummary `json:"summary,omitempty"`
	Daily []GetUsage200ResponseDailyInner `json:"daily,omitempty"`
}

// NewGetUsage200Response instantiates a new GetUsage200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsage200Response() *GetUsage200Response {
	this := GetUsage200Response{}
	return &this
}

// NewGetUsage200ResponseWithDefaults instantiates a new GetUsage200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsage200ResponseWithDefaults() *GetUsage200Response {
	this := GetUsage200Response{}
	return &this
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *GetUsage200Response) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200Response) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *GetUsage200Response) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *GetUsage200Response) SetKeyId(v string) {
	o.KeyId = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *GetUsage200Response) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200Response) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *GetUsage200Response) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *GetUsage200Response) SetTier(v string) {
	o.Tier = &v
}

// GetQuota returns the Quota field value if set, zero value otherwise.
func (o *GetUsage200Response) GetQuota() GetUsage200ResponseQuota {
	if o == nil || IsNil(o.Quota) {
		var ret GetUsage200ResponseQuota
		return ret
	}
	return *o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200Response) GetQuotaOk() (*GetUsage200ResponseQuota, bool) {
	if o == nil || IsNil(o.Quota) {
		return nil, false
	}
	return o.Quota, true
}

// HasQuota returns a boolean if a field has been set.
func (o *GetUsage200Response) HasQuota() bool {
	if o != nil && !IsNil(o.Quota) {
		return true
	}

	return false
}

// SetQuota gets a reference to the given GetUsage200ResponseQuota and assigns it to the Quota field.
func (o *GetUsage200Response) SetQuota(v GetUsage200ResponseQuota) {
	o.Quota = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *GetUsage200Response) GetSummary() GetUsage200ResponseSummary {
	if o == nil || IsNil(o.Summary) {
		var ret GetUsage200ResponseSummary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200Response) GetSummaryOk() (*GetUsage200ResponseSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *GetUsage200Response) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given GetUsage200ResponseSummary and assigns it to the Summary field.
func (o *GetUsage200Response) SetSummary(v GetUsage200ResponseSummary) {
	o.Summary = &v
}

// GetDaily returns the Daily field value if set, zero value otherwise.
func (o *GetUsage200Response) GetDaily() []GetUsage200ResponseDailyInner {
	if o == nil || IsNil(o.Daily) {
		var ret []GetUsage200ResponseDailyInner
		return ret
	}
	return o.Daily
}

// GetDailyOk returns a tuple with the Daily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200Response) GetDailyOk() ([]GetUsage200ResponseDailyInner, bool) {
	if o == nil || IsNil(o.Daily) {
		return nil, false
	}
	return o.Daily, true
}

// HasDaily returns a boolean if a field has been set.
func (o *GetUsage200Response) HasDaily() bool {
	if o != nil && !IsNil(o.Daily) {
		return true
	}

	return false
}

// SetDaily gets a reference to the given []GetUsage200ResponseDailyInner and assigns it to the Daily field.
func (o *GetUsage200Response) SetDaily(v []GetUsage200ResponseDailyInner) {
	o.Daily = v
}

func (o GetUsage200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsage200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyId) {
		toSerialize["key_id"] = o.KeyId
	}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.Quota) {
		toSerialize["quota"] = o.Quota
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Daily) {
		toSerialize["daily"] = o.Daily
	}
	return toSerialize, nil
}

type NullableGetUsage200Response struct {
	value *GetUsage200Response
	isSet bool
}

func (v NullableGetUsage200Response) Get() *GetUsage200Response {
	return v.value
}

func (v *NullableGetUsage200Response) Set(val *GetUsage200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsage200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsage200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsage200Response(val *GetUsage200Response) *NullableGetUsage200Response {
	return &NullableGetUsage200Response{value: val, isSet: true}
}

func (v NullableGetUsage200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsage200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


