/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetUsage200ResponseSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsage200ResponseSummary{}

// GetUsage200ResponseSummary struct for GetUsage200ResponseSummary
type GetUsage200ResponseSummary struct {
	TotalRequests *int32 `json:"total_requests,omitempty"`
	TotalBytes *int32 `json:"total_bytes,omitempty"`
	TotalErrors *int32 `json:"total_errors,omitempty"`
	AvgLatencyMs *float32 `json:"avg_latency_ms,omitempty"`
	TopEndpoints []GetUsage200ResponseSummaryTopEndpointsInner `json:"top_endpoints,omitempty"`
}

// NewGetUsage200ResponseSummary instantiates a new GetUsage200ResponseSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsage200ResponseSummary() *GetUsage200ResponseSummary {
	this := GetUsage200ResponseSummary{}
	return &this
}

// NewGetUsage200ResponseSummaryWithDefaults instantiates a new GetUsage200ResponseSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsage200ResponseSummaryWithDefaults() *GetUsage200ResponseSummary {
	this := GetUsage200ResponseSummary{}
	return &this
}

// GetTotalRequests returns the TotalRequests field value if set, zero value otherwise.
func (o *GetUsage200ResponseSummary) GetTotalRequests() int32 {
	if o == nil || IsNil(o.TotalRequests) {
		var ret int32
		return ret
	}
	return *o.TotalRequests
}

// GetTotalRequestsOk returns a tuple with the TotalRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseSummary) GetTotalRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRequests) {
		return nil, false
	}
	return o.TotalRequests, true
}

// HasTotalRequests returns a boolean if a field has been set.
func (o *GetUsage200ResponseSummary) HasTotalRequests() bool {
	if o != nil && !IsNil(o.TotalRequests) {
		return true
	}

	return false
}

// SetTotalRequests gets a reference to the given int32 and assigns it to the TotalRequests field.
func (o *GetUsage200ResponseSummary) SetTotalRequests(v int32) {
	o.TotalRequests = &v
}

// GetTotalBytes returns the TotalBytes field value if set, zero value otherwise.
func (o *GetUsage200ResponseSummary) GetTotalBytes() int32 {
	if o == nil || IsNil(o.TotalBytes) {
		var ret int32
		return ret
	}
	return *o.TotalBytes
}

// GetTotalBytesOk returns a tuple with the TotalBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseSummary) GetTotalBytesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalBytes) {
		return nil, false
	}
	return o.TotalBytes, true
}

// HasTotalBytes returns a boolean if a field has been set.
func (o *GetUsage200ResponseSummary) HasTotalBytes() bool {
	if o != nil && !IsNil(o.TotalBytes) {
		return true
	}

	return false
}

// SetTotalBytes gets a reference to the given int32 and assigns it to the TotalBytes field.
func (o *GetUsage200ResponseSummary) SetTotalBytes(v int32) {
	o.TotalBytes = &v
}

// GetTotalErrors returns the TotalErrors field value if set, zero value otherwise.
func (o *GetUsage200ResponseSummary) GetTotalErrors() int32 {
	if o == nil || IsNil(o.TotalErrors) {
		var ret int32
		return ret
	}
	return *o.TotalErrors
}

// GetTotalErrorsOk returns a tuple with the TotalErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseSummary) GetTotalErrorsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalErrors) {
		return nil, false
	}
	return o.TotalErrors, true
}

// HasTotalErrors returns a boolean if a field has been set.
func (o *GetUsage200ResponseSummary) HasTotalErrors() bool {
	if o != nil && !IsNil(o.TotalErrors) {
		return true
	}

	return false
}

// SetTotalErrors gets a reference to the given int32 and assigns it to the TotalErrors field.
func (o *GetUsage200ResponseSummary) SetTotalErrors(v int32) {
	o.TotalErrors = &v
}

// GetAvgLatencyMs returns the AvgLatencyMs field value if set, zero value otherwise.
func (o *GetUsage200ResponseSummary) GetAvgLatencyMs() float32 {
	if o == nil || IsNil(o.AvgLatencyMs) {
		var ret float32
		return ret
	}
	return *o.AvgLatencyMs
}

// GetAvgLatencyMsOk returns a tuple with the AvgLatencyMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseSummary) GetAvgLatencyMsOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgLatencyMs) {
		return nil, false
	}
	return o.AvgLatencyMs, true
}

// HasAvgLatencyMs returns a boolean if a field has been set.
func (o *GetUsage200ResponseSummary) HasAvgLatencyMs() bool {
	if o != nil && !IsNil(o.AvgLatencyMs) {
		return true
	}

	return false
}

// SetAvgLatencyMs gets a reference to the given float32 and assigns it to the AvgLatencyMs field.
func (o *GetUsage200ResponseSummary) SetAvgLatencyMs(v float32) {
	o.AvgLatencyMs = &v
}

// GetTopEndpoints returns the TopEndpoints field value if set, zero value otherwise.
func (o *GetUsage200ResponseSummary) GetTopEndpoints() []GetUsage200ResponseSummaryTopEndpointsInner {
	if o == nil || IsNil(o.TopEndpoints) {
		var ret []GetUsage200ResponseSummaryTopEndpointsInner
		return ret
	}
	return o.TopEndpoints
}

// GetTopEndpointsOk returns a tuple with the TopEndpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseSummary) GetTopEndpointsOk() ([]GetUsage200ResponseSummaryTopEndpointsInner, bool) {
	if o == nil || IsNil(o.TopEndpoints) {
		return nil, false
	}
	return o.TopEndpoints, true
}

// HasTopEndpoints returns a boolean if a field has been set.
func (o *GetUsage200ResponseSummary) HasTopEndpoints() bool {
	if o != nil && !IsNil(o.TopEndpoints) {
		return true
	}

	return false
}

// SetTopEndpoints gets a reference to the given []GetUsage200ResponseSummaryTopEndpointsInner and assigns it to the TopEndpoints field.
func (o *GetUsage200ResponseSummary) SetTopEndpoints(v []GetUsage200ResponseSummaryTopEndpointsInner) {
	o.TopEndpoints = v
}

func (o GetUsage200ResponseSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsage200ResponseSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalRequests) {
		toSerialize["total_requests"] = o.TotalRequests
	}
	if !IsNil(o.TotalBytes) {
		toSerialize["total_bytes"] = o.TotalBytes
	}
	if !IsNil(o.TotalErrors) {
		toSerialize["total_errors"] = o.TotalErrors
	}
	if !IsNil(o.AvgLatencyMs) {
		toSerialize["avg_latency_ms"] = o.AvgLatencyMs
	}
	if !IsNil(o.TopEndpoints) {
		toSerialize["top_endpoints"] = o.TopEndpoints
	}
	return toSerialize, nil
}

type NullableGetUsage200ResponseSummary struct {
	value *GetUsage200ResponseSummary
	isSet bool
}

func (v NullableGetUsage200ResponseSummary) Get() *GetUsage200ResponseSummary {
	return v.value
}

func (v *NullableGetUsage200ResponseSummary) Set(val *GetUsage200ResponseSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsage200ResponseSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsage200ResponseSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsage200ResponseSummary(val *GetUsage200ResponseSummary) *NullableGetUsage200ResponseSummary {
	return &NullableGetUsage200ResponseSummary{value: val, isSet: true}
}

func (v NullableGetUsage200ResponseSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsage200ResponseSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


