/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the SourceRanking type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceRanking{}

// SourceRanking struct for SourceRanking
type SourceRanking struct {
	SourceId *string `json:"source_id,omitempty"`
	SourceName *string `json:"source_name,omitempty"`
	LogoUrl *string `json:"logo_url,omitempty"`
	FirstToClusterScore *float32 `json:"first_to_cluster_score,omitempty"`
	ClusterFrequencyScore *float32 `json:"cluster_frequency_score,omitempty"`
	SpeedScore *float32 `json:"speed_score,omitempty"`
	TopicalAuthorityScore *float32 `json:"topical_authority_score,omitempty"`
	ContentDiversityScore *float32 `json:"content_diversity_score,omitempty"`
	ExtractionSuccessScore *float32 `json:"extraction_success_score,omitempty"`
	NeutralityScore *float32 `json:"neutrality_score,omitempty"`
	SensationalismScore *float32 `json:"sensationalism_score,omitempty"`
	ReliabilityScore *float32 `json:"reliability_score,omitempty"`
	OverallScore *float32 `json:"overall_score,omitempty"`
	Tier *string `json:"tier,omitempty"`
	DescriptionOneLiner *string `json:"description_one_liner,omitempty"`
	DescriptionSummary *string `json:"description_summary,omitempty"`
}

// NewSourceRanking instantiates a new SourceRanking object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceRanking() *SourceRanking {
	this := SourceRanking{}
	return &this
}

// NewSourceRankingWithDefaults instantiates a new SourceRanking object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceRankingWithDefaults() *SourceRanking {
	this := SourceRanking{}
	return &this
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *SourceRanking) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *SourceRanking) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *SourceRanking) SetSourceId(v string) {
	o.SourceId = &v
}

// GetSourceName returns the SourceName field value if set, zero value otherwise.
func (o *SourceRanking) GetSourceName() string {
	if o == nil || IsNil(o.SourceName) {
		var ret string
		return ret
	}
	return *o.SourceName
}

// GetSourceNameOk returns a tuple with the SourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetSourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceName) {
		return nil, false
	}
	return o.SourceName, true
}

// HasSourceName returns a boolean if a field has been set.
func (o *SourceRanking) HasSourceName() bool {
	if o != nil && !IsNil(o.SourceName) {
		return true
	}

	return false
}

// SetSourceName gets a reference to the given string and assigns it to the SourceName field.
func (o *SourceRanking) SetSourceName(v string) {
	o.SourceName = &v
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *SourceRanking) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl) {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetLogoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoUrl) {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *SourceRanking) HasLogoUrl() bool {
	if o != nil && !IsNil(o.LogoUrl) {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *SourceRanking) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

// GetFirstToClusterScore returns the FirstToClusterScore field value if set, zero value otherwise.
func (o *SourceRanking) GetFirstToClusterScore() float32 {
	if o == nil || IsNil(o.FirstToClusterScore) {
		var ret float32
		return ret
	}
	return *o.FirstToClusterScore
}

// GetFirstToClusterScoreOk returns a tuple with the FirstToClusterScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetFirstToClusterScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.FirstToClusterScore) {
		return nil, false
	}
	return o.FirstToClusterScore, true
}

// HasFirstToClusterScore returns a boolean if a field has been set.
func (o *SourceRanking) HasFirstToClusterScore() bool {
	if o != nil && !IsNil(o.FirstToClusterScore) {
		return true
	}

	return false
}

// SetFirstToClusterScore gets a reference to the given float32 and assigns it to the FirstToClusterScore field.
func (o *SourceRanking) SetFirstToClusterScore(v float32) {
	o.FirstToClusterScore = &v
}

// GetClusterFrequencyScore returns the ClusterFrequencyScore field value if set, zero value otherwise.
func (o *SourceRanking) GetClusterFrequencyScore() float32 {
	if o == nil || IsNil(o.ClusterFrequencyScore) {
		var ret float32
		return ret
	}
	return *o.ClusterFrequencyScore
}

// GetClusterFrequencyScoreOk returns a tuple with the ClusterFrequencyScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetClusterFrequencyScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.ClusterFrequencyScore) {
		return nil, false
	}
	return o.ClusterFrequencyScore, true
}

// HasClusterFrequencyScore returns a boolean if a field has been set.
func (o *SourceRanking) HasClusterFrequencyScore() bool {
	if o != nil && !IsNil(o.ClusterFrequencyScore) {
		return true
	}

	return false
}

// SetClusterFrequencyScore gets a reference to the given float32 and assigns it to the ClusterFrequencyScore field.
func (o *SourceRanking) SetClusterFrequencyScore(v float32) {
	o.ClusterFrequencyScore = &v
}

// GetSpeedScore returns the SpeedScore field value if set, zero value otherwise.
func (o *SourceRanking) GetSpeedScore() float32 {
	if o == nil || IsNil(o.SpeedScore) {
		var ret float32
		return ret
	}
	return *o.SpeedScore
}

// GetSpeedScoreOk returns a tuple with the SpeedScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetSpeedScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.SpeedScore) {
		return nil, false
	}
	return o.SpeedScore, true
}

// HasSpeedScore returns a boolean if a field has been set.
func (o *SourceRanking) HasSpeedScore() bool {
	if o != nil && !IsNil(o.SpeedScore) {
		return true
	}

	return false
}

// SetSpeedScore gets a reference to the given float32 and assigns it to the SpeedScore field.
func (o *SourceRanking) SetSpeedScore(v float32) {
	o.SpeedScore = &v
}

// GetTopicalAuthorityScore returns the TopicalAuthorityScore field value if set, zero value otherwise.
func (o *SourceRanking) GetTopicalAuthorityScore() float32 {
	if o == nil || IsNil(o.TopicalAuthorityScore) {
		var ret float32
		return ret
	}
	return *o.TopicalAuthorityScore
}

// GetTopicalAuthorityScoreOk returns a tuple with the TopicalAuthorityScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetTopicalAuthorityScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.TopicalAuthorityScore) {
		return nil, false
	}
	return o.TopicalAuthorityScore, true
}

// HasTopicalAuthorityScore returns a boolean if a field has been set.
func (o *SourceRanking) HasTopicalAuthorityScore() bool {
	if o != nil && !IsNil(o.TopicalAuthorityScore) {
		return true
	}

	return false
}

// SetTopicalAuthorityScore gets a reference to the given float32 and assigns it to the TopicalAuthorityScore field.
func (o *SourceRanking) SetTopicalAuthorityScore(v float32) {
	o.TopicalAuthorityScore = &v
}

// GetContentDiversityScore returns the ContentDiversityScore field value if set, zero value otherwise.
func (o *SourceRanking) GetContentDiversityScore() float32 {
	if o == nil || IsNil(o.ContentDiversityScore) {
		var ret float32
		return ret
	}
	return *o.ContentDiversityScore
}

// GetContentDiversityScoreOk returns a tuple with the ContentDiversityScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetContentDiversityScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.ContentDiversityScore) {
		return nil, false
	}
	return o.ContentDiversityScore, true
}

// HasContentDiversityScore returns a boolean if a field has been set.
func (o *SourceRanking) HasContentDiversityScore() bool {
	if o != nil && !IsNil(o.ContentDiversityScore) {
		return true
	}

	return false
}

// SetContentDiversityScore gets a reference to the given float32 and assigns it to the ContentDiversityScore field.
func (o *SourceRanking) SetContentDiversityScore(v float32) {
	o.ContentDiversityScore = &v
}

// GetExtractionSuccessScore returns the ExtractionSuccessScore field value if set, zero value otherwise.
func (o *SourceRanking) GetExtractionSuccessScore() float32 {
	if o == nil || IsNil(o.ExtractionSuccessScore) {
		var ret float32
		return ret
	}
	return *o.ExtractionSuccessScore
}

// GetExtractionSuccessScoreOk returns a tuple with the ExtractionSuccessScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetExtractionSuccessScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.ExtractionSuccessScore) {
		return nil, false
	}
	return o.ExtractionSuccessScore, true
}

// HasExtractionSuccessScore returns a boolean if a field has been set.
func (o *SourceRanking) HasExtractionSuccessScore() bool {
	if o != nil && !IsNil(o.ExtractionSuccessScore) {
		return true
	}

	return false
}

// SetExtractionSuccessScore gets a reference to the given float32 and assigns it to the ExtractionSuccessScore field.
func (o *SourceRanking) SetExtractionSuccessScore(v float32) {
	o.ExtractionSuccessScore = &v
}

// GetNeutralityScore returns the NeutralityScore field value if set, zero value otherwise.
func (o *SourceRanking) GetNeutralityScore() float32 {
	if o == nil || IsNil(o.NeutralityScore) {
		var ret float32
		return ret
	}
	return *o.NeutralityScore
}

// GetNeutralityScoreOk returns a tuple with the NeutralityScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetNeutralityScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.NeutralityScore) {
		return nil, false
	}
	return o.NeutralityScore, true
}

// HasNeutralityScore returns a boolean if a field has been set.
func (o *SourceRanking) HasNeutralityScore() bool {
	if o != nil && !IsNil(o.NeutralityScore) {
		return true
	}

	return false
}

// SetNeutralityScore gets a reference to the given float32 and assigns it to the NeutralityScore field.
func (o *SourceRanking) SetNeutralityScore(v float32) {
	o.NeutralityScore = &v
}

// GetSensationalismScore returns the SensationalismScore field value if set, zero value otherwise.
func (o *SourceRanking) GetSensationalismScore() float32 {
	if o == nil || IsNil(o.SensationalismScore) {
		var ret float32
		return ret
	}
	return *o.SensationalismScore
}

// GetSensationalismScoreOk returns a tuple with the SensationalismScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetSensationalismScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.SensationalismScore) {
		return nil, false
	}
	return o.SensationalismScore, true
}

// HasSensationalismScore returns a boolean if a field has been set.
func (o *SourceRanking) HasSensationalismScore() bool {
	if o != nil && !IsNil(o.SensationalismScore) {
		return true
	}

	return false
}

// SetSensationalismScore gets a reference to the given float32 and assigns it to the SensationalismScore field.
func (o *SourceRanking) SetSensationalismScore(v float32) {
	o.SensationalismScore = &v
}

// GetReliabilityScore returns the ReliabilityScore field value if set, zero value otherwise.
func (o *SourceRanking) GetReliabilityScore() float32 {
	if o == nil || IsNil(o.ReliabilityScore) {
		var ret float32
		return ret
	}
	return *o.ReliabilityScore
}

// GetReliabilityScoreOk returns a tuple with the ReliabilityScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetReliabilityScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.ReliabilityScore) {
		return nil, false
	}
	return o.ReliabilityScore, true
}

// HasReliabilityScore returns a boolean if a field has been set.
func (o *SourceRanking) HasReliabilityScore() bool {
	if o != nil && !IsNil(o.ReliabilityScore) {
		return true
	}

	return false
}

// SetReliabilityScore gets a reference to the given float32 and assigns it to the ReliabilityScore field.
func (o *SourceRanking) SetReliabilityScore(v float32) {
	o.ReliabilityScore = &v
}

// GetOverallScore returns the OverallScore field value if set, zero value otherwise.
func (o *SourceRanking) GetOverallScore() float32 {
	if o == nil || IsNil(o.OverallScore) {
		var ret float32
		return ret
	}
	return *o.OverallScore
}

// GetOverallScoreOk returns a tuple with the OverallScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetOverallScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.OverallScore) {
		return nil, false
	}
	return o.OverallScore, true
}

// HasOverallScore returns a boolean if a field has been set.
func (o *SourceRanking) HasOverallScore() bool {
	if o != nil && !IsNil(o.OverallScore) {
		return true
	}

	return false
}

// SetOverallScore gets a reference to the given float32 and assigns it to the OverallScore field.
func (o *SourceRanking) SetOverallScore(v float32) {
	o.OverallScore = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *SourceRanking) GetTier() string {
	if o == nil || IsNil(o.Tier) {
		var ret string
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetTierOk() (*string, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *SourceRanking) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given string and assigns it to the Tier field.
func (o *SourceRanking) SetTier(v string) {
	o.Tier = &v
}

// GetDescriptionOneLiner returns the DescriptionOneLiner field value if set, zero value otherwise.
func (o *SourceRanking) GetDescriptionOneLiner() string {
	if o == nil || IsNil(o.DescriptionOneLiner) {
		var ret string
		return ret
	}
	return *o.DescriptionOneLiner
}

// GetDescriptionOneLinerOk returns a tuple with the DescriptionOneLiner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetDescriptionOneLinerOk() (*string, bool) {
	if o == nil || IsNil(o.DescriptionOneLiner) {
		return nil, false
	}
	return o.DescriptionOneLiner, true
}

// HasDescriptionOneLiner returns a boolean if a field has been set.
func (o *SourceRanking) HasDescriptionOneLiner() bool {
	if o != nil && !IsNil(o.DescriptionOneLiner) {
		return true
	}

	return false
}

// SetDescriptionOneLiner gets a reference to the given string and assigns it to the DescriptionOneLiner field.
func (o *SourceRanking) SetDescriptionOneLiner(v string) {
	o.DescriptionOneLiner = &v
}

// GetDescriptionSummary returns the DescriptionSummary field value if set, zero value otherwise.
func (o *SourceRanking) GetDescriptionSummary() string {
	if o == nil || IsNil(o.DescriptionSummary) {
		var ret string
		return ret
	}
	return *o.DescriptionSummary
}

// GetDescriptionSummaryOk returns a tuple with the DescriptionSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceRanking) GetDescriptionSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.DescriptionSummary) {
		return nil, false
	}
	return o.DescriptionSummary, true
}

// HasDescriptionSummary returns a boolean if a field has been set.
func (o *SourceRanking) HasDescriptionSummary() bool {
	if o != nil && !IsNil(o.DescriptionSummary) {
		return true
	}

	return false
}

// SetDescriptionSummary gets a reference to the given string and assigns it to the DescriptionSummary field.
func (o *SourceRanking) SetDescriptionSummary(v string) {
	o.DescriptionSummary = &v
}

func (o SourceRanking) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceRanking) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	if !IsNil(o.SourceName) {
		toSerialize["source_name"] = o.SourceName
	}
	if !IsNil(o.LogoUrl) {
		toSerialize["logo_url"] = o.LogoUrl
	}
	if !IsNil(o.FirstToClusterScore) {
		toSerialize["first_to_cluster_score"] = o.FirstToClusterScore
	}
	if !IsNil(o.ClusterFrequencyScore) {
		toSerialize["cluster_frequency_score"] = o.ClusterFrequencyScore
	}
	if !IsNil(o.SpeedScore) {
		toSerialize["speed_score"] = o.SpeedScore
	}
	if !IsNil(o.TopicalAuthorityScore) {
		toSerialize["topical_authority_score"] = o.TopicalAuthorityScore
	}
	if !IsNil(o.ContentDiversityScore) {
		toSerialize["content_diversity_score"] = o.ContentDiversityScore
	}
	if !IsNil(o.ExtractionSuccessScore) {
		toSerialize["extraction_success_score"] = o.ExtractionSuccessScore
	}
	if !IsNil(o.NeutralityScore) {
		toSerialize["neutrality_score"] = o.NeutralityScore
	}
	if !IsNil(o.SensationalismScore) {
		toSerialize["sensationalism_score"] = o.SensationalismScore
	}
	if !IsNil(o.ReliabilityScore) {
		toSerialize["reliability_score"] = o.ReliabilityScore
	}
	if !IsNil(o.OverallScore) {
		toSerialize["overall_score"] = o.OverallScore
	}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.DescriptionOneLiner) {
		toSerialize["description_one_liner"] = o.DescriptionOneLiner
	}
	if !IsNil(o.DescriptionSummary) {
		toSerialize["description_summary"] = o.DescriptionSummary
	}
	return toSerialize, nil
}

type NullableSourceRanking struct {
	value *SourceRanking
	isSet bool
}

func (v NullableSourceRanking) Get() *SourceRanking {
	return v.value
}

func (v *NullableSourceRanking) Set(val *SourceRanking) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceRanking) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceRanking) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceRanking(val *SourceRanking) *NullableSourceRanking {
	return &NullableSourceRanking{value: val, isSet: true}
}

func (v NullableSourceRanking) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceRanking) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


