/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the ListSourceRankings200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSourceRankings200Response{}

// ListSourceRankings200Response struct for ListSourceRankings200Response
type ListSourceRankings200Response struct {
	Rankings []SourceRanking `json:"rankings,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewListSourceRankings200Response instantiates a new ListSourceRankings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSourceRankings200Response() *ListSourceRankings200Response {
	this := ListSourceRankings200Response{}
	return &this
}

// NewListSourceRankings200ResponseWithDefaults instantiates a new ListSourceRankings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSourceRankings200ResponseWithDefaults() *ListSourceRankings200Response {
	this := ListSourceRankings200Response{}
	return &this
}

// GetRankings returns the Rankings field value if set, zero value otherwise.
func (o *ListSourceRankings200Response) GetRankings() []SourceRanking {
	if o == nil || IsNil(o.Rankings) {
		var ret []SourceRanking
		return ret
	}
	return o.Rankings
}

// GetRankingsOk returns a tuple with the Rankings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSourceRankings200Response) GetRankingsOk() ([]SourceRanking, bool) {
	if o == nil || IsNil(o.Rankings) {
		return nil, false
	}
	return o.Rankings, true
}

// HasRankings returns a boolean if a field has been set.
func (o *ListSourceRankings200Response) HasRankings() bool {
	if o != nil && !IsNil(o.Rankings) {
		return true
	}

	return false
}

// SetRankings gets a reference to the given []SourceRanking and assigns it to the Rankings field.
func (o *ListSourceRankings200Response) SetRankings(v []SourceRanking) {
	o.Rankings = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ListSourceRankings200Response) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSourceRankings200Response) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ListSourceRankings200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ListSourceRankings200Response) SetCount(v int32) {
	o.Count = &v
}

func (o ListSourceRankings200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSourceRankings200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rankings) {
		toSerialize["rankings"] = o.Rankings
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableListSourceRankings200Response struct {
	value *ListSourceRankings200Response
	isSet bool
}

func (v NullableListSourceRankings200Response) Get() *ListSourceRankings200Response {
	return v.value
}

func (v *NullableListSourceRankings200Response) Set(val *ListSourceRankings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListSourceRankings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListSourceRankings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSourceRankings200Response(val *ListSourceRankings200Response) *NullableListSourceRankings200Response {
	return &NullableListSourceRankings200Response{value: val, isSet: true}
}

func (v NullableListSourceRankings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSourceRankings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


