/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the BacktestReplay200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BacktestReplay200Response{}

// BacktestReplay200Response struct for BacktestReplay200Response
type BacktestReplay200Response struct {
	Ok *bool `json:"ok,omitempty"`
	Events []BacktestEvent `json:"events,omitempty"`
	// Cursor for the next page. Pass as `cursor` in the next request.
	NextCursor *int64 `json:"next_cursor,omitempty"`
	// Whether more events are available after this page
	HasMore *bool `json:"has_more,omitempty"`
	Meta *BacktestReplay200ResponseMeta `json:"meta,omitempty"`
}

// NewBacktestReplay200Response instantiates a new BacktestReplay200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBacktestReplay200Response() *BacktestReplay200Response {
	this := BacktestReplay200Response{}
	return &this
}

// NewBacktestReplay200ResponseWithDefaults instantiates a new BacktestReplay200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBacktestReplay200ResponseWithDefaults() *BacktestReplay200Response {
	this := BacktestReplay200Response{}
	return &this
}

// GetOk returns the Ok field value if set, zero value otherwise.
func (o *BacktestReplay200Response) GetOk() bool {
	if o == nil || IsNil(o.Ok) {
		var ret bool
		return ret
	}
	return *o.Ok
}

// GetOkOk returns a tuple with the Ok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200Response) GetOkOk() (*bool, bool) {
	if o == nil || IsNil(o.Ok) {
		return nil, false
	}
	return o.Ok, true
}

// HasOk returns a boolean if a field has been set.
func (o *BacktestReplay200Response) HasOk() bool {
	if o != nil && !IsNil(o.Ok) {
		return true
	}

	return false
}

// SetOk gets a reference to the given bool and assigns it to the Ok field.
func (o *BacktestReplay200Response) SetOk(v bool) {
	o.Ok = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *BacktestReplay200Response) GetEvents() []BacktestEvent {
	if o == nil || IsNil(o.Events) {
		var ret []BacktestEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200Response) GetEventsOk() ([]BacktestEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *BacktestReplay200Response) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []BacktestEvent and assigns it to the Events field.
func (o *BacktestReplay200Response) SetEvents(v []BacktestEvent) {
	o.Events = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *BacktestReplay200Response) GetNextCursor() int64 {
	if o == nil || IsNil(o.NextCursor) {
		var ret int64
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200Response) GetNextCursorOk() (*int64, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *BacktestReplay200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given int64 and assigns it to the NextCursor field.
func (o *BacktestReplay200Response) SetNextCursor(v int64) {
	o.NextCursor = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *BacktestReplay200Response) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *BacktestReplay200Response) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *BacktestReplay200Response) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BacktestReplay200Response) GetMeta() BacktestReplay200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret BacktestReplay200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200Response) GetMetaOk() (*BacktestReplay200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BacktestReplay200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given BacktestReplay200ResponseMeta and assigns it to the Meta field.
func (o *BacktestReplay200Response) SetMeta(v BacktestReplay200ResponseMeta) {
	o.Meta = &v
}

func (o BacktestReplay200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BacktestReplay200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ok) {
		toSerialize["ok"] = o.Ok
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	if !IsNil(o.HasMore) {
		toSerialize["has_more"] = o.HasMore
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableBacktestReplay200Response struct {
	value *BacktestReplay200Response
	isSet bool
}

func (v NullableBacktestReplay200Response) Get() *BacktestReplay200Response {
	return v.value
}

func (v *NullableBacktestReplay200Response) Set(val *BacktestReplay200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBacktestReplay200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBacktestReplay200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBacktestReplay200Response(val *BacktestReplay200Response) *NullableBacktestReplay200Response {
	return &NullableBacktestReplay200Response{value: val, isSet: true}
}

func (v NullableBacktestReplay200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBacktestReplay200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


