/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetUsage200ResponseQuota type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsage200ResponseQuota{}

// GetUsage200ResponseQuota struct for GetUsage200ResponseQuota
type GetUsage200ResponseQuota struct {
	MonthlyLimit *int32 `json:"monthly_limit,omitempty"`
	MonthlyUsed *int32 `json:"monthly_used,omitempty"`
	PctUsed *int32 `json:"pct_used,omitempty"`
	GraceLimit *int32 `json:"grace_limit,omitempty"`
	ResetsAtMs *int64 `json:"resets_at_ms,omitempty"`
}

// NewGetUsage200ResponseQuota instantiates a new GetUsage200ResponseQuota object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsage200ResponseQuota() *GetUsage200ResponseQuota {
	this := GetUsage200ResponseQuota{}
	return &this
}

// NewGetUsage200ResponseQuotaWithDefaults instantiates a new GetUsage200ResponseQuota object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsage200ResponseQuotaWithDefaults() *GetUsage200ResponseQuota {
	this := GetUsage200ResponseQuota{}
	return &this
}

// GetMonthlyLimit returns the MonthlyLimit field value if set, zero value otherwise.
func (o *GetUsage200ResponseQuota) GetMonthlyLimit() int32 {
	if o == nil || IsNil(o.MonthlyLimit) {
		var ret int32
		return ret
	}
	return *o.MonthlyLimit
}

// GetMonthlyLimitOk returns a tuple with the MonthlyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseQuota) GetMonthlyLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.MonthlyLimit) {
		return nil, false
	}
	return o.MonthlyLimit, true
}

// HasMonthlyLimit returns a boolean if a field has been set.
func (o *GetUsage200ResponseQuota) HasMonthlyLimit() bool {
	if o != nil && !IsNil(o.MonthlyLimit) {
		return true
	}

	return false
}

// SetMonthlyLimit gets a reference to the given int32 and assigns it to the MonthlyLimit field.
func (o *GetUsage200ResponseQuota) SetMonthlyLimit(v int32) {
	o.MonthlyLimit = &v
}

// GetMonthlyUsed returns the MonthlyUsed field value if set, zero value otherwise.
func (o *GetUsage200ResponseQuota) GetMonthlyUsed() int32 {
	if o == nil || IsNil(o.MonthlyUsed) {
		var ret int32
		return ret
	}
	return *o.MonthlyUsed
}

// GetMonthlyUsedOk returns a tuple with the MonthlyUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseQuota) GetMonthlyUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.MonthlyUsed) {
		return nil, false
	}
	return o.MonthlyUsed, true
}

// HasMonthlyUsed returns a boolean if a field has been set.
func (o *GetUsage200ResponseQuota) HasMonthlyUsed() bool {
	if o != nil && !IsNil(o.MonthlyUsed) {
		return true
	}

	return false
}

// SetMonthlyUsed gets a reference to the given int32 and assigns it to the MonthlyUsed field.
func (o *GetUsage200ResponseQuota) SetMonthlyUsed(v int32) {
	o.MonthlyUsed = &v
}

// GetPctUsed returns the PctUsed field value if set, zero value otherwise.
func (o *GetUsage200ResponseQuota) GetPctUsed() int32 {
	if o == nil || IsNil(o.PctUsed) {
		var ret int32
		return ret
	}
	return *o.PctUsed
}

// GetPctUsedOk returns a tuple with the PctUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseQuota) GetPctUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.PctUsed) {
		return nil, false
	}
	return o.PctUsed, true
}

// HasPctUsed returns a boolean if a field has been set.
func (o *GetUsage200ResponseQuota) HasPctUsed() bool {
	if o != nil && !IsNil(o.PctUsed) {
		return true
	}

	return false
}

// SetPctUsed gets a reference to the given int32 and assigns it to the PctUsed field.
func (o *GetUsage200ResponseQuota) SetPctUsed(v int32) {
	o.PctUsed = &v
}

// GetGraceLimit returns the GraceLimit field value if set, zero value otherwise.
func (o *GetUsage200ResponseQuota) GetGraceLimit() int32 {
	if o == nil || IsNil(o.GraceLimit) {
		var ret int32
		return ret
	}
	return *o.GraceLimit
}

// GetGraceLimitOk returns a tuple with the GraceLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseQuota) GetGraceLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.GraceLimit) {
		return nil, false
	}
	return o.GraceLimit, true
}

// HasGraceLimit returns a boolean if a field has been set.
func (o *GetUsage200ResponseQuota) HasGraceLimit() bool {
	if o != nil && !IsNil(o.GraceLimit) {
		return true
	}

	return false
}

// SetGraceLimit gets a reference to the given int32 and assigns it to the GraceLimit field.
func (o *GetUsage200ResponseQuota) SetGraceLimit(v int32) {
	o.GraceLimit = &v
}

// GetResetsAtMs returns the ResetsAtMs field value if set, zero value otherwise.
func (o *GetUsage200ResponseQuota) GetResetsAtMs() int64 {
	if o == nil || IsNil(o.ResetsAtMs) {
		var ret int64
		return ret
	}
	return *o.ResetsAtMs
}

// GetResetsAtMsOk returns a tuple with the ResetsAtMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage200ResponseQuota) GetResetsAtMsOk() (*int64, bool) {
	if o == nil || IsNil(o.ResetsAtMs) {
		return nil, false
	}
	return o.ResetsAtMs, true
}

// HasResetsAtMs returns a boolean if a field has been set.
func (o *GetUsage200ResponseQuota) HasResetsAtMs() bool {
	if o != nil && !IsNil(o.ResetsAtMs) {
		return true
	}

	return false
}

// SetResetsAtMs gets a reference to the given int64 and assigns it to the ResetsAtMs field.
func (o *GetUsage200ResponseQuota) SetResetsAtMs(v int64) {
	o.ResetsAtMs = &v
}

func (o GetUsage200ResponseQuota) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsage200ResponseQuota) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MonthlyLimit) {
		toSerialize["monthly_limit"] = o.MonthlyLimit
	}
	if !IsNil(o.MonthlyUsed) {
		toSerialize["monthly_used"] = o.MonthlyUsed
	}
	if !IsNil(o.PctUsed) {
		toSerialize["pct_used"] = o.PctUsed
	}
	if !IsNil(o.GraceLimit) {
		toSerialize["grace_limit"] = o.GraceLimit
	}
	if !IsNil(o.ResetsAtMs) {
		toSerialize["resets_at_ms"] = o.ResetsAtMs
	}
	return toSerialize, nil
}

type NullableGetUsage200ResponseQuota struct {
	value *GetUsage200ResponseQuota
	isSet bool
}

func (v NullableGetUsage200ResponseQuota) Get() *GetUsage200ResponseQuota {
	return v.value
}

func (v *NullableGetUsage200ResponseQuota) Set(val *GetUsage200ResponseQuota) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsage200ResponseQuota) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsage200ResponseQuota) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsage200ResponseQuota(val *GetUsage200ResponseQuota) *NullableGetUsage200ResponseQuota {
	return &NullableGetUsage200ResponseQuota{value: val, isSet: true}
}

func (v NullableGetUsage200ResponseQuota) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsage200ResponseQuota) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


