/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the BacktestReplayWithEmbeddings200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BacktestReplayWithEmbeddings200Response{}

// BacktestReplayWithEmbeddings200Response struct for BacktestReplayWithEmbeddings200Response
type BacktestReplayWithEmbeddings200Response struct {
	Ok *bool `json:"ok,omitempty"`
	Events []BacktestEvent `json:"events,omitempty"`
	NextCursor *int64 `json:"next_cursor,omitempty"`
	HasMore *bool `json:"has_more,omitempty"`
	Meta *BacktestReplayWithEmbeddings200ResponseMeta `json:"meta,omitempty"`
}

// NewBacktestReplayWithEmbeddings200Response instantiates a new BacktestReplayWithEmbeddings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBacktestReplayWithEmbeddings200Response() *BacktestReplayWithEmbeddings200Response {
	this := BacktestReplayWithEmbeddings200Response{}
	return &this
}

// NewBacktestReplayWithEmbeddings200ResponseWithDefaults instantiates a new BacktestReplayWithEmbeddings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBacktestReplayWithEmbeddings200ResponseWithDefaults() *BacktestReplayWithEmbeddings200Response {
	this := BacktestReplayWithEmbeddings200Response{}
	return &this
}

// GetOk returns the Ok field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddings200Response) GetOk() bool {
	if o == nil || IsNil(o.Ok) {
		var ret bool
		return ret
	}
	return *o.Ok
}

// GetOkOk returns a tuple with the Ok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddings200Response) GetOkOk() (*bool, bool) {
	if o == nil || IsNil(o.Ok) {
		return nil, false
	}
	return o.Ok, true
}

// HasOk returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddings200Response) HasOk() bool {
	if o != nil && !IsNil(o.Ok) {
		return true
	}

	return false
}

// SetOk gets a reference to the given bool and assigns it to the Ok field.
func (o *BacktestReplayWithEmbeddings200Response) SetOk(v bool) {
	o.Ok = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddings200Response) GetEvents() []BacktestEvent {
	if o == nil || IsNil(o.Events) {
		var ret []BacktestEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddings200Response) GetEventsOk() ([]BacktestEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddings200Response) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []BacktestEvent and assigns it to the Events field.
func (o *BacktestReplayWithEmbeddings200Response) SetEvents(v []BacktestEvent) {
	o.Events = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddings200Response) GetNextCursor() int64 {
	if o == nil || IsNil(o.NextCursor) {
		var ret int64
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddings200Response) GetNextCursorOk() (*int64, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddings200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given int64 and assigns it to the NextCursor field.
func (o *BacktestReplayWithEmbeddings200Response) SetNextCursor(v int64) {
	o.NextCursor = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddings200Response) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddings200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddings200Response) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *BacktestReplayWithEmbeddings200Response) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddings200Response) GetMeta() BacktestReplayWithEmbeddings200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret BacktestReplayWithEmbeddings200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddings200Response) GetMetaOk() (*BacktestReplayWithEmbeddings200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddings200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given BacktestReplayWithEmbeddings200ResponseMeta and assigns it to the Meta field.
func (o *BacktestReplayWithEmbeddings200Response) SetMeta(v BacktestReplayWithEmbeddings200ResponseMeta) {
	o.Meta = &v
}

func (o BacktestReplayWithEmbeddings200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BacktestReplayWithEmbeddings200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ok) {
		toSerialize["ok"] = o.Ok
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	if !IsNil(o.HasMore) {
		toSerialize["has_more"] = o.HasMore
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableBacktestReplayWithEmbeddings200Response struct {
	value *BacktestReplayWithEmbeddings200Response
	isSet bool
}

func (v NullableBacktestReplayWithEmbeddings200Response) Get() *BacktestReplayWithEmbeddings200Response {
	return v.value
}

func (v *NullableBacktestReplayWithEmbeddings200Response) Set(val *BacktestReplayWithEmbeddings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBacktestReplayWithEmbeddings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBacktestReplayWithEmbeddings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBacktestReplayWithEmbeddings200Response(val *BacktestReplayWithEmbeddings200Response) *NullableBacktestReplayWithEmbeddings200Response {
	return &NullableBacktestReplayWithEmbeddings200Response{value: val, isSet: true}
}

func (v NullableBacktestReplayWithEmbeddings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBacktestReplayWithEmbeddings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


