/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the ApiVersionInfoSdkRecommendations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiVersionInfoSdkRecommendations{}

// ApiVersionInfoSdkRecommendations struct for ApiVersionInfoSdkRecommendations
type ApiVersionInfoSdkRecommendations struct {
	Typescript *string `json:"typescript,omitempty"`
	Python *string `json:"python,omitempty"`
}

// NewApiVersionInfoSdkRecommendations instantiates a new ApiVersionInfoSdkRecommendations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiVersionInfoSdkRecommendations() *ApiVersionInfoSdkRecommendations {
	this := ApiVersionInfoSdkRecommendations{}
	return &this
}

// NewApiVersionInfoSdkRecommendationsWithDefaults instantiates a new ApiVersionInfoSdkRecommendations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiVersionInfoSdkRecommendationsWithDefaults() *ApiVersionInfoSdkRecommendations {
	this := ApiVersionInfoSdkRecommendations{}
	return &this
}

// GetTypescript returns the Typescript field value if set, zero value otherwise.
func (o *ApiVersionInfoSdkRecommendations) GetTypescript() string {
	if o == nil || IsNil(o.Typescript) {
		var ret string
		return ret
	}
	return *o.Typescript
}

// GetTypescriptOk returns a tuple with the Typescript field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfoSdkRecommendations) GetTypescriptOk() (*string, bool) {
	if o == nil || IsNil(o.Typescript) {
		return nil, false
	}
	return o.Typescript, true
}

// HasTypescript returns a boolean if a field has been set.
func (o *ApiVersionInfoSdkRecommendations) HasTypescript() bool {
	if o != nil && !IsNil(o.Typescript) {
		return true
	}

	return false
}

// SetTypescript gets a reference to the given string and assigns it to the Typescript field.
func (o *ApiVersionInfoSdkRecommendations) SetTypescript(v string) {
	o.Typescript = &v
}

// GetPython returns the Python field value if set, zero value otherwise.
func (o *ApiVersionInfoSdkRecommendations) GetPython() string {
	if o == nil || IsNil(o.Python) {
		var ret string
		return ret
	}
	return *o.Python
}

// GetPythonOk returns a tuple with the Python field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfoSdkRecommendations) GetPythonOk() (*string, bool) {
	if o == nil || IsNil(o.Python) {
		return nil, false
	}
	return o.Python, true
}

// HasPython returns a boolean if a field has been set.
func (o *ApiVersionInfoSdkRecommendations) HasPython() bool {
	if o != nil && !IsNil(o.Python) {
		return true
	}

	return false
}

// SetPython gets a reference to the given string and assigns it to the Python field.
func (o *ApiVersionInfoSdkRecommendations) SetPython(v string) {
	o.Python = &v
}

func (o ApiVersionInfoSdkRecommendations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiVersionInfoSdkRecommendations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Typescript) {
		toSerialize["typescript"] = o.Typescript
	}
	if !IsNil(o.Python) {
		toSerialize["python"] = o.Python
	}
	return toSerialize, nil
}

type NullableApiVersionInfoSdkRecommendations struct {
	value *ApiVersionInfoSdkRecommendations
	isSet bool
}

func (v NullableApiVersionInfoSdkRecommendations) Get() *ApiVersionInfoSdkRecommendations {
	return v.value
}

func (v *NullableApiVersionInfoSdkRecommendations) Set(val *ApiVersionInfoSdkRecommendations) {
	v.value = val
	v.isSet = true
}

func (v NullableApiVersionInfoSdkRecommendations) IsSet() bool {
	return v.isSet
}

func (v *NullableApiVersionInfoSdkRecommendations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiVersionInfoSdkRecommendations(val *ApiVersionInfoSdkRecommendations) *NullableApiVersionInfoSdkRecommendations {
	return &NullableApiVersionInfoSdkRecommendations{value: val, isSet: true}
}

func (v NullableApiVersionInfoSdkRecommendations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiVersionInfoSdkRecommendations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


