/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetEntityNetwork200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEntityNetwork200Response{}

// GetEntityNetwork200Response struct for GetEntityNetwork200Response
type GetEntityNetwork200Response struct {
	Nodes []GraphNode `json:"nodes,omitempty"`
	Edges []GraphEdge `json:"edges,omitempty"`
}

// NewGetEntityNetwork200Response instantiates a new GetEntityNetwork200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEntityNetwork200Response() *GetEntityNetwork200Response {
	this := GetEntityNetwork200Response{}
	return &this
}

// NewGetEntityNetwork200ResponseWithDefaults instantiates a new GetEntityNetwork200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEntityNetwork200ResponseWithDefaults() *GetEntityNetwork200Response {
	this := GetEntityNetwork200Response{}
	return &this
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *GetEntityNetwork200Response) GetNodes() []GraphNode {
	if o == nil || IsNil(o.Nodes) {
		var ret []GraphNode
		return ret
	}
	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntityNetwork200Response) GetNodesOk() ([]GraphNode, bool) {
	if o == nil || IsNil(o.Nodes) {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *GetEntityNetwork200Response) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given []GraphNode and assigns it to the Nodes field.
func (o *GetEntityNetwork200Response) SetNodes(v []GraphNode) {
	o.Nodes = v
}

// GetEdges returns the Edges field value if set, zero value otherwise.
func (o *GetEntityNetwork200Response) GetEdges() []GraphEdge {
	if o == nil || IsNil(o.Edges) {
		var ret []GraphEdge
		return ret
	}
	return o.Edges
}

// GetEdgesOk returns a tuple with the Edges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntityNetwork200Response) GetEdgesOk() ([]GraphEdge, bool) {
	if o == nil || IsNil(o.Edges) {
		return nil, false
	}
	return o.Edges, true
}

// HasEdges returns a boolean if a field has been set.
func (o *GetEntityNetwork200Response) HasEdges() bool {
	if o != nil && !IsNil(o.Edges) {
		return true
	}

	return false
}

// SetEdges gets a reference to the given []GraphEdge and assigns it to the Edges field.
func (o *GetEntityNetwork200Response) SetEdges(v []GraphEdge) {
	o.Edges = v
}

func (o GetEntityNetwork200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEntityNetwork200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	if !IsNil(o.Edges) {
		toSerialize["edges"] = o.Edges
	}
	return toSerialize, nil
}

type NullableGetEntityNetwork200Response struct {
	value *GetEntityNetwork200Response
	isSet bool
}

func (v NullableGetEntityNetwork200Response) Get() *GetEntityNetwork200Response {
	return v.value
}

func (v *NullableGetEntityNetwork200Response) Set(val *GetEntityNetwork200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEntityNetwork200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEntityNetwork200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEntityNetwork200Response(val *GetEntityNetwork200Response) *NullableGetEntityNetwork200Response {
	return &NullableGetEntityNetwork200Response{value: val, isSet: true}
}

func (v NullableGetEntityNetwork200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEntityNetwork200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


