/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
	"time"
)

// checks if the ApiVersionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiVersionInfo{}

// ApiVersionInfo struct for ApiVersionInfo
type ApiVersionInfo struct {
	ApiMajor *string `json:"api_major,omitempty"`
	ApiLatest *string `json:"api_latest,omitempty"`
	SupportedApiMajors []string `json:"supported_api_majors,omitempty"`
	Sunset map[string]string `json:"sunset,omitempty"`
	SdkRecommendations *ApiVersionInfoSdkRecommendations `json:"sdk_recommendations,omitempty"`
	GeneratedAt *time.Time `json:"generated_at,omitempty"`
}

// NewApiVersionInfo instantiates a new ApiVersionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiVersionInfo() *ApiVersionInfo {
	this := ApiVersionInfo{}
	return &this
}

// NewApiVersionInfoWithDefaults instantiates a new ApiVersionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiVersionInfoWithDefaults() *ApiVersionInfo {
	this := ApiVersionInfo{}
	return &this
}

// GetApiMajor returns the ApiMajor field value if set, zero value otherwise.
func (o *ApiVersionInfo) GetApiMajor() string {
	if o == nil || IsNil(o.ApiMajor) {
		var ret string
		return ret
	}
	return *o.ApiMajor
}

// GetApiMajorOk returns a tuple with the ApiMajor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfo) GetApiMajorOk() (*string, bool) {
	if o == nil || IsNil(o.ApiMajor) {
		return nil, false
	}
	return o.ApiMajor, true
}

// HasApiMajor returns a boolean if a field has been set.
func (o *ApiVersionInfo) HasApiMajor() bool {
	if o != nil && !IsNil(o.ApiMajor) {
		return true
	}

	return false
}

// SetApiMajor gets a reference to the given string and assigns it to the ApiMajor field.
func (o *ApiVersionInfo) SetApiMajor(v string) {
	o.ApiMajor = &v
}

// GetApiLatest returns the ApiLatest field value if set, zero value otherwise.
func (o *ApiVersionInfo) GetApiLatest() string {
	if o == nil || IsNil(o.ApiLatest) {
		var ret string
		return ret
	}
	return *o.ApiLatest
}

// GetApiLatestOk returns a tuple with the ApiLatest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfo) GetApiLatestOk() (*string, bool) {
	if o == nil || IsNil(o.ApiLatest) {
		return nil, false
	}
	return o.ApiLatest, true
}

// HasApiLatest returns a boolean if a field has been set.
func (o *ApiVersionInfo) HasApiLatest() bool {
	if o != nil && !IsNil(o.ApiLatest) {
		return true
	}

	return false
}

// SetApiLatest gets a reference to the given string and assigns it to the ApiLatest field.
func (o *ApiVersionInfo) SetApiLatest(v string) {
	o.ApiLatest = &v
}

// GetSupportedApiMajors returns the SupportedApiMajors field value if set, zero value otherwise.
func (o *ApiVersionInfo) GetSupportedApiMajors() []string {
	if o == nil || IsNil(o.SupportedApiMajors) {
		var ret []string
		return ret
	}
	return o.SupportedApiMajors
}

// GetSupportedApiMajorsOk returns a tuple with the SupportedApiMajors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfo) GetSupportedApiMajorsOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportedApiMajors) {
		return nil, false
	}
	return o.SupportedApiMajors, true
}

// HasSupportedApiMajors returns a boolean if a field has been set.
func (o *ApiVersionInfo) HasSupportedApiMajors() bool {
	if o != nil && !IsNil(o.SupportedApiMajors) {
		return true
	}

	return false
}

// SetSupportedApiMajors gets a reference to the given []string and assigns it to the SupportedApiMajors field.
func (o *ApiVersionInfo) SetSupportedApiMajors(v []string) {
	o.SupportedApiMajors = v
}

// GetSunset returns the Sunset field value if set, zero value otherwise.
func (o *ApiVersionInfo) GetSunset() map[string]string {
	if o == nil || IsNil(o.Sunset) {
		var ret map[string]string
		return ret
	}
	return o.Sunset
}

// GetSunsetOk returns a tuple with the Sunset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfo) GetSunsetOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Sunset) {
		return map[string]string{}, false
	}
	return o.Sunset, true
}

// HasSunset returns a boolean if a field has been set.
func (o *ApiVersionInfo) HasSunset() bool {
	if o != nil && !IsNil(o.Sunset) {
		return true
	}

	return false
}

// SetSunset gets a reference to the given map[string]string and assigns it to the Sunset field.
func (o *ApiVersionInfo) SetSunset(v map[string]string) {
	o.Sunset = v
}

// GetSdkRecommendations returns the SdkRecommendations field value if set, zero value otherwise.
func (o *ApiVersionInfo) GetSdkRecommendations() ApiVersionInfoSdkRecommendations {
	if o == nil || IsNil(o.SdkRecommendations) {
		var ret ApiVersionInfoSdkRecommendations
		return ret
	}
	return *o.SdkRecommendations
}

// GetSdkRecommendationsOk returns a tuple with the SdkRecommendations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfo) GetSdkRecommendationsOk() (*ApiVersionInfoSdkRecommendations, bool) {
	if o == nil || IsNil(o.SdkRecommendations) {
		return nil, false
	}
	return o.SdkRecommendations, true
}

// HasSdkRecommendations returns a boolean if a field has been set.
func (o *ApiVersionInfo) HasSdkRecommendations() bool {
	if o != nil && !IsNil(o.SdkRecommendations) {
		return true
	}

	return false
}

// SetSdkRecommendations gets a reference to the given ApiVersionInfoSdkRecommendations and assigns it to the SdkRecommendations field.
func (o *ApiVersionInfo) SetSdkRecommendations(v ApiVersionInfoSdkRecommendations) {
	o.SdkRecommendations = &v
}

// GetGeneratedAt returns the GeneratedAt field value if set, zero value otherwise.
func (o *ApiVersionInfo) GetGeneratedAt() time.Time {
	if o == nil || IsNil(o.GeneratedAt) {
		var ret time.Time
		return ret
	}
	return *o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiVersionInfo) GetGeneratedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.GeneratedAt) {
		return nil, false
	}
	return o.GeneratedAt, true
}

// HasGeneratedAt returns a boolean if a field has been set.
func (o *ApiVersionInfo) HasGeneratedAt() bool {
	if o != nil && !IsNil(o.GeneratedAt) {
		return true
	}

	return false
}

// SetGeneratedAt gets a reference to the given time.Time and assigns it to the GeneratedAt field.
func (o *ApiVersionInfo) SetGeneratedAt(v time.Time) {
	o.GeneratedAt = &v
}

func (o ApiVersionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiVersionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiMajor) {
		toSerialize["api_major"] = o.ApiMajor
	}
	if !IsNil(o.ApiLatest) {
		toSerialize["api_latest"] = o.ApiLatest
	}
	if !IsNil(o.SupportedApiMajors) {
		toSerialize["supported_api_majors"] = o.SupportedApiMajors
	}
	if !IsNil(o.Sunset) {
		toSerialize["sunset"] = o.Sunset
	}
	if !IsNil(o.SdkRecommendations) {
		toSerialize["sdk_recommendations"] = o.SdkRecommendations
	}
	if !IsNil(o.GeneratedAt) {
		toSerialize["generated_at"] = o.GeneratedAt
	}
	return toSerialize, nil
}

type NullableApiVersionInfo struct {
	value *ApiVersionInfo
	isSet bool
}

func (v NullableApiVersionInfo) Get() *ApiVersionInfo {
	return v.value
}

func (v *NullableApiVersionInfo) Set(val *ApiVersionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableApiVersionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableApiVersionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiVersionInfo(val *ApiVersionInfo) *NullableApiVersionInfo {
	return &NullableApiVersionInfo{value: val, isSet: true}
}

func (v NullableApiVersionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiVersionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


