/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the ArticleContentTagsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleContentTagsInner{}

// ArticleContentTagsInner struct for ArticleContentTagsInner
type ArticleContentTagsInner struct {
	Tag *string `json:"tag,omitempty"`
	Score *float32 `json:"score,omitempty"`
}

// NewArticleContentTagsInner instantiates a new ArticleContentTagsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleContentTagsInner() *ArticleContentTagsInner {
	this := ArticleContentTagsInner{}
	return &this
}

// NewArticleContentTagsInnerWithDefaults instantiates a new ArticleContentTagsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleContentTagsInnerWithDefaults() *ArticleContentTagsInner {
	this := ArticleContentTagsInner{}
	return &this
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *ArticleContentTagsInner) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContentTagsInner) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *ArticleContentTagsInner) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *ArticleContentTagsInner) SetTag(v string) {
	o.Tag = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *ArticleContentTagsInner) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContentTagsInner) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *ArticleContentTagsInner) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *ArticleContentTagsInner) SetScore(v float32) {
	o.Score = &v
}

func (o ArticleContentTagsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleContentTagsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	return toSerialize, nil
}

type NullableArticleContentTagsInner struct {
	value *ArticleContentTagsInner
	isSet bool
}

func (v NullableArticleContentTagsInner) Get() *ArticleContentTagsInner {
	return v.value
}

func (v *NullableArticleContentTagsInner) Set(val *ArticleContentTagsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleContentTagsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleContentTagsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleContentTagsInner(val *ArticleContentTagsInner) *NullableArticleContentTagsInner {
	return &NullableArticleContentTagsInner{value: val, isSet: true}
}

func (v NullableArticleContentTagsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleContentTagsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


