/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BacktestReplayWithEmbeddingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BacktestReplayWithEmbeddingsRequest{}

// BacktestReplayWithEmbeddingsRequest struct for BacktestReplayWithEmbeddingsRequest
type BacktestReplayWithEmbeddingsRequest struct {
	// Start of time range (Unix milliseconds)
	From int64 `json:"from"`
	// End of time range (Unix milliseconds)
	To int64 `json:"to"`
	// Topic classes: `articles`, `stories`
	Topics []string `json:"topics,omitempty"`
	Categories []string `json:"categories,omitempty"`
	Sources []string `json:"sources,omitempty"`
	Keywords []string `json:"keywords,omitempty"`
	Entities []int32 `json:"entities,omitempty"`
	IncludeEmbeddings *bool `json:"include_embeddings,omitempty"`
	// Max 1 embedding filter per request
	EmbeddingFilters []BacktestEmbeddingFilter `json:"embedding_filters,omitempty"`
	Cursor *int64 `json:"cursor,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

type _BacktestReplayWithEmbeddingsRequest BacktestReplayWithEmbeddingsRequest

// NewBacktestReplayWithEmbeddingsRequest instantiates a new BacktestReplayWithEmbeddingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBacktestReplayWithEmbeddingsRequest(from int64, to int64) *BacktestReplayWithEmbeddingsRequest {
	this := BacktestReplayWithEmbeddingsRequest{}
	this.From = from
	this.To = to
	var includeEmbeddings bool = false
	this.IncludeEmbeddings = &includeEmbeddings
	var cursor int64 = 0
	this.Cursor = &cursor
	var limit int32 = 1000
	this.Limit = &limit
	return &this
}

// NewBacktestReplayWithEmbeddingsRequestWithDefaults instantiates a new BacktestReplayWithEmbeddingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBacktestReplayWithEmbeddingsRequestWithDefaults() *BacktestReplayWithEmbeddingsRequest {
	this := BacktestReplayWithEmbeddingsRequest{}
	var includeEmbeddings bool = false
	this.IncludeEmbeddings = &includeEmbeddings
	var cursor int64 = 0
	this.Cursor = &cursor
	var limit int32 = 1000
	this.Limit = &limit
	return &this
}

// GetFrom returns the From field value
func (o *BacktestReplayWithEmbeddingsRequest) GetFrom() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetFromOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *BacktestReplayWithEmbeddingsRequest) SetFrom(v int64) {
	o.From = v
}

// GetTo returns the To field value
func (o *BacktestReplayWithEmbeddingsRequest) GetTo() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetToOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *BacktestReplayWithEmbeddingsRequest) SetTo(v int64) {
	o.To = v
}

// GetTopics returns the Topics field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetTopics() []string {
	if o == nil || IsNil(o.Topics) {
		var ret []string
		return ret
	}
	return o.Topics
}

// GetTopicsOk returns a tuple with the Topics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetTopicsOk() ([]string, bool) {
	if o == nil || IsNil(o.Topics) {
		return nil, false
	}
	return o.Topics, true
}

// HasTopics returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasTopics() bool {
	if o != nil && !IsNil(o.Topics) {
		return true
	}

	return false
}

// SetTopics gets a reference to the given []string and assigns it to the Topics field.
func (o *BacktestReplayWithEmbeddingsRequest) SetTopics(v []string) {
	o.Topics = v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *BacktestReplayWithEmbeddingsRequest) SetCategories(v []string) {
	o.Categories = v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetSources() []string {
	if o == nil || IsNil(o.Sources) {
		var ret []string
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []string and assigns it to the Sources field.
func (o *BacktestReplayWithEmbeddingsRequest) SetSources(v []string) {
	o.Sources = v
}

// GetKeywords returns the Keywords field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetKeywords() []string {
	if o == nil || IsNil(o.Keywords) {
		var ret []string
		return ret
	}
	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetKeywordsOk() ([]string, bool) {
	if o == nil || IsNil(o.Keywords) {
		return nil, false
	}
	return o.Keywords, true
}

// HasKeywords returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasKeywords() bool {
	if o != nil && !IsNil(o.Keywords) {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given []string and assigns it to the Keywords field.
func (o *BacktestReplayWithEmbeddingsRequest) SetKeywords(v []string) {
	o.Keywords = v
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetEntities() []int32 {
	if o == nil || IsNil(o.Entities) {
		var ret []int32
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetEntitiesOk() ([]int32, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []int32 and assigns it to the Entities field.
func (o *BacktestReplayWithEmbeddingsRequest) SetEntities(v []int32) {
	o.Entities = v
}

// GetIncludeEmbeddings returns the IncludeEmbeddings field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetIncludeEmbeddings() bool {
	if o == nil || IsNil(o.IncludeEmbeddings) {
		var ret bool
		return ret
	}
	return *o.IncludeEmbeddings
}

// GetIncludeEmbeddingsOk returns a tuple with the IncludeEmbeddings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetIncludeEmbeddingsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeEmbeddings) {
		return nil, false
	}
	return o.IncludeEmbeddings, true
}

// HasIncludeEmbeddings returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasIncludeEmbeddings() bool {
	if o != nil && !IsNil(o.IncludeEmbeddings) {
		return true
	}

	return false
}

// SetIncludeEmbeddings gets a reference to the given bool and assigns it to the IncludeEmbeddings field.
func (o *BacktestReplayWithEmbeddingsRequest) SetIncludeEmbeddings(v bool) {
	o.IncludeEmbeddings = &v
}

// GetEmbeddingFilters returns the EmbeddingFilters field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetEmbeddingFilters() []BacktestEmbeddingFilter {
	if o == nil || IsNil(o.EmbeddingFilters) {
		var ret []BacktestEmbeddingFilter
		return ret
	}
	return o.EmbeddingFilters
}

// GetEmbeddingFiltersOk returns a tuple with the EmbeddingFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetEmbeddingFiltersOk() ([]BacktestEmbeddingFilter, bool) {
	if o == nil || IsNil(o.EmbeddingFilters) {
		return nil, false
	}
	return o.EmbeddingFilters, true
}

// HasEmbeddingFilters returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasEmbeddingFilters() bool {
	if o != nil && !IsNil(o.EmbeddingFilters) {
		return true
	}

	return false
}

// SetEmbeddingFilters gets a reference to the given []BacktestEmbeddingFilter and assigns it to the EmbeddingFilters field.
func (o *BacktestReplayWithEmbeddingsRequest) SetEmbeddingFilters(v []BacktestEmbeddingFilter) {
	o.EmbeddingFilters = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetCursor() int64 {
	if o == nil || IsNil(o.Cursor) {
		var ret int64
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetCursorOk() (*int64, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given int64 and assigns it to the Cursor field.
func (o *BacktestReplayWithEmbeddingsRequest) SetCursor(v int64) {
	o.Cursor = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *BacktestReplayWithEmbeddingsRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplayWithEmbeddingsRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *BacktestReplayWithEmbeddingsRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *BacktestReplayWithEmbeddingsRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o BacktestReplayWithEmbeddingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BacktestReplayWithEmbeddingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	if !IsNil(o.Topics) {
		toSerialize["topics"] = o.Topics
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.Keywords) {
		toSerialize["keywords"] = o.Keywords
	}
	if !IsNil(o.Entities) {
		toSerialize["entities"] = o.Entities
	}
	if !IsNil(o.IncludeEmbeddings) {
		toSerialize["include_embeddings"] = o.IncludeEmbeddings
	}
	if !IsNil(o.EmbeddingFilters) {
		toSerialize["embedding_filters"] = o.EmbeddingFilters
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

func (o *BacktestReplayWithEmbeddingsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBacktestReplayWithEmbeddingsRequest := _BacktestReplayWithEmbeddingsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBacktestReplayWithEmbeddingsRequest)

	if err != nil {
		return err
	}

	*o = BacktestReplayWithEmbeddingsRequest(varBacktestReplayWithEmbeddingsRequest)

	return err
}

type NullableBacktestReplayWithEmbeddingsRequest struct {
	value *BacktestReplayWithEmbeddingsRequest
	isSet bool
}

func (v NullableBacktestReplayWithEmbeddingsRequest) Get() *BacktestReplayWithEmbeddingsRequest {
	return v.value
}

func (v *NullableBacktestReplayWithEmbeddingsRequest) Set(val *BacktestReplayWithEmbeddingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBacktestReplayWithEmbeddingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBacktestReplayWithEmbeddingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBacktestReplayWithEmbeddingsRequest(val *BacktestReplayWithEmbeddingsRequest) *NullableBacktestReplayWithEmbeddingsRequest {
	return &NullableBacktestReplayWithEmbeddingsRequest{value: val, isSet: true}
}

func (v NullableBacktestReplayWithEmbeddingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBacktestReplayWithEmbeddingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


