/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the StoryDevelopment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoryDevelopment{}

// StoryDevelopment struct for StoryDevelopment
type StoryDevelopment struct {
	Id *int32 `json:"id,omitempty"`
	ClusterId *int32 `json:"cluster_id,omitempty"`
	// Unix timestamp in milliseconds
	CreatedAtMs *int64 `json:"created_at_ms,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Significance *string `json:"significance,omitempty"`
	PreviousHeadline *string `json:"previous_headline,omitempty"`
	NewHeadline *string `json:"new_headline,omitempty"`
	TriggerArticleHashes []string `json:"trigger_article_hashes,omitempty"`
	EnrichmentSeq *int32 `json:"enrichment_seq,omitempty"`
}

// NewStoryDevelopment instantiates a new StoryDevelopment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoryDevelopment() *StoryDevelopment {
	this := StoryDevelopment{}
	return &this
}

// NewStoryDevelopmentWithDefaults instantiates a new StoryDevelopment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoryDevelopmentWithDefaults() *StoryDevelopment {
	this := StoryDevelopment{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StoryDevelopment) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StoryDevelopment) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *StoryDevelopment) SetId(v int32) {
	o.Id = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *StoryDevelopment) GetClusterId() int32 {
	if o == nil || IsNil(o.ClusterId) {
		var ret int32
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetClusterIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *StoryDevelopment) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given int32 and assigns it to the ClusterId field.
func (o *StoryDevelopment) SetClusterId(v int32) {
	o.ClusterId = &v
}

// GetCreatedAtMs returns the CreatedAtMs field value if set, zero value otherwise.
func (o *StoryDevelopment) GetCreatedAtMs() int64 {
	if o == nil || IsNil(o.CreatedAtMs) {
		var ret int64
		return ret
	}
	return *o.CreatedAtMs
}

// GetCreatedAtMsOk returns a tuple with the CreatedAtMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetCreatedAtMsOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAtMs) {
		return nil, false
	}
	return o.CreatedAtMs, true
}

// HasCreatedAtMs returns a boolean if a field has been set.
func (o *StoryDevelopment) HasCreatedAtMs() bool {
	if o != nil && !IsNil(o.CreatedAtMs) {
		return true
	}

	return false
}

// SetCreatedAtMs gets a reference to the given int64 and assigns it to the CreatedAtMs field.
func (o *StoryDevelopment) SetCreatedAtMs(v int64) {
	o.CreatedAtMs = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *StoryDevelopment) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *StoryDevelopment) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *StoryDevelopment) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StoryDevelopment) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StoryDevelopment) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StoryDevelopment) SetDescription(v string) {
	o.Description = &v
}

// GetSignificance returns the Significance field value if set, zero value otherwise.
func (o *StoryDevelopment) GetSignificance() string {
	if o == nil || IsNil(o.Significance) {
		var ret string
		return ret
	}
	return *o.Significance
}

// GetSignificanceOk returns a tuple with the Significance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetSignificanceOk() (*string, bool) {
	if o == nil || IsNil(o.Significance) {
		return nil, false
	}
	return o.Significance, true
}

// HasSignificance returns a boolean if a field has been set.
func (o *StoryDevelopment) HasSignificance() bool {
	if o != nil && !IsNil(o.Significance) {
		return true
	}

	return false
}

// SetSignificance gets a reference to the given string and assigns it to the Significance field.
func (o *StoryDevelopment) SetSignificance(v string) {
	o.Significance = &v
}

// GetPreviousHeadline returns the PreviousHeadline field value if set, zero value otherwise.
func (o *StoryDevelopment) GetPreviousHeadline() string {
	if o == nil || IsNil(o.PreviousHeadline) {
		var ret string
		return ret
	}
	return *o.PreviousHeadline
}

// GetPreviousHeadlineOk returns a tuple with the PreviousHeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetPreviousHeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.PreviousHeadline) {
		return nil, false
	}
	return o.PreviousHeadline, true
}

// HasPreviousHeadline returns a boolean if a field has been set.
func (o *StoryDevelopment) HasPreviousHeadline() bool {
	if o != nil && !IsNil(o.PreviousHeadline) {
		return true
	}

	return false
}

// SetPreviousHeadline gets a reference to the given string and assigns it to the PreviousHeadline field.
func (o *StoryDevelopment) SetPreviousHeadline(v string) {
	o.PreviousHeadline = &v
}

// GetNewHeadline returns the NewHeadline field value if set, zero value otherwise.
func (o *StoryDevelopment) GetNewHeadline() string {
	if o == nil || IsNil(o.NewHeadline) {
		var ret string
		return ret
	}
	return *o.NewHeadline
}

// GetNewHeadlineOk returns a tuple with the NewHeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetNewHeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.NewHeadline) {
		return nil, false
	}
	return o.NewHeadline, true
}

// HasNewHeadline returns a boolean if a field has been set.
func (o *StoryDevelopment) HasNewHeadline() bool {
	if o != nil && !IsNil(o.NewHeadline) {
		return true
	}

	return false
}

// SetNewHeadline gets a reference to the given string and assigns it to the NewHeadline field.
func (o *StoryDevelopment) SetNewHeadline(v string) {
	o.NewHeadline = &v
}

// GetTriggerArticleHashes returns the TriggerArticleHashes field value if set, zero value otherwise.
func (o *StoryDevelopment) GetTriggerArticleHashes() []string {
	if o == nil || IsNil(o.TriggerArticleHashes) {
		var ret []string
		return ret
	}
	return o.TriggerArticleHashes
}

// GetTriggerArticleHashesOk returns a tuple with the TriggerArticleHashes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetTriggerArticleHashesOk() ([]string, bool) {
	if o == nil || IsNil(o.TriggerArticleHashes) {
		return nil, false
	}
	return o.TriggerArticleHashes, true
}

// HasTriggerArticleHashes returns a boolean if a field has been set.
func (o *StoryDevelopment) HasTriggerArticleHashes() bool {
	if o != nil && !IsNil(o.TriggerArticleHashes) {
		return true
	}

	return false
}

// SetTriggerArticleHashes gets a reference to the given []string and assigns it to the TriggerArticleHashes field.
func (o *StoryDevelopment) SetTriggerArticleHashes(v []string) {
	o.TriggerArticleHashes = v
}

// GetEnrichmentSeq returns the EnrichmentSeq field value if set, zero value otherwise.
func (o *StoryDevelopment) GetEnrichmentSeq() int32 {
	if o == nil || IsNil(o.EnrichmentSeq) {
		var ret int32
		return ret
	}
	return *o.EnrichmentSeq
}

// GetEnrichmentSeqOk returns a tuple with the EnrichmentSeq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoryDevelopment) GetEnrichmentSeqOk() (*int32, bool) {
	if o == nil || IsNil(o.EnrichmentSeq) {
		return nil, false
	}
	return o.EnrichmentSeq, true
}

// HasEnrichmentSeq returns a boolean if a field has been set.
func (o *StoryDevelopment) HasEnrichmentSeq() bool {
	if o != nil && !IsNil(o.EnrichmentSeq) {
		return true
	}

	return false
}

// SetEnrichmentSeq gets a reference to the given int32 and assigns it to the EnrichmentSeq field.
func (o *StoryDevelopment) SetEnrichmentSeq(v int32) {
	o.EnrichmentSeq = &v
}

func (o StoryDevelopment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoryDevelopment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ClusterId) {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if !IsNil(o.CreatedAtMs) {
		toSerialize["created_at_ms"] = o.CreatedAtMs
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Significance) {
		toSerialize["significance"] = o.Significance
	}
	if !IsNil(o.PreviousHeadline) {
		toSerialize["previous_headline"] = o.PreviousHeadline
	}
	if !IsNil(o.NewHeadline) {
		toSerialize["new_headline"] = o.NewHeadline
	}
	if !IsNil(o.TriggerArticleHashes) {
		toSerialize["trigger_article_hashes"] = o.TriggerArticleHashes
	}
	if !IsNil(o.EnrichmentSeq) {
		toSerialize["enrichment_seq"] = o.EnrichmentSeq
	}
	return toSerialize, nil
}

type NullableStoryDevelopment struct {
	value *StoryDevelopment
	isSet bool
}

func (v NullableStoryDevelopment) Get() *StoryDevelopment {
	return v.value
}

func (v *NullableStoryDevelopment) Set(val *StoryDevelopment) {
	v.value = val
	v.isSet = true
}

func (v NullableStoryDevelopment) IsSet() bool {
	return v.isSet
}

func (v *NullableStoryDevelopment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoryDevelopment(val *StoryDevelopment) *NullableStoryDevelopment {
	return &NullableStoryDevelopment{value: val, isSet: true}
}

func (v NullableStoryDevelopment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoryDevelopment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


