/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VectorSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorSearchRequest{}

// VectorSearchRequest struct for VectorSearchRequest
type VectorSearchRequest struct {
	// 1536-dimensional embedding vector (OpenAI text-embedding-3-small compatible)
	Embedding []float32 `json:"embedding"`
	// Which result types to include
	Types []string `json:"types,omitempty"`
	// Only search content from the last N hours
	SinceHours *int32 `json:"since_hours,omitempty"`
	// Maximum results per type
	Limit *int32 `json:"limit,omitempty"`
}

type _VectorSearchRequest VectorSearchRequest

// NewVectorSearchRequest instantiates a new VectorSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorSearchRequest(embedding []float32) *VectorSearchRequest {
	this := VectorSearchRequest{}
	this.Embedding = embedding
	var sinceHours int32 = 72
	this.SinceHours = &sinceHours
	var limit int32 = 20
	this.Limit = &limit
	return &this
}

// NewVectorSearchRequestWithDefaults instantiates a new VectorSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorSearchRequestWithDefaults() *VectorSearchRequest {
	this := VectorSearchRequest{}
	var sinceHours int32 = 72
	this.SinceHours = &sinceHours
	var limit int32 = 20
	this.Limit = &limit
	return &this
}

// GetEmbedding returns the Embedding field value
func (o *VectorSearchRequest) GetEmbedding() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.Embedding
}

// GetEmbeddingOk returns a tuple with the Embedding field value
// and a boolean to check if the value has been set.
func (o *VectorSearchRequest) GetEmbeddingOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Embedding, true
}

// SetEmbedding sets field value
func (o *VectorSearchRequest) SetEmbedding(v []float32) {
	o.Embedding = v
}

// GetTypes returns the Types field value if set, zero value otherwise.
func (o *VectorSearchRequest) GetTypes() []string {
	if o == nil || IsNil(o.Types) {
		var ret []string
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearchRequest) GetTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *VectorSearchRequest) HasTypes() bool {
	if o != nil && !IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given []string and assigns it to the Types field.
func (o *VectorSearchRequest) SetTypes(v []string) {
	o.Types = v
}

// GetSinceHours returns the SinceHours field value if set, zero value otherwise.
func (o *VectorSearchRequest) GetSinceHours() int32 {
	if o == nil || IsNil(o.SinceHours) {
		var ret int32
		return ret
	}
	return *o.SinceHours
}

// GetSinceHoursOk returns a tuple with the SinceHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearchRequest) GetSinceHoursOk() (*int32, bool) {
	if o == nil || IsNil(o.SinceHours) {
		return nil, false
	}
	return o.SinceHours, true
}

// HasSinceHours returns a boolean if a field has been set.
func (o *VectorSearchRequest) HasSinceHours() bool {
	if o != nil && !IsNil(o.SinceHours) {
		return true
	}

	return false
}

// SetSinceHours gets a reference to the given int32 and assigns it to the SinceHours field.
func (o *VectorSearchRequest) SetSinceHours(v int32) {
	o.SinceHours = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *VectorSearchRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearchRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *VectorSearchRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *VectorSearchRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o VectorSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["embedding"] = o.Embedding
	if !IsNil(o.Types) {
		toSerialize["types"] = o.Types
	}
	if !IsNil(o.SinceHours) {
		toSerialize["since_hours"] = o.SinceHours
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

func (o *VectorSearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"embedding",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVectorSearchRequest := _VectorSearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVectorSearchRequest)

	if err != nil {
		return err
	}

	*o = VectorSearchRequest(varVectorSearchRequest)

	return err
}

type NullableVectorSearchRequest struct {
	value *VectorSearchRequest
	isSet bool
}

func (v NullableVectorSearchRequest) Get() *VectorSearchRequest {
	return v.value
}

func (v *NullableVectorSearchRequest) Set(val *VectorSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorSearchRequest(val *VectorSearchRequest) *NullableVectorSearchRequest {
	return &NullableVectorSearchRequest{value: val, isSet: true}
}

func (v NullableVectorSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


