/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the BacktestReplay200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BacktestReplay200ResponseMeta{}

// BacktestReplay200ResponseMeta struct for BacktestReplay200ResponseMeta
type BacktestReplay200ResponseMeta struct {
	From *int64 `json:"from,omitempty"`
	To *int64 `json:"to,omitempty"`
	Topics []string `json:"topics,omitempty"`
	FiltersApplied map[string][]string `json:"filters_applied,omitempty"`
	EventCount *int32 `json:"event_count,omitempty"`
}

// NewBacktestReplay200ResponseMeta instantiates a new BacktestReplay200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBacktestReplay200ResponseMeta() *BacktestReplay200ResponseMeta {
	this := BacktestReplay200ResponseMeta{}
	return &this
}

// NewBacktestReplay200ResponseMetaWithDefaults instantiates a new BacktestReplay200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBacktestReplay200ResponseMetaWithDefaults() *BacktestReplay200ResponseMeta {
	this := BacktestReplay200ResponseMeta{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *BacktestReplay200ResponseMeta) GetFrom() int64 {
	if o == nil || IsNil(o.From) {
		var ret int64
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200ResponseMeta) GetFromOk() (*int64, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *BacktestReplay200ResponseMeta) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int64 and assigns it to the From field.
func (o *BacktestReplay200ResponseMeta) SetFrom(v int64) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *BacktestReplay200ResponseMeta) GetTo() int64 {
	if o == nil || IsNil(o.To) {
		var ret int64
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200ResponseMeta) GetToOk() (*int64, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *BacktestReplay200ResponseMeta) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given int64 and assigns it to the To field.
func (o *BacktestReplay200ResponseMeta) SetTo(v int64) {
	o.To = &v
}

// GetTopics returns the Topics field value if set, zero value otherwise.
func (o *BacktestReplay200ResponseMeta) GetTopics() []string {
	if o == nil || IsNil(o.Topics) {
		var ret []string
		return ret
	}
	return o.Topics
}

// GetTopicsOk returns a tuple with the Topics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200ResponseMeta) GetTopicsOk() ([]string, bool) {
	if o == nil || IsNil(o.Topics) {
		return nil, false
	}
	return o.Topics, true
}

// HasTopics returns a boolean if a field has been set.
func (o *BacktestReplay200ResponseMeta) HasTopics() bool {
	if o != nil && !IsNil(o.Topics) {
		return true
	}

	return false
}

// SetTopics gets a reference to the given []string and assigns it to the Topics field.
func (o *BacktestReplay200ResponseMeta) SetTopics(v []string) {
	o.Topics = v
}

// GetFiltersApplied returns the FiltersApplied field value if set, zero value otherwise.
func (o *BacktestReplay200ResponseMeta) GetFiltersApplied() map[string][]string {
	if o == nil || IsNil(o.FiltersApplied) {
		var ret map[string][]string
		return ret
	}
	return o.FiltersApplied
}

// GetFiltersAppliedOk returns a tuple with the FiltersApplied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200ResponseMeta) GetFiltersAppliedOk() (map[string][]string, bool) {
	if o == nil || IsNil(o.FiltersApplied) {
		return map[string][]string{}, false
	}
	return o.FiltersApplied, true
}

// HasFiltersApplied returns a boolean if a field has been set.
func (o *BacktestReplay200ResponseMeta) HasFiltersApplied() bool {
	if o != nil && !IsNil(o.FiltersApplied) {
		return true
	}

	return false
}

// SetFiltersApplied gets a reference to the given map[string][]string and assigns it to the FiltersApplied field.
func (o *BacktestReplay200ResponseMeta) SetFiltersApplied(v map[string][]string) {
	o.FiltersApplied = v
}

// GetEventCount returns the EventCount field value if set, zero value otherwise.
func (o *BacktestReplay200ResponseMeta) GetEventCount() int32 {
	if o == nil || IsNil(o.EventCount) {
		var ret int32
		return ret
	}
	return *o.EventCount
}

// GetEventCountOk returns a tuple with the EventCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BacktestReplay200ResponseMeta) GetEventCountOk() (*int32, bool) {
	if o == nil || IsNil(o.EventCount) {
		return nil, false
	}
	return o.EventCount, true
}

// HasEventCount returns a boolean if a field has been set.
func (o *BacktestReplay200ResponseMeta) HasEventCount() bool {
	if o != nil && !IsNil(o.EventCount) {
		return true
	}

	return false
}

// SetEventCount gets a reference to the given int32 and assigns it to the EventCount field.
func (o *BacktestReplay200ResponseMeta) SetEventCount(v int32) {
	o.EventCount = &v
}

func (o BacktestReplay200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BacktestReplay200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Topics) {
		toSerialize["topics"] = o.Topics
	}
	if !IsNil(o.FiltersApplied) {
		toSerialize["filters_applied"] = o.FiltersApplied
	}
	if !IsNil(o.EventCount) {
		toSerialize["event_count"] = o.EventCount
	}
	return toSerialize, nil
}

type NullableBacktestReplay200ResponseMeta struct {
	value *BacktestReplay200ResponseMeta
	isSet bool
}

func (v NullableBacktestReplay200ResponseMeta) Get() *BacktestReplay200ResponseMeta {
	return v.value
}

func (v *NullableBacktestReplay200ResponseMeta) Set(val *BacktestReplay200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableBacktestReplay200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableBacktestReplay200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBacktestReplay200ResponseMeta(val *BacktestReplay200ResponseMeta) *NullableBacktestReplay200ResponseMeta {
	return &NullableBacktestReplay200ResponseMeta{value: val, isSet: true}
}

func (v NullableBacktestReplay200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBacktestReplay200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


