/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetEmbedding200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmbedding200Response{}

// GetEmbedding200Response struct for GetEmbedding200Response
type GetEmbedding200Response struct {
	Ok *bool `json:"ok,omitempty"`
	Type *string `json:"type,omitempty"`
	Id *string `json:"id,omitempty"`
	Model *string `json:"model,omitempty"`
	Dimensions *int32 `json:"dimensions,omitempty"`
	Embedding *GetEmbedding200ResponseEmbedding `json:"embedding,omitempty"`
}

// NewGetEmbedding200Response instantiates a new GetEmbedding200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmbedding200Response() *GetEmbedding200Response {
	this := GetEmbedding200Response{}
	return &this
}

// NewGetEmbedding200ResponseWithDefaults instantiates a new GetEmbedding200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmbedding200ResponseWithDefaults() *GetEmbedding200Response {
	this := GetEmbedding200Response{}
	return &this
}

// GetOk returns the Ok field value if set, zero value otherwise.
func (o *GetEmbedding200Response) GetOk() bool {
	if o == nil || IsNil(o.Ok) {
		var ret bool
		return ret
	}
	return *o.Ok
}

// GetOkOk returns a tuple with the Ok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmbedding200Response) GetOkOk() (*bool, bool) {
	if o == nil || IsNil(o.Ok) {
		return nil, false
	}
	return o.Ok, true
}

// HasOk returns a boolean if a field has been set.
func (o *GetEmbedding200Response) HasOk() bool {
	if o != nil && !IsNil(o.Ok) {
		return true
	}

	return false
}

// SetOk gets a reference to the given bool and assigns it to the Ok field.
func (o *GetEmbedding200Response) SetOk(v bool) {
	o.Ok = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetEmbedding200Response) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmbedding200Response) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetEmbedding200Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetEmbedding200Response) SetType(v string) {
	o.Type = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetEmbedding200Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmbedding200Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetEmbedding200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetEmbedding200Response) SetId(v string) {
	o.Id = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *GetEmbedding200Response) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmbedding200Response) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *GetEmbedding200Response) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *GetEmbedding200Response) SetModel(v string) {
	o.Model = &v
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *GetEmbedding200Response) GetDimensions() int32 {
	if o == nil || IsNil(o.Dimensions) {
		var ret int32
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmbedding200Response) GetDimensionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *GetEmbedding200Response) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given int32 and assigns it to the Dimensions field.
func (o *GetEmbedding200Response) SetDimensions(v int32) {
	o.Dimensions = &v
}

// GetEmbedding returns the Embedding field value if set, zero value otherwise.
func (o *GetEmbedding200Response) GetEmbedding() GetEmbedding200ResponseEmbedding {
	if o == nil || IsNil(o.Embedding) {
		var ret GetEmbedding200ResponseEmbedding
		return ret
	}
	return *o.Embedding
}

// GetEmbeddingOk returns a tuple with the Embedding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmbedding200Response) GetEmbeddingOk() (*GetEmbedding200ResponseEmbedding, bool) {
	if o == nil || IsNil(o.Embedding) {
		return nil, false
	}
	return o.Embedding, true
}

// HasEmbedding returns a boolean if a field has been set.
func (o *GetEmbedding200Response) HasEmbedding() bool {
	if o != nil && !IsNil(o.Embedding) {
		return true
	}

	return false
}

// SetEmbedding gets a reference to the given GetEmbedding200ResponseEmbedding and assigns it to the Embedding field.
func (o *GetEmbedding200Response) SetEmbedding(v GetEmbedding200ResponseEmbedding) {
	o.Embedding = &v
}

func (o GetEmbedding200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmbedding200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ok) {
		toSerialize["ok"] = o.Ok
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	if !IsNil(o.Embedding) {
		toSerialize["embedding"] = o.Embedding
	}
	return toSerialize, nil
}

type NullableGetEmbedding200Response struct {
	value *GetEmbedding200Response
	isSet bool
}

func (v NullableGetEmbedding200Response) Get() *GetEmbedding200Response {
	return v.value
}

func (v *NullableGetEmbedding200Response) Set(val *GetEmbedding200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmbedding200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmbedding200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmbedding200Response(val *GetEmbedding200Response) *NullableGetEmbedding200Response {
	return &NullableGetEmbedding200Response{value: val, isSet: true}
}

func (v NullableGetEmbedding200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmbedding200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


