/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the GetStoryEntityGraph200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStoryEntityGraph200Response{}

// GetStoryEntityGraph200Response struct for GetStoryEntityGraph200Response
type GetStoryEntityGraph200Response struct {
	Story *Story `json:"story,omitempty"`
	Entities []EntityDetail `json:"entities,omitempty"`
	Edges []GetStoryEntityGraph200ResponseEdgesInner `json:"edges,omitempty"`
}

// NewGetStoryEntityGraph200Response instantiates a new GetStoryEntityGraph200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStoryEntityGraph200Response() *GetStoryEntityGraph200Response {
	this := GetStoryEntityGraph200Response{}
	return &this
}

// NewGetStoryEntityGraph200ResponseWithDefaults instantiates a new GetStoryEntityGraph200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStoryEntityGraph200ResponseWithDefaults() *GetStoryEntityGraph200Response {
	this := GetStoryEntityGraph200Response{}
	return &this
}

// GetStory returns the Story field value if set, zero value otherwise.
func (o *GetStoryEntityGraph200Response) GetStory() Story {
	if o == nil || IsNil(o.Story) {
		var ret Story
		return ret
	}
	return *o.Story
}

// GetStoryOk returns a tuple with the Story field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStoryEntityGraph200Response) GetStoryOk() (*Story, bool) {
	if o == nil || IsNil(o.Story) {
		return nil, false
	}
	return o.Story, true
}

// HasStory returns a boolean if a field has been set.
func (o *GetStoryEntityGraph200Response) HasStory() bool {
	if o != nil && !IsNil(o.Story) {
		return true
	}

	return false
}

// SetStory gets a reference to the given Story and assigns it to the Story field.
func (o *GetStoryEntityGraph200Response) SetStory(v Story) {
	o.Story = &v
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *GetStoryEntityGraph200Response) GetEntities() []EntityDetail {
	if o == nil || IsNil(o.Entities) {
		var ret []EntityDetail
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStoryEntityGraph200Response) GetEntitiesOk() ([]EntityDetail, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *GetStoryEntityGraph200Response) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []EntityDetail and assigns it to the Entities field.
func (o *GetStoryEntityGraph200Response) SetEntities(v []EntityDetail) {
	o.Entities = v
}

// GetEdges returns the Edges field value if set, zero value otherwise.
func (o *GetStoryEntityGraph200Response) GetEdges() []GetStoryEntityGraph200ResponseEdgesInner {
	if o == nil || IsNil(o.Edges) {
		var ret []GetStoryEntityGraph200ResponseEdgesInner
		return ret
	}
	return o.Edges
}

// GetEdgesOk returns a tuple with the Edges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStoryEntityGraph200Response) GetEdgesOk() ([]GetStoryEntityGraph200ResponseEdgesInner, bool) {
	if o == nil || IsNil(o.Edges) {
		return nil, false
	}
	return o.Edges, true
}

// HasEdges returns a boolean if a field has been set.
func (o *GetStoryEntityGraph200Response) HasEdges() bool {
	if o != nil && !IsNil(o.Edges) {
		return true
	}

	return false
}

// SetEdges gets a reference to the given []GetStoryEntityGraph200ResponseEdgesInner and assigns it to the Edges field.
func (o *GetStoryEntityGraph200Response) SetEdges(v []GetStoryEntityGraph200ResponseEdgesInner) {
	o.Edges = v
}

func (o GetStoryEntityGraph200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStoryEntityGraph200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Story) {
		toSerialize["story"] = o.Story
	}
	if !IsNil(o.Entities) {
		toSerialize["entities"] = o.Entities
	}
	if !IsNil(o.Edges) {
		toSerialize["edges"] = o.Edges
	}
	return toSerialize, nil
}

type NullableGetStoryEntityGraph200Response struct {
	value *GetStoryEntityGraph200Response
	isSet bool
}

func (v NullableGetStoryEntityGraph200Response) Get() *GetStoryEntityGraph200Response {
	return v.value
}

func (v *NullableGetStoryEntityGraph200Response) Set(val *GetStoryEntityGraph200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStoryEntityGraph200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStoryEntityGraph200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStoryEntityGraph200Response(val *GetStoryEntityGraph200Response) *NullableGetStoryEntityGraph200Response {
	return &NullableGetStoryEntityGraph200Response{value: val, isSet: true}
}

func (v NullableGetStoryEntityGraph200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStoryEntityGraph200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


