/*
NewsRank API

The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package newsrank

import (
	"encoding/json"
)

// checks if the ArticleContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleContent{}

// ArticleContent struct for ArticleContent
type ArticleContent struct {
	Ok *bool `json:"ok,omitempty"`
	UrlHash *string `json:"url_hash,omitempty"`
	FinalUrl *string `json:"final_url,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	ThumbUrl *string `json:"thumb_url,omitempty"`
	VideoUrl *string `json:"video_url,omitempty"`
	ExtractedTitle *string `json:"extracted_title,omitempty"`
	Text *string `json:"text,omitempty"`
	// Unix timestamp in milliseconds
	ExtractedAt *int64 `json:"extracted_at,omitempty"`
	Truncated *bool `json:"truncated,omitempty"`
	HeadlineSummary *string `json:"headline_summary,omitempty"`
	FullSummary *string `json:"full_summary,omitempty"`
	Tags []ArticleContentTagsInner `json:"tags,omitempty"`
}

// NewArticleContent instantiates a new ArticleContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleContent() *ArticleContent {
	this := ArticleContent{}
	return &this
}

// NewArticleContentWithDefaults instantiates a new ArticleContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleContentWithDefaults() *ArticleContent {
	this := ArticleContent{}
	return &this
}

// GetOk returns the Ok field value if set, zero value otherwise.
func (o *ArticleContent) GetOk() bool {
	if o == nil || IsNil(o.Ok) {
		var ret bool
		return ret
	}
	return *o.Ok
}

// GetOkOk returns a tuple with the Ok field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetOkOk() (*bool, bool) {
	if o == nil || IsNil(o.Ok) {
		return nil, false
	}
	return o.Ok, true
}

// HasOk returns a boolean if a field has been set.
func (o *ArticleContent) HasOk() bool {
	if o != nil && !IsNil(o.Ok) {
		return true
	}

	return false
}

// SetOk gets a reference to the given bool and assigns it to the Ok field.
func (o *ArticleContent) SetOk(v bool) {
	o.Ok = &v
}

// GetUrlHash returns the UrlHash field value if set, zero value otherwise.
func (o *ArticleContent) GetUrlHash() string {
	if o == nil || IsNil(o.UrlHash) {
		var ret string
		return ret
	}
	return *o.UrlHash
}

// GetUrlHashOk returns a tuple with the UrlHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetUrlHashOk() (*string, bool) {
	if o == nil || IsNil(o.UrlHash) {
		return nil, false
	}
	return o.UrlHash, true
}

// HasUrlHash returns a boolean if a field has been set.
func (o *ArticleContent) HasUrlHash() bool {
	if o != nil && !IsNil(o.UrlHash) {
		return true
	}

	return false
}

// SetUrlHash gets a reference to the given string and assigns it to the UrlHash field.
func (o *ArticleContent) SetUrlHash(v string) {
	o.UrlHash = &v
}

// GetFinalUrl returns the FinalUrl field value if set, zero value otherwise.
func (o *ArticleContent) GetFinalUrl() string {
	if o == nil || IsNil(o.FinalUrl) {
		var ret string
		return ret
	}
	return *o.FinalUrl
}

// GetFinalUrlOk returns a tuple with the FinalUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetFinalUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FinalUrl) {
		return nil, false
	}
	return o.FinalUrl, true
}

// HasFinalUrl returns a boolean if a field has been set.
func (o *ArticleContent) HasFinalUrl() bool {
	if o != nil && !IsNil(o.FinalUrl) {
		return true
	}

	return false
}

// SetFinalUrl gets a reference to the given string and assigns it to the FinalUrl field.
func (o *ArticleContent) SetFinalUrl(v string) {
	o.FinalUrl = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *ArticleContent) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *ArticleContent) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *ArticleContent) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetThumbUrl returns the ThumbUrl field value if set, zero value otherwise.
func (o *ArticleContent) GetThumbUrl() string {
	if o == nil || IsNil(o.ThumbUrl) {
		var ret string
		return ret
	}
	return *o.ThumbUrl
}

// GetThumbUrlOk returns a tuple with the ThumbUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetThumbUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbUrl) {
		return nil, false
	}
	return o.ThumbUrl, true
}

// HasThumbUrl returns a boolean if a field has been set.
func (o *ArticleContent) HasThumbUrl() bool {
	if o != nil && !IsNil(o.ThumbUrl) {
		return true
	}

	return false
}

// SetThumbUrl gets a reference to the given string and assigns it to the ThumbUrl field.
func (o *ArticleContent) SetThumbUrl(v string) {
	o.ThumbUrl = &v
}

// GetVideoUrl returns the VideoUrl field value if set, zero value otherwise.
func (o *ArticleContent) GetVideoUrl() string {
	if o == nil || IsNil(o.VideoUrl) {
		var ret string
		return ret
	}
	return *o.VideoUrl
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetVideoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.VideoUrl) {
		return nil, false
	}
	return o.VideoUrl, true
}

// HasVideoUrl returns a boolean if a field has been set.
func (o *ArticleContent) HasVideoUrl() bool {
	if o != nil && !IsNil(o.VideoUrl) {
		return true
	}

	return false
}

// SetVideoUrl gets a reference to the given string and assigns it to the VideoUrl field.
func (o *ArticleContent) SetVideoUrl(v string) {
	o.VideoUrl = &v
}

// GetExtractedTitle returns the ExtractedTitle field value if set, zero value otherwise.
func (o *ArticleContent) GetExtractedTitle() string {
	if o == nil || IsNil(o.ExtractedTitle) {
		var ret string
		return ret
	}
	return *o.ExtractedTitle
}

// GetExtractedTitleOk returns a tuple with the ExtractedTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetExtractedTitleOk() (*string, bool) {
	if o == nil || IsNil(o.ExtractedTitle) {
		return nil, false
	}
	return o.ExtractedTitle, true
}

// HasExtractedTitle returns a boolean if a field has been set.
func (o *ArticleContent) HasExtractedTitle() bool {
	if o != nil && !IsNil(o.ExtractedTitle) {
		return true
	}

	return false
}

// SetExtractedTitle gets a reference to the given string and assigns it to the ExtractedTitle field.
func (o *ArticleContent) SetExtractedTitle(v string) {
	o.ExtractedTitle = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ArticleContent) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ArticleContent) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ArticleContent) SetText(v string) {
	o.Text = &v
}

// GetExtractedAt returns the ExtractedAt field value if set, zero value otherwise.
func (o *ArticleContent) GetExtractedAt() int64 {
	if o == nil || IsNil(o.ExtractedAt) {
		var ret int64
		return ret
	}
	return *o.ExtractedAt
}

// GetExtractedAtOk returns a tuple with the ExtractedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetExtractedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ExtractedAt) {
		return nil, false
	}
	return o.ExtractedAt, true
}

// HasExtractedAt returns a boolean if a field has been set.
func (o *ArticleContent) HasExtractedAt() bool {
	if o != nil && !IsNil(o.ExtractedAt) {
		return true
	}

	return false
}

// SetExtractedAt gets a reference to the given int64 and assigns it to the ExtractedAt field.
func (o *ArticleContent) SetExtractedAt(v int64) {
	o.ExtractedAt = &v
}

// GetTruncated returns the Truncated field value if set, zero value otherwise.
func (o *ArticleContent) GetTruncated() bool {
	if o == nil || IsNil(o.Truncated) {
		var ret bool
		return ret
	}
	return *o.Truncated
}

// GetTruncatedOk returns a tuple with the Truncated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetTruncatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Truncated) {
		return nil, false
	}
	return o.Truncated, true
}

// HasTruncated returns a boolean if a field has been set.
func (o *ArticleContent) HasTruncated() bool {
	if o != nil && !IsNil(o.Truncated) {
		return true
	}

	return false
}

// SetTruncated gets a reference to the given bool and assigns it to the Truncated field.
func (o *ArticleContent) SetTruncated(v bool) {
	o.Truncated = &v
}

// GetHeadlineSummary returns the HeadlineSummary field value if set, zero value otherwise.
func (o *ArticleContent) GetHeadlineSummary() string {
	if o == nil || IsNil(o.HeadlineSummary) {
		var ret string
		return ret
	}
	return *o.HeadlineSummary
}

// GetHeadlineSummaryOk returns a tuple with the HeadlineSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetHeadlineSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.HeadlineSummary) {
		return nil, false
	}
	return o.HeadlineSummary, true
}

// HasHeadlineSummary returns a boolean if a field has been set.
func (o *ArticleContent) HasHeadlineSummary() bool {
	if o != nil && !IsNil(o.HeadlineSummary) {
		return true
	}

	return false
}

// SetHeadlineSummary gets a reference to the given string and assigns it to the HeadlineSummary field.
func (o *ArticleContent) SetHeadlineSummary(v string) {
	o.HeadlineSummary = &v
}

// GetFullSummary returns the FullSummary field value if set, zero value otherwise.
func (o *ArticleContent) GetFullSummary() string {
	if o == nil || IsNil(o.FullSummary) {
		var ret string
		return ret
	}
	return *o.FullSummary
}

// GetFullSummaryOk returns a tuple with the FullSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetFullSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.FullSummary) {
		return nil, false
	}
	return o.FullSummary, true
}

// HasFullSummary returns a boolean if a field has been set.
func (o *ArticleContent) HasFullSummary() bool {
	if o != nil && !IsNil(o.FullSummary) {
		return true
	}

	return false
}

// SetFullSummary gets a reference to the given string and assigns it to the FullSummary field.
func (o *ArticleContent) SetFullSummary(v string) {
	o.FullSummary = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ArticleContent) GetTags() []ArticleContentTagsInner {
	if o == nil || IsNil(o.Tags) {
		var ret []ArticleContentTagsInner
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleContent) GetTagsOk() ([]ArticleContentTagsInner, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ArticleContent) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []ArticleContentTagsInner and assigns it to the Tags field.
func (o *ArticleContent) SetTags(v []ArticleContentTagsInner) {
	o.Tags = v
}

func (o ArticleContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ok) {
		toSerialize["ok"] = o.Ok
	}
	if !IsNil(o.UrlHash) {
		toSerialize["url_hash"] = o.UrlHash
	}
	if !IsNil(o.FinalUrl) {
		toSerialize["final_url"] = o.FinalUrl
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.ThumbUrl) {
		toSerialize["thumb_url"] = o.ThumbUrl
	}
	if !IsNil(o.VideoUrl) {
		toSerialize["video_url"] = o.VideoUrl
	}
	if !IsNil(o.ExtractedTitle) {
		toSerialize["extracted_title"] = o.ExtractedTitle
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.ExtractedAt) {
		toSerialize["extracted_at"] = o.ExtractedAt
	}
	if !IsNil(o.Truncated) {
		toSerialize["truncated"] = o.Truncated
	}
	if !IsNil(o.HeadlineSummary) {
		toSerialize["headline_summary"] = o.HeadlineSummary
	}
	if !IsNil(o.FullSummary) {
		toSerialize["full_summary"] = o.FullSummary
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableArticleContent struct {
	value *ArticleContent
	isSet bool
}

func (v NullableArticleContent) Get() *ArticleContent {
	return v.value
}

func (v *NullableArticleContent) Set(val *ArticleContent) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleContent) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleContent(val *ArticleContent) *NullableArticleContent {
	return &NullableArticleContent{value: val, isSet: true}
}

func (v NullableArticleContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


